/*
Copyright 2021 Kong, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	konnectv1alpha1 "github.com/kong/kubernetes-configuration/v2/api/konnect/v1alpha1"
	scheme "github.com/kong/kubernetes-configuration/v2/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KonnectGatewayControlPlanesGetter has a method to return a KonnectGatewayControlPlaneInterface.
// A group's client should implement this interface.
type KonnectGatewayControlPlanesGetter interface {
	KonnectGatewayControlPlanes(namespace string) KonnectGatewayControlPlaneInterface
}

// KonnectGatewayControlPlaneInterface has methods to work with KonnectGatewayControlPlane resources.
type KonnectGatewayControlPlaneInterface interface {
	Create(ctx context.Context, konnectGatewayControlPlane *konnectv1alpha1.KonnectGatewayControlPlane, opts v1.CreateOptions) (*konnectv1alpha1.KonnectGatewayControlPlane, error)
	Update(ctx context.Context, konnectGatewayControlPlane *konnectv1alpha1.KonnectGatewayControlPlane, opts v1.UpdateOptions) (*konnectv1alpha1.KonnectGatewayControlPlane, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, konnectGatewayControlPlane *konnectv1alpha1.KonnectGatewayControlPlane, opts v1.UpdateOptions) (*konnectv1alpha1.KonnectGatewayControlPlane, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*konnectv1alpha1.KonnectGatewayControlPlane, error)
	List(ctx context.Context, opts v1.ListOptions) (*konnectv1alpha1.KonnectGatewayControlPlaneList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *konnectv1alpha1.KonnectGatewayControlPlane, err error)
	KonnectGatewayControlPlaneExpansion
}

// konnectGatewayControlPlanes implements KonnectGatewayControlPlaneInterface
type konnectGatewayControlPlanes struct {
	*gentype.ClientWithList[*konnectv1alpha1.KonnectGatewayControlPlane, *konnectv1alpha1.KonnectGatewayControlPlaneList]
}

// newKonnectGatewayControlPlanes returns a KonnectGatewayControlPlanes
func newKonnectGatewayControlPlanes(c *KonnectV1alpha1Client, namespace string) *konnectGatewayControlPlanes {
	return &konnectGatewayControlPlanes{
		gentype.NewClientWithList[*konnectv1alpha1.KonnectGatewayControlPlane, *konnectv1alpha1.KonnectGatewayControlPlaneList](
			"konnectgatewaycontrolplanes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *konnectv1alpha1.KonnectGatewayControlPlane {
				return &konnectv1alpha1.KonnectGatewayControlPlane{}
			},
			func() *konnectv1alpha1.KonnectGatewayControlPlaneList {
				return &konnectv1alpha1.KonnectGatewayControlPlaneList{}
			},
		),
	}
}
