area/crds:
  - changed-files:
    - any-glob-to-any-file:
      - 'config/crd/gateway-operator/**'
      - 'config/crd/kong-operator/**'
      - 'config/crd/ingress-controller-incubator/**'

area/docs:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'
      - 'README.md'
      - '.github/**.md'

area/tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'test/**'

area/charts:
  - changed-files:
    - any-glob-to-any-file:
      - 'charts/**'

area/ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/*.yaml'
      - '.github/*.yml'
