# Customize GitHub secret scanning to automatically close alerts for secrets found in specific directories
# that are used for testing or examples, as these are not actual secrets and do not pose a security risk.
# Read more:
# https://docs.github.com/en/code-security/how-tos/secure-your-secrets/customize-leak-detection/excluding-folders-and-files-from-secret-scanning
paths-ignore:
  - "charts/kong-operator/ci/__snapshots__/**"
  - "ingress-controller/examples/**"
  - "config/samples/**"
  - "ingress-controller/internal/dataplane/testdata/golden/**"
