# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.36.1
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.36.1
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.36.1
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.36.1
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.36.1
# renovate: datasource=docker packageName=kindest/node depName=kindest/node@only-patch
- v1.36.1
