/*
Copyright 2022 Kong Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/kong/gateway-operator/api/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGatewayConfigurations implements GatewayConfigurationInterface
type FakeGatewayConfigurations struct {
	Fake *FakeApisV1beta1
	ns   string
}

var gatewayconfigurationsResource = v1beta1.SchemeGroupVersion.WithResource("gatewayconfigurations")

var gatewayconfigurationsKind = v1beta1.SchemeGroupVersion.WithKind("GatewayConfiguration")

// Get takes name of the gatewayConfiguration, and returns the corresponding gatewayConfiguration object, and an error if there is any.
func (c *FakeGatewayConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.GatewayConfiguration, err error) {
	emptyResult := &v1beta1.GatewayConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(gatewayconfigurationsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.GatewayConfiguration), err
}

// List takes label and field selectors, and returns the list of GatewayConfigurations that match those selectors.
func (c *FakeGatewayConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.GatewayConfigurationList, err error) {
	emptyResult := &v1beta1.GatewayConfigurationList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(gatewayconfigurationsResource, gatewayconfigurationsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.GatewayConfigurationList{ListMeta: obj.(*v1beta1.GatewayConfigurationList).ListMeta}
	for _, item := range obj.(*v1beta1.GatewayConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gatewayConfigurations.
func (c *FakeGatewayConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(gatewayconfigurationsResource, c.ns, opts))

}

// Create takes the representation of a gatewayConfiguration and creates it.  Returns the server's representation of the gatewayConfiguration, and an error, if there is any.
func (c *FakeGatewayConfigurations) Create(ctx context.Context, gatewayConfiguration *v1beta1.GatewayConfiguration, opts v1.CreateOptions) (result *v1beta1.GatewayConfiguration, err error) {
	emptyResult := &v1beta1.GatewayConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(gatewayconfigurationsResource, c.ns, gatewayConfiguration, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.GatewayConfiguration), err
}

// Update takes the representation of a gatewayConfiguration and updates it. Returns the server's representation of the gatewayConfiguration, and an error, if there is any.
func (c *FakeGatewayConfigurations) Update(ctx context.Context, gatewayConfiguration *v1beta1.GatewayConfiguration, opts v1.UpdateOptions) (result *v1beta1.GatewayConfiguration, err error) {
	emptyResult := &v1beta1.GatewayConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(gatewayconfigurationsResource, c.ns, gatewayConfiguration, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.GatewayConfiguration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGatewayConfigurations) UpdateStatus(ctx context.Context, gatewayConfiguration *v1beta1.GatewayConfiguration, opts v1.UpdateOptions) (result *v1beta1.GatewayConfiguration, err error) {
	emptyResult := &v1beta1.GatewayConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(gatewayconfigurationsResource, "status", c.ns, gatewayConfiguration, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.GatewayConfiguration), err
}

// Delete takes name of the gatewayConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeGatewayConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gatewayconfigurationsResource, c.ns, name, opts), &v1beta1.GatewayConfiguration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGatewayConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(gatewayconfigurationsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.GatewayConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched gatewayConfiguration.
func (c *FakeGatewayConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.GatewayConfiguration, err error) {
	emptyResult := &v1beta1.GatewayConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(gatewayconfigurationsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.GatewayConfiguration), err
}
