// This file is generated by /hack/generators/kic/role-generator. DO NOT EDIT.

package resources

import (
	"fmt"
)

// -----------------------------------------------------------------------------
// ClusterRole generator helper
// -----------------------------------------------------------------------------

var ErrControlPlaneVersionNotSupported = fmt.Errorf("version not supported")
