# renovate: datasource=github-releases depName=golangci/golangci-lint
version: v2.6.2
name: golangci-kube-api-linter
destination: ./bin
plugins:
- module: 'sigs.k8s.io/kube-api-linter'
  version: b446a4e42d16c9fd46a297e780a97fa22252c4c2
