version: "2"
run:
  timeout: 8m
  build-tags:
    - integration_tests
    - e2e_tests
    - conformance_tests
    - istio_tests
    - envtest
    - performance_tests
linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - forbidigo
    - gocritic
    - gomodguard
    - gosec
    - importas
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - predeclared
    - revive
    # Uncomment or remove - TODO: https://github.com/Kong/kong-operator/issues/1847
    # - testifylint
    - unconvert
    - unparam
    - usetesting
    - wastedassign
  # Remove - TODO: https://github.com/Kong/kong-operator/issues/1847
  disable:
    - unused
  settings:
    staticcheck:
      checks:
        - all
        # Incorrect or missing package comment.
        # https://staticcheck.dev/docs/checks/#ST1000
        - -ST1000
        # Incorrectly formatted error string.
        # https://staticcheck.dev/docs/checks/#ST1005
        - -ST1005
        # Underscore in the name of a package.
        # https://staticcheck.dev/docs/checks/#ST1003
        - -ST1003
    exhaustive:
      default-signifies-exhaustive: true
    forbidigo:
      forbid:
        # Uncomment or remove - TODO: https://github.com/Kong/kong-operator/issues/1847
        # - pattern: ^.*Dataplane[^G].*$
        #   msg: Please use camel case 'DataPlane' instead of 'Dataplane'
        - pattern: ^.*Controlplane.*$
          msg: Please use camel case 'ControlPlane' instead of 'Controlplane'
        - pattern: ^.*operatorv1beta1.ControlPlane.*$
          msg: Please use v2beta1 ControlPlane (through github.com/kong/kong-operator/internal/types)
        # NOTE: When all references use the types package, this rule can use .* instead of listing types.
        - pattern: ^.*operatorv2alpha1.ControlPlane.*$
          msg: Please use the types package to refer to the type (through github.com/kong/kong-operator/internal/types)
    gomodguard:
      blocked:
        modules:
          - golang.org/x/exp:
              recommendations:
                - maps
                - slices
                - github.com/samber/lo
          - github.com/pkg/errors:
              recommendations:
                - fmt
                - errors
          - github.com/sirupsen/logrus:
              recommendations:
                - sigs.k8s.io/controller-runtime/pkg/log
                - go.uber.org/zap/zapcore
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    importas:
      alias:
        - pkg: k8s.io/api/([a-z])/(v[\w\d]+)
          alias: ${1}${2}
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/watch
          alias: apiwatch
        - pkg: sigs.k8s.io/gateway-api/apis/(v[\w\d]+)
          alias: gateway${1}
        - pkg: sigs.k8s.io/controller-runtime/pkg/log
          alias: ctrllog
        - pkg: github.com/Kong/sdk-konnect-go/models/components
          alias: sdkkonnectcomp
        - pkg: github.com/Kong/sdk-konnect-go/models/operations
          alias: sdkkonnectops
        - pkg: github.com/Kong/sdk-konnect-go/models/sdkerrors
          alias: sdkkonnecterrs
        - pkg: github.com/kong/kong-operator/controller/konnect/ops/sdk
          alias: sdkops
        - pkg: github.com/kong/kong-operator/controller/konnect/ops/sdk/mocks
          alias: sdkmocks
        - pkg: github.com/kong/kong-operator/internal/types
          alias: gwtypes
        - pkg: github.com/kong/kong-operator/pkg/utils/kubernetes
          alias: k8sutils
        - pkg: github.com/kong/kong-operator/pkg/utils/kubernetes/resources
          alias: k8sresources
      no-unaliased: true
    revive:
      rules:
        - name: errorf
          severity: warning
          disabled: false
        - name: error-strings
          severity: warning
          disabled: false
        - name: error-naming
          severity: warning
          disabled: false
        - name: duplicated-imports
          severity: warning
          disabled: false
        - name: empty-block
          severity: warning
          disabled: false
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
          severity: warning
          disabled: false
        - name: context-as-argument
          disabled: true
    testifylint:
      enable-all: true
      disable:
        - error-is-as
    usetesting:
      os-temp-dir: true
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        # pkg/|test/ has been added, see TODO: https://github.com/Kong/kong-operator/issues/1847
        path: internal/|pkg/|test/
        text: 'exported: exported'
      - linters:
          - revive
        path: test/integration
        text: 'exported: exported'
      - linters:
          - revive
        path: test/e2e
        text: 'exported: exported'
      - linters:
          - revive
        path: controller/konnect/ops/.*_mock\.go
        text: 'exported: exported'
      - linters:
          - forbidigo
        text: use of `.*(Create|Delete)Dataplane.+` forbidden because "Please use camel case
      - linters:
          - gosec
        path: .*_test\.go
        text: Use of weak random number generator
      # Remove/adjust whole section - TODO: https://github.com/Kong/kong-operator/issues/1847
      - linters:
          - gosec
        path: .*_test\.go
        text: Potential hardcoded credentials
      - linters:
          - gosec
        path: .*_test\.go
        text: Potential HTTP request made with variable url
      - linters:
          - gosec
        text: integer overflow conversion
      - linters:
          - forbidigo
        path: internal/types/operatortypes.go
        text: use of `operatorv2beta1.(ControlPlane\w*)` forbidden
      - linters:
          - forbidigo
        path: api/test
        text: use of `operatorv1beta1.(ControlPlane\w*)` forbidden
    paths:
      - pkg/clientset
      - config/
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  fix: true
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kong/kong-operator)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - pkg/clientset
      - config/
      - third_party$
      - builtin$
      - examples$
