[settings.github]
github_attestations = false

[tools]
node = "latest"

################################################################################
# Tools

[tools.markdownlint-cli2]
# renovate: datasource=github-tags depName=DavidAnson/markdownlint-cli2
version = "0.23.1"

[tools."github:kubernetes-sigs/controller-tools"]
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-tools
version = "0.21.0"

[tools."github:golangci/golangci-lint"]
# renovate: datasource=github-releases depName=golangci/golangci-lint
version = "2.12.2"

[tools."github:kubernetes-sigs/controller-runtime"]
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-runtime
version = "0.24.1"
[tools."github:kubernetes-sigs/controller-runtime".platforms]
darwin-arm64 = { asset_pattern = "setup-envtest-darwin-arm64" }
linux-arm64 = { asset_pattern = "setup-envtest-linux-arm64" }
linux-amd64 = { asset_pattern = "setup-envtest-linux-amd64" }

# NOTE: The reason for tool version being set here and not in .tools-versions.toml
# is that mise requires the version to be specified when using version_prefix
# and we need to set the latter for kustomize because its tags on GitHub are prefixed
# with "kustomize/".

# NOTE renovate's mise manager doesn't want to work with this for some reason
# so we add renovate comments manually here.
# Ref: https://docs.renovatebot.com/modules/manager/mise/

[tools."github:kubernetes-sigs/kustomize"]
# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
version = "v5.8.1"
version_prefix = "kustomize/"

[tools."kind"]
# renovate: datasource=github-releases depName=kubernetes-sigs/kind
version = "v0.32.0"
bin = "kind"
[tools."kind".platforms]
linux-x64 = { asset_pattern = "kind-linux-amd64" }
linux-arm64 = { asset_pattern = "kind-linux-arm64" }
macos-arm64 = { asset_pattern = "kind-darwin-arm64" }

[tools."github:Kong/kubernetes-testing-framework"]
# renovate: datasource=github-releases depName=Kong/kubernetes-testing-framework
version = "v0.51.0"
bin = "ktf"

[tools."github:telepresenceio/telepresence"]
# renovate: datasource=github-releases depName=telepresenceio/telepresence
version = "2.30.0"
[tools."github:telepresenceio/telepresence".platforms]
linux-x64 = { asset_pattern = "telepresence-linux-amd64" }
linux-arm64 = { asset_pattern = "telepresence-linux-arm64" }
macos-arm64 = { asset_pattern = "telepresence-darwin-arm64" }

[tools."aqua:helm/helm"]
# renovate: datasource=github-releases depName=helm/helm
version = "4.2.3"

[tools."go:sigs.k8s.io/kube-api-linter/cmd/golangci-lint-kube-api-linter"]
# renovate: datasource=git-refs packageName=https://github.com/kubernetes-sigs/kube-api-linter.git
version = "092fe0c72997c3e7d6d78405211ed913e37a44e5"

[tools."yq"]
# renovate: datasource=github-releases depName=mikefarah/yq
version = "v4.53.3"

[tools."aqua:kyverno/chainsaw"]
# renovate: datasource=git-refs packageName=https://github.com/kyverno/chainsaw.git
version = "v0.2.15"

################################################################################
# Tasks

[env]
DIR = "crd-from-oas"

[tasks.build-crd-from-oas]
description = "Build the {{env.DIR}} binary"
dir = "./{{env.DIR}}"
run = "go build -o ../bin/{{env.DIR}} main.go"

[tasks.clean]
description = "Clean generated files"
run = '''
rm -rf \
       ./api/konnect/v1alpha1/zz_generated_*_sdkops.go \
       ./api/konnect/v1alpha1/zz_generated_*_sdkops_test.go \
       ./api/konnect/v1alpha1/zz_generated_*_types.go \
       ./api/konnect/v1alpha1/zz_generated_*_types_test.go \
       ./api/konnect/v1alpha1/zz_generated_*_conditions.go \
       ./controller/konnect/zz_generated_reconciler_generic_rbac_* \
       ./modules/manager/zz_generated_* \
       ./internal/utils/index/zz_generated_konnect_*
'''

[tasks.generate-api]
description = "Generate Kubernetes Go API from OpenAPI spec"
dir = "./{{env.DIR}}"
run = "mise r generate-api"
depends = [ "clean" ]
depends_post = [ "generate-deepcopy" ]

[tasks.generate-deepcopy]
description = "Generate DeepCopy methods for the API types"
dir = "./{{env.DIR}}"
run = "controller-gen object:headerFile='../hack/generators/boilerplate.go.txt' paths=../api/..."

[tasks.test-crdsvalidation]
description = "Run CRD validation tests"
# Update test paths below if more API groups are added
run = '''
export KUBEBUILDER_ASSETS=$(setup-envtest use -p path)
go test -v -count 1 ${GOTESTFLAGS} ./test/crdsvalidation/konnect.konghq.com/...
'''

[tasks.all]
description = "Generate API, CRDs, and run all tests and linters"
run = [
       { task = "generate-api" },
       { task = "test-crdsvalidation" },
]
