dir: 'test/mocks/sdkmocks'
structname: Mock{{ .InterfaceName }}
pkgname: sdkmocks
template: testify
# NOTE: We write mocks to a non test file so that other packages can also use them.
filename: 'zz_generated.{{base .InterfaceFile }}'
force-file-write: true
packages:
  github.com/kong/kong-operator/controller/konnect/ops/sdk:
    config:
      include-interface-regex: .*SDK$
      # TODO: gradually add more types to this exclude list when they are
      # provided by SDK Konnect Go.
      exclude-interface-regex: ^ControlPlaneSDK$
