dir: '{{ .InterfaceDir }}/mocks'
structname: Mock{{ .InterfaceName }}
pkgname: mocks
template: testify
# NOTE: We write mocks to a non test file so that other packages can also use them.
filename: mocks.go
force-file-write: true
packages:
  github.com/kong/kong-operator/controller/konnect/ops/sdk:
    config:
      include-interface-regex: .*SDK$
