# renovate: datasource=github-tags depName=kubernetes/code-generator
code-generator: "0.35.1"
# renovate: datasource=github-releases depName=golangci/golangci-lint
golangci-lint: "2.10.1"
# renovate: datasource=github-releases depName=GoogleContainerTools/skaffold
skaffold: "2.17.2"
# renovate: datasource=github-releases depName=go-delve/delve
dlv: "1.26.0"
# renovate: datasource=github-releases depName=gotestyourself/gotestsum
gotestsum: "1.13.0"
# renovate: datasource=github-releases depName=elastic/crd-ref-docs
crd-ref-docs: "0.3.0"
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-runtime
setup-envtest: "0.23.1"
# renovate: datasource=github-releases depName=rhysd/actionlint
actionlint: "1.7.11"
# renovate: datasource=github-releases depName=koalaman/shellcheck
shellcheck: "0.11.0"
# NOTE: This does not work and requires further investigation.
# Perhaps it's possible to use a git url but https://go.googlesource.com/vuln/
# does not seem to provide one.
#
#  WARN: Custom registries are not allowed for this datasource and will be ignored (repository=local)
#        "datasource": "git-tags",
#        "registryUrls": ["https://go.googlesource.com/"],
#        "defaultRegistryUrls": null,
#        "additionalRegistryUrls": undefined
#  WARN: Attempting to use non-git url for git operations (repository=local)
#        "url": "vuln"
#
# Renovate UI errors:
# These problems occurred while renovating this repository.

# ⚠️ Custom registries are not allowed for this datasource and will be ignored
# ⚠️ Attempting to use non-git url for git operations
# ⚠️ Package lookup failures
#
# TODO: Make this work.
#
# todo: datasource=git-tags depName=vuln registryUrl=https://go.googlesource.com
govulncheck: "1.1.4"
# renovate: datasource=github-releases depName=jlandowner/helm-chartsnap
chartsnap: "0.6.0"
# renovate: datasource=github-releases depName=stackrox/kube-linter
kube-linter: "0.8.1"
# renovate: datasource=github-tags depName=DavidAnson/markdownlint-cli2
markdownlint-cli2: "0.21.0"
# renovate: datasource=github-releases depName=cert-manager/cert-manager
cert-manager: "1.19.4"
# renovate: datasource=github-releases depName=kyverno/chainsaw
chainsaw: "v0.2.15-beta.1"
