# renovate: datasource=github-tags depName=kubernetes/code-generator
code-generator: "0.35.0"
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-tools
controller-tools: "0.20.0"
# renovate: datasource=github-releases depName=golangci/golangci-lint
golangci-lint: "2.7.2"
# TODO: Renovate comment is missing. This needs to be added at some point.
modernize: "0.19.1"
# renovate: datasource=github-releases depName=GoogleContainerTools/skaffold
skaffold: "2.17.1"
# renovate: datasource=github-releases depName=go-delve/delve
dlv: "1.26.0"
# renovate: datasource=github-releases depName=gotestyourself/gotestsum
gotestsum: "1.13.0"
# renovate: datasource=github-releases depName=elastic/crd-ref-docs
crd-ref-docs: "0.2.0"
# renovate: datasource=github-releases depName=vektra/mockery
mockery: "3.6.1"
# renovate: datasource=github-releases depName=kubernetes-sigs/controller-runtime
setup-envtest: "0.22.4"
# renovate: datasource=github-releases depName=rhysd/actionlint
actionlint: "1.7.10"
# renovate: datasource=github-releases depName=koalaman/shellcheck
shellcheck: "0.11.0"
# NOTE: This does not work and requires further investigation.
# Perhaps it's possible to use a git url but https://go.googlesource.com/vuln/
# does not seem to provide one.
#
#  WARN: Custom registries are not allowed for this datasource and will be ignored (repository=local)
#        "datasource": "git-tags",
#        "registryUrls": ["https://go.googlesource.com/"],
#        "defaultRegistryUrls": null,
#        "additionalRegistryUrls": undefined
#  WARN: Attempting to use non-git url for git operations (repository=local)
#        "url": "vuln"
#
# TODO: Make this work.
# renovate: datasource=git-tags depName=vuln registryUrl=https://go.googlesource.com
govulncheck: "1.1.4"
# renovate: datasource=github-releases depName=jlandowner/helm-chartsnap
chartsnap: "0.6.0"
# renovate: datasource=github-releases depName=stackrox/kube-linter
kube-linter: "0.8.1"
# renovate: datasource=github-tags depName=DavidAnson/markdownlint-cli2
markdownlint-cli2: "0.20.0"
# renovate: datasource=github-releases depName=cert-manager/cert-manager
cert-manager: "1.19.2"
# renovate: datasource=github-releases depName=kyverno/chainsaw
chainsaw: "0.2.14"
