// Code generated by CRD generation pipeline. DO NOT EDIT.

package index

import (
	"sigs.k8s.io/controller-runtime/pkg/client"

	konnectv1alpha1 "github.com/kong/kong-operator/v2/api/konnect/v1alpha1"
)

const (
	// IndexFieldEventGatewayListenerPolicyOnEventGatewayListenerRef is the index field for EventGatewayListenerPolicy -> EventGatewayListener.
	IndexFieldEventGatewayListenerPolicyOnEventGatewayListenerRef = "eventGatewayListenerPolicyOnEventGatewayListenerRef"
)

// OptionsForEventGatewayListenerPolicy returns required Index options for EventGatewayListenerPolicy reconciler.
func OptionsForEventGatewayListenerPolicy() []Option {
	return []Option{
		{
			Object:         &konnectv1alpha1.EventGatewayListenerPolicy{},
			Field:          IndexFieldEventGatewayListenerPolicyOnEventGatewayListenerRef,
			ExtractValueFn: eventGatewayListenerPolicyOnEventGatewayListenerRef,
		},
	}
}

func eventGatewayListenerPolicyOnEventGatewayListenerRef(object client.Object) []string {
	ent, ok := object.(*konnectv1alpha1.EventGatewayListenerPolicy)
	if !ok {
		return nil
	}
	if ent.Spec.EventGatewayListenerRef.NamespacedRef == nil {
		return nil
	}

	return []string{ent.Spec.EventGatewayListenerRef.NamespacedRef.Name}
}
