// Code generated by CRD generation pipeline. DO NOT EDIT.

package index

import (
	"sigs.k8s.io/controller-runtime/pkg/client"

	konnectv1alpha1 "github.com/kong/kong-operator/v2/api/konnect/v1alpha1"
)

const (
	// IndexFieldAIGatewayConsumerCredentialOnAIGatewayConsumerRef is the index field for AIGatewayConsumerCredential -> AIGatewayConsumer.
	IndexFieldAIGatewayConsumerCredentialOnAIGatewayConsumerRef = "aiGatewayConsumerCredentialOnAIGatewayConsumerRef"
)

// OptionsForAIGatewayConsumerCredential returns required Index options for AIGatewayConsumerCredential reconciler.
func OptionsForAIGatewayConsumerCredential() []Option {
	return []Option{
		{
			Object:         &konnectv1alpha1.AIGatewayConsumerCredential{},
			Field:          IndexFieldAIGatewayConsumerCredentialOnAIGatewayConsumerRef,
			ExtractValueFn: aiGatewayConsumerCredentialOnAIGatewayConsumerRef,
		},
	}
}

func aiGatewayConsumerCredentialOnAIGatewayConsumerRef(object client.Object) []string {
	ent, ok := object.(*konnectv1alpha1.AIGatewayConsumerCredential)
	if !ok {
		return nil
	}
	if ent.Spec.AIGatewayConsumerRef.NamespacedRef == nil {
		return nil
	}

	refNamespace := ent.GetNamespace()
	if ent.Spec.AIGatewayConsumerRef.NamespacedRef.Namespace != nil && *ent.Spec.AIGatewayConsumerRef.NamespacedRef.Namespace != "" {
		refNamespace = *ent.Spec.AIGatewayConsumerRef.NamespacedRef.Namespace
	}

	return []string{refNamespace + "/" + ent.Spec.AIGatewayConsumerRef.NamespacedRef.Name}
}
