// Code generated by CRD generation pipeline. DO NOT EDIT.

package index

import (
	"sigs.k8s.io/controller-runtime/pkg/client"

	aiconfigurationv1alpha1 "github.com/kong/kong-operator/v2/api/aiconfiguration/v1alpha1"
)

const (
	// IndexFieldAIGatewayConsumerGroupOnKonnectAIGatewayRef is the index field for AIGatewayConsumerGroup -> KonnectAIGateway.
	IndexFieldAIGatewayConsumerGroupOnKonnectAIGatewayRef = "aiGatewayConsumerGroupOnKonnectAIGatewayRef"
	// IndexFieldAIGatewayConsumerGroupOnOnPremAIGatewayRef is the index field for AIGatewayConsumerGroup -> OnPremAIGateway.
	IndexFieldAIGatewayConsumerGroupOnOnPremAIGatewayRef = "aiGatewayConsumerGroupOnOnPremAIGatewayRef"
	// IndexFieldAIGatewayConsumerGroupOnAIGatewayPolicyRef is the index field for AIGatewayConsumerGroup -> AIGatewayPolicy.
	IndexFieldAIGatewayConsumerGroupOnAIGatewayPolicyRef = "aiGatewayConsumerGroupOnAIGatewayPolicyRef"
)

// OptionsForAIGatewayConsumerGroup returns required Index options for AIGatewayConsumerGroup reconciler.
func OptionsForAIGatewayConsumerGroup() []Option {
	return []Option{
		{
			Object:         &aiconfigurationv1alpha1.AIGatewayConsumerGroup{},
			Field:          IndexFieldAIGatewayConsumerGroupOnKonnectAIGatewayRef,
			ExtractValueFn: aiGatewayConsumerGroupOnKonnectAIGatewayRef,
		},
		{
			Object:         &aiconfigurationv1alpha1.AIGatewayConsumerGroup{},
			Field:          IndexFieldAIGatewayConsumerGroupOnOnPremAIGatewayRef,
			ExtractValueFn: aiGatewayConsumerGroupOnOnPremAIGatewayRef,
		},
		{
			Object:         &aiconfigurationv1alpha1.AIGatewayConsumerGroup{},
			Field:          IndexFieldAIGatewayConsumerGroupOnAIGatewayPolicyRef,
			ExtractValueFn: aiGatewayConsumerGroupOnAIGatewayPolicyRef,
		},
	}
}

func aiGatewayConsumerGroupOnKonnectAIGatewayRef(object client.Object) []string {
	ent, ok := object.(*aiconfigurationv1alpha1.AIGatewayConsumerGroup)
	if !ok {
		return nil
	}
	if ent.Spec.AIGatewayRef.NamespacedRef == nil {
		return nil
	}
	// Only entities targeting a KonnectAIGateway are visible to the Konnect
	// reconciler: on-prem-targeted ones are indexed separately.
	if !ent.Spec.AIGatewayRef.TargetsKonnectAIGateway() {
		return nil
	}

	refNamespace := ent.GetNamespace()
	if ent.Spec.AIGatewayRef.NamespacedRef.Namespace != nil && *ent.Spec.AIGatewayRef.NamespacedRef.Namespace != "" {
		refNamespace = *ent.Spec.AIGatewayRef.NamespacedRef.Namespace
	}

	return []string{refNamespace + "/" + ent.Spec.AIGatewayRef.NamespacedRef.Name}
}
func aiGatewayConsumerGroupOnOnPremAIGatewayRef(object client.Object) []string {
	ent, ok := object.(*aiconfigurationv1alpha1.AIGatewayConsumerGroup)
	if !ok {
		return nil
	}
	if ent.Spec.AIGatewayRef.NamespacedRef == nil {
		return nil
	}
	// Only entities targeting an OnPremAIGateway are visible to the on-prem
	// reconciler: Konnect-targeted ones stay in the KonnectAIGateway index.
	if !ent.Spec.AIGatewayRef.TargetsOnPremAIGateway() {
		return nil
	}

	refNamespace := ent.GetNamespace()
	if ent.Spec.AIGatewayRef.NamespacedRef.Namespace != nil && *ent.Spec.AIGatewayRef.NamespacedRef.Namespace != "" {
		refNamespace = *ent.Spec.AIGatewayRef.NamespacedRef.Namespace
	}

	return []string{refNamespace + "/" + ent.Spec.AIGatewayRef.NamespacedRef.Name}
}

func aiGatewayConsumerGroupOnAIGatewayPolicyRef(object client.Object) []string {
	ent, ok := object.(*aiconfigurationv1alpha1.AIGatewayConsumerGroup)
	if !ok {
		return nil
	}
	var out []string
	for _, ref := range ent.Spec.APISpec.Policies {
		if ref.Kind != "" && ref.Kind != "AIGatewayPolicy" {
			continue
		}
		ns := ref.Namespace
		if ns == "" {
			ns = ent.GetNamespace()
		}
		out = append(out, ns+"/"+ref.Name)
	}
	return out
}
