// Code generated by CRD generation pipeline. DO NOT EDIT.

package index

import (
	"sigs.k8s.io/controller-runtime/pkg/client"

	konnectv1alpha1 "github.com/kong/kong-operator/v2/api/konnect/v1alpha1"
)

const (
	// IndexFieldAIGatewayMCPServerOnKonnectAIGatewayRef is the index field for AIGatewayMCPServer -> KonnectAIGateway.
	IndexFieldAIGatewayMCPServerOnKonnectAIGatewayRef = "aiGatewayMCPServerOnKonnectAIGatewayRef"
)

// OptionsForAIGatewayMCPServer returns required Index options for AIGatewayMCPServer reconciler.
func OptionsForAIGatewayMCPServer() []Option {
	return []Option{
		{
			Object:         &konnectv1alpha1.AIGatewayMCPServer{},
			Field:          IndexFieldAIGatewayMCPServerOnKonnectAIGatewayRef,
			ExtractValueFn: aiGatewayMCPServerOnKonnectAIGatewayRef,
		},
	}
}

func aiGatewayMCPServerOnKonnectAIGatewayRef(object client.Object) []string {
	ent, ok := object.(*konnectv1alpha1.AIGatewayMCPServer)
	if !ok {
		return nil
	}
	if ent.Spec.AIGatewayRef.NamespacedRef == nil {
		return nil
	}

	refNamespace := ent.GetNamespace()
	if ent.Spec.AIGatewayRef.NamespacedRef.Namespace != nil && *ent.Spec.AIGatewayRef.NamespacedRef.Namespace != "" {
		refNamespace = *ent.Spec.AIGatewayRef.NamespacedRef.Namespace
	}

	return []string{refNamespace + "/" + ent.Spec.AIGatewayRef.NamespacedRef.Name}
}
