// Code generated by CRD generation pipeline. DO NOT EDIT.

package index

import (
	"sigs.k8s.io/controller-runtime/pkg/client"

	configurationv1alpha1 "github.com/kong/kong-operator/v2/api/configuration/v1alpha1"
)

const (
	// IndexFieldEventGatewayStaticKeyOnKonnectEventGatewayRef is the index field for EventGatewayStaticKey -> KonnectEventGateway.
	IndexFieldEventGatewayStaticKeyOnKonnectEventGatewayRef = "eventGatewayStaticKeyOnKonnectEventGatewayRef"
)

// OptionsForEventGatewayStaticKey returns required Index options for EventGatewayStaticKey reconciler.
func OptionsForEventGatewayStaticKey() []Option {
	return []Option{
		{
			Object:         &configurationv1alpha1.EventGatewayStaticKey{},
			Field:          IndexFieldEventGatewayStaticKeyOnKonnectEventGatewayRef,
			ExtractValueFn: eventGatewayStaticKeyOnKonnectEventGatewayRef,
		},
	}
}

func eventGatewayStaticKeyOnKonnectEventGatewayRef(object client.Object) []string {
	ent, ok := object.(*configurationv1alpha1.EventGatewayStaticKey)
	if !ok {
		return nil
	}
	if ent.Spec.GatewayRef.NamespacedRef == nil {
		return nil
	}

	refNamespace := ent.GetNamespace()
	if ent.Spec.GatewayRef.NamespacedRef.Namespace != nil && *ent.Spec.GatewayRef.NamespacedRef.Namespace != "" {
		refNamespace = *ent.Spec.GatewayRef.NamespacedRef.Namespace
	}

	return []string{refNamespace + "/" + ent.Spec.GatewayRef.NamespacedRef.Name}
}
