// Code generated by CRD generation pipeline. DO NOT EDIT.

package index

import (
	"sigs.k8s.io/controller-runtime/pkg/client"

	configurationv1alpha1 "github.com/kong/kong-operator/v2/api/configuration/v1alpha1"
)

const (
	// IndexFieldEventGatewayVirtualClusterPolicyOnEventGatewayVirtualClusterRef is the index field for EventGatewayVirtualClusterPolicy -> EventGatewayVirtualCluster.
	IndexFieldEventGatewayVirtualClusterPolicyOnEventGatewayVirtualClusterRef = "eventGatewayVirtualClusterPolicyOnEventGatewayVirtualClusterRef"
)

// OptionsForEventGatewayVirtualClusterPolicy returns required Index options for EventGatewayVirtualClusterPolicy reconciler.
func OptionsForEventGatewayVirtualClusterPolicy() []Option {
	return []Option{
		{
			Object:         &configurationv1alpha1.EventGatewayVirtualClusterPolicy{},
			Field:          IndexFieldEventGatewayVirtualClusterPolicyOnEventGatewayVirtualClusterRef,
			ExtractValueFn: eventGatewayVirtualClusterPolicyOnEventGatewayVirtualClusterRef,
		},
	}
}

func eventGatewayVirtualClusterPolicyOnEventGatewayVirtualClusterRef(object client.Object) []string {
	ent, ok := object.(*configurationv1alpha1.EventGatewayVirtualClusterPolicy)
	if !ok {
		return nil
	}
	if ent.Spec.EventGatewayVirtualClusterRef.NamespacedRef == nil {
		return nil
	}

	refNamespace := ent.GetNamespace()
	if ent.Spec.EventGatewayVirtualClusterRef.NamespacedRef.Namespace != nil && *ent.Spec.EventGatewayVirtualClusterRef.NamespacedRef.Namespace != "" {
		refNamespace = *ent.Spec.EventGatewayVirtualClusterRef.NamespacedRef.Namespace
	}

	return []string{refNamespace + "/" + ent.Spec.EventGatewayVirtualClusterRef.NamespacedRef.Name}
}
