apiGroupVersions:
  konnect.konghq.com/v1alpha1:
    # Don't generate GroupVersionInfo for this API group, as it already has it defined.
    # We might do this in the future to replace the manually defined one.
    generateGroupVersionInfo: false
    commonTypes:
      objectRef:
        import:
          path: github.com/kong/kong-operator/v2/api/common/v1alpha1
          alias: commonv1alpha1
    types:
      - path: /v1/event-gateways
        name: KonnectEventControlPlane
        ops:
          create:
            path: github.com/Kong/sdk-konnect-go/models/components.CreateGatewayRequest
          update:
            path: github.com/Kong/sdk-konnect-go/models/components.UpdateGatewayRequest
        reconciler:
          isRoot: true
      - path: /v1/event-gateways/{gatewayId}/data-plane-certificates
        name: KonnectEventDataPlaneCertificate
        optionalSecretReference: true
        ops:
          create:
            path: github.com/Kong/sdk-konnect-go/models/components.CreateEventGatewayDataPlaneCertificateRequest
          update:
            path: github.com/Kong/sdk-konnect-go/models/components.UpdateEventGatewayDataPlaneCertificateRequest
        reconciler:
          isRoot: false
          parentEntityType: KonnectEventControlPlane

  # TODO: temporary
  x-konnect.konghq.com/v1alpha1:
    generateGroupVersionInfo: true
    commonTypes:
      objectRef:
        import:
          path: github.com/kong/kong-operator/v2/api/common/v1alpha1
          alias: commonv1alpha1
    types:
      - path: /v3/portals
        cel:
          name:
            _validations:
              - "+kubebuilder:validation:XValidation:rule=\"self == oldSelf\",message=\"name is immutable\""
        ops:
          create:
            path: github.com/Kong/sdk-konnect-go/models/components.CreatePortal
          update:
            path: github.com/Kong/sdk-konnect-go/models/components.UpdatePortal
        reconciler:
          isRoot: true
      - path: /v3/portals/{portalId}/teams
      - path: /v2/dcr-providers
        ops:
          create:
            path: github.com/Kong/sdk-konnect-go/models/components.CreateDcrProviderRequest
          update:
            path: github.com/Kong/sdk-konnect-go/models/components.UpdateDcrProviderRequest
        reconciler:
          isRoot: true
      # TODO: uncomment
      # - path: /v3/portals/{portalId}/custom-domain
      # - path: /v3/identity-providers
      # - path: /v3/portals/{portalId}/teams/{teamId}/developers
