// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kong/kong-operator/v2/api/common/v1alpha1"
	konnectv1alpha2 "github.com/kong/kong-operator/v2/api/konnect/v1alpha2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// GetKonnectStatus returns the Konnect status contained in the EventGatewayVirtualClusterPolicy status.
func (obj *EventGatewayVirtualClusterPolicy) GetKonnectStatus() *konnectv1alpha2.KonnectEntityStatus {
	return &obj.Status.KonnectEntityStatus
}

// SetKonnectID sets the Konnect ID in the EventGatewayVirtualClusterPolicy status.
func (obj *EventGatewayVirtualClusterPolicy) SetKonnectID(id string) {
	obj.Status.ID = id
}

// GetKonnectID returns the Konnect ID in the EventGatewayVirtualClusterPolicy status.
func (obj *EventGatewayVirtualClusterPolicy) GetKonnectID() string {
	return obj.Status.ID
}

// GetTypeName returns the EventGatewayVirtualClusterPolicy Kind name.
func (obj EventGatewayVirtualClusterPolicy) GetTypeName() string {
	return "EventGatewayVirtualClusterPolicy"
}

// GetItems returns the list of EventGatewayVirtualClusterPolicy items.
func (obj EventGatewayVirtualClusterPolicyList) GetItems() []EventGatewayVirtualClusterPolicy {
	return obj.Items
}

// HasParent returns true if the EventGatewayVirtualClusterPolicy has a parent entity.
func (obj EventGatewayVirtualClusterPolicy) HasParent() bool {
	return true
}

// GetConditions returns the Status Conditions.
func (obj *EventGatewayVirtualClusterPolicy) GetConditions() []metav1.Condition {
	return obj.Status.Conditions
}

// SetConditions sets the Status Conditions.
func (obj *EventGatewayVirtualClusterPolicy) SetConditions(conditions []metav1.Condition) {
	obj.Status.Conditions = conditions
}

// GetGatewayID returns the Konnect ID of the parent Gateway.
func (obj *EventGatewayVirtualClusterPolicy) GetGatewayID() string {
	if obj.Status.GatewayID == nil {
		return ""
	}
	return obj.Status.GatewayID.ID
}

// SetGatewayID sets the Konnect ID of the parent Gateway.
func (obj *EventGatewayVirtualClusterPolicy) SetGatewayID(id string) {
	if obj.Status.GatewayID == nil {
		obj.Status.GatewayID = &KonnectEntityRef{}
	}
	obj.Status.GatewayID.ID = id
}

// GetVirtualClusterID returns the Konnect ID of the parent VirtualCluster.
func (obj *EventGatewayVirtualClusterPolicy) GetVirtualClusterID() string {
	if obj.Status.VirtualClusterID == nil {
		return ""
	}
	return obj.Status.VirtualClusterID.ID
}

// SetVirtualClusterID sets the Konnect ID of the parent VirtualCluster.
func (obj *EventGatewayVirtualClusterPolicy) SetVirtualClusterID(id string) {
	if obj.Status.VirtualClusterID == nil {
		obj.Status.VirtualClusterID = &KonnectEntityRef{}
	}
	obj.Status.VirtualClusterID.ID = id
}

// GetEventGatewayVirtualClusterRef returns the reference to the parent EventGatewayVirtualCluster.
func (obj *EventGatewayVirtualClusterPolicy) GetEventGatewayVirtualClusterRef() commonv1alpha1.ObjectRef {
	return obj.Spec.EventGatewayVirtualClusterRef
}

// GetParentRef returns the reference to the parent entity.
func (obj *EventGatewayVirtualClusterPolicy) GetParentRef() commonv1alpha1.ObjectRef {
	return obj.GetEventGatewayVirtualClusterRef()
}

// SetParentRef sets the reference to the parent entity.
func (obj *EventGatewayVirtualClusterPolicy) SetParentRef(ref commonv1alpha1.ObjectRef) {
	obj.Spec.EventGatewayVirtualClusterRef = ref
}

// SetParentID sets the Konnect ID of the immediate parent entity.
func (obj *EventGatewayVirtualClusterPolicy) SetParentID(id string) {
	obj.SetVirtualClusterID(id)
}

// GetParentGVK returns the GroupVersionKind of the parent entity.
func (obj *EventGatewayVirtualClusterPolicy) GetParentGVK() schema.GroupVersionKind {
	return schema.GroupVersionKind{
		Group:   "configuration.konghq.com",
		Version: GroupVersion.Version,
		Kind:    "EventGatewayVirtualCluster",
	}
}

// GetStatusConditionTypeParentRefValid returns the status condition type
// indicating whether the parent reference is valid.
func (obj *EventGatewayVirtualClusterPolicy) GetStatusConditionTypeParentRefValid() string {
	return EventGatewayVirtualClusterRefValidConditionType
}

// GetStatusConditionReasonParentRefValid returns the status condition reason
// indicating that the parent reference is valid.
func (obj *EventGatewayVirtualClusterPolicy) GetStatusConditionReasonParentRefValid() string {
	return EventGatewayVirtualClusterRefReasonValid
}

// GetStatusConditionReasonParentRefInvalid returns the status condition reason
// indicating that the parent reference is invalid.
func (obj *EventGatewayVirtualClusterPolicy) GetStatusConditionReasonParentRefInvalid() string {
	return EventGatewayVirtualClusterRefReasonInvalid
}

// GetStatusConditionReasonParentRefNotProgrammed returns the status condition
// reason indicating that the referenced parent exists but is not yet
// programmed in Konnect.
func (obj *EventGatewayVirtualClusterPolicy) GetStatusConditionReasonParentRefNotProgrammed() string {
	return EventGatewayVirtualClusterRefReasonNotProgrammed
}

// GetAncestorIDs returns the Konnect IDs of the ancestor entities keyed by their Kind.
func (obj *EventGatewayVirtualClusterPolicy) GetAncestorIDs() map[string]string {
	m := make(map[string]string, 1)
	if obj.Status.GatewayID != nil {
		m["KonnectEventGateway"] = obj.Status.GatewayID.ID
	} else {
		m["KonnectEventGateway"] = ""
	}
	return m
}

// SetAncestorID sets the Konnect ID for the ancestor entity identified by kind.
func (obj *EventGatewayVirtualClusterPolicy) SetAncestorID(kind, id string) {
	switch kind {
	case "KonnectEventGateway":
		obj.SetGatewayID(id)
	}
}
