// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"encoding/json"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	sdkkonnectcomp "github.com/Kong/sdk-konnect-go/models/components"
	sdkkonnectoper "github.com/Kong/sdk-konnect-go/models/operations"
)

func (s *EventGatewaySchemaRegistryAPISpec) marshalSDKOpsPayload() (map[string]any, error) {
	data, err := json.Marshal(s)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal EventGatewaySchemaRegistryAPISpec: %w", err)
	}

	var rawPayload any
	if err := json.Unmarshal(data, &rawPayload); err != nil {
		return nil, fmt.Errorf("failed to decode EventGatewaySchemaRegistryAPISpec: %w", err)
	}
	rawPayload = flattenSensitiveData(rawPayload)
	// Convert camelCase CRD wire-format keys and discriminator values to
	// snake_case for the Konnect SDK request types.
	renamed := renameKeysToSDK(rawPayload)
	payload, ok := renamed.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("failed to convert EventGatewaySchemaRegistryAPISpec SDK payload to map")
	}
	return payload, nil
}

func (s *EventGatewaySchemaRegistryAPISpec) selectedSDKOpsPayload(payload map[string]any) ([]byte, string, error) {
	if s == nil || s.EventGatewaySchemaRegistryConfig == nil {
		return nil, "", fmt.Errorf("EventGatewaySchemaRegistry config is required")
	}

	var selected any
	var variant string
	switch s.EventGatewaySchemaRegistryConfig.Type {
	case EventGatewaySchemaRegistryConfigTypeSchemaRegistryConfluent:
		selected = payload["confluent"]
		variant = "SchemaRegistryConfluent"
	default:
		return nil, "", fmt.Errorf("unsupported EventGatewaySchemaRegistry config type %q", s.EventGatewaySchemaRegistryConfig.Type)
	}

	if selected == nil {
		return nil, "", fmt.Errorf("EventGatewaySchemaRegistry config payload missing for type %q", s.EventGatewaySchemaRegistryConfig.Type)
	}
	selected = flattenSDKUnions(selected)
	if selectedMap, ok := selected.(map[string]any); ok {
		if typeValue, ok := payload["type"]; ok {
			if _, hasType := selectedMap["type"]; !hasType {
				withType := make(map[string]any)
				for key, value := range selectedMap {
					withType[key] = value
				}
				withType["type"] = typeValue
				selected = withType
			}
		}
	}

	data, err := json.Marshal(selected)
	if err != nil {
		return nil, "", fmt.Errorf("failed to marshal selected EventGatewaySchemaRegistry config: %w", err)
	}
	return data, variant, nil
}

// ToSchemaRegistryCreate converts the EventGatewaySchemaRegistryAPISpec to the SDK type
// sdkkonnectcomp.SchemaRegistryCreate using JSON marshal/unmarshal.
// Fields that exist in the CRD spec but not in the SDK type (e.g., Kubernetes
// object references) are naturally excluded because they have different JSON names.
func (s *EventGatewaySchemaRegistryAPISpec) ToSchemaRegistryCreate() (*sdkkonnectcomp.SchemaRegistryCreate, error) {
	payload, err := s.marshalSDKOpsPayload()
	if err != nil {
		return nil, err
	}
	data, variant, err := s.selectedSDKOpsPayload(payload)
	if err != nil {
		return nil, err
	}

	switch variant {
	case "SchemaRegistryConfluent":
		var member sdkkonnectcomp.SchemaRegistryConfluent
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into SchemaRegistryConfluent: %w", err)
		}
		target := sdkkonnectcomp.CreateSchemaRegistryCreateConfluent(member)
		return &target, nil
	default:
		return nil, fmt.Errorf("unsupported EventGatewaySchemaRegistry config variant %q", variant)
	}
}

// ToUpdateEventGatewaySchemaRegistryRequest converts the EventGatewaySchemaRegistryAPISpec to the SDK type
// sdkkonnectoper.UpdateEventGatewaySchemaRegistryRequest using JSON marshal/unmarshal.
// Fields that exist in the CRD spec but not in the SDK type (e.g., Kubernetes
// object references) are naturally excluded because they have different JSON names.
func (s *EventGatewaySchemaRegistryAPISpec) ToUpdateEventGatewaySchemaRegistryRequest() (*sdkkonnectoper.UpdateEventGatewaySchemaRegistryRequest, error) {
	payload, err := s.marshalSDKOpsPayload()
	if err != nil {
		return nil, err
	}
	data, variant, err := s.selectedSDKOpsPayload(payload)
	if err != nil {
		return nil, err
	}

	_ = variant
	var body sdkkonnectcomp.SchemaRegistryUpdate
	if err := json.Unmarshal(data, &body); err != nil {
		return nil, fmt.Errorf("failed to unmarshal into SchemaRegistryUpdate: %w", err)
	}
	return &sdkkonnectoper.UpdateEventGatewaySchemaRegistryRequest{
		SchemaRegistryUpdate: &body,
	}, nil
}

func (obj *EventGatewaySchemaRegistry) sdkOpsAPISpec(ctx context.Context, cl client.Client) (*EventGatewaySchemaRegistryAPISpec, error) {
	if obj == nil {
		return nil, fmt.Errorf("EventGatewaySchemaRegistry is nil")
	}

	apiSpec := obj.Spec.APISpec
	// Resolve spec.apiSpec.confluent.config.authentication.basic.password
	if apiSpec.EventGatewaySchemaRegistryConfig != nil {
		if apiSpec.EventGatewaySchemaRegistryConfig.SchemaRegistryConfluent != nil {
			if apiSpec.EventGatewaySchemaRegistryConfig.SchemaRegistryConfluent.Config.Authentication != nil {
				if apiSpec.EventGatewaySchemaRegistryConfig.SchemaRegistryConfluent.Config.Authentication.SchemaRegistryAuthenticationBasic != nil {
					{
						src := apiSpec.EventGatewaySchemaRegistryConfig.SchemaRegistryConfluent.Config.Authentication.SchemaRegistryAuthenticationBasic.Password
						if src.Type == SensitiveDataSourceTypeSecretRef {
							if src.SecretRef == nil {
								return nil, fmt.Errorf("secretRef is nil for spec.apiSpec.confluent.config.authentication.basic.password")
							}
							namespace := obj.GetNamespace()
							if src.SecretRef.Namespace != nil && *src.SecretRef.Namespace != "" {
								namespace = *src.SecretRef.Namespace
							}
							var secret corev1.Secret
							if err := cl.Get(ctx, client.ObjectKey{Namespace: namespace, Name: src.SecretRef.Name}, &secret); err != nil {
								return nil, fmt.Errorf("failed to fetch Secret %s/%s: %w", namespace, src.SecretRef.Name, err)
							}
							secretBytes, ok := secret.Data[src.SecretRef.Key]
							if !ok {
								return nil, fmt.Errorf("secret %s/%s is missing key %q", namespace, src.SecretRef.Name, src.SecretRef.Key)
							}
							resolved := string(secretBytes)
							apiSpec.EventGatewaySchemaRegistryConfig.SchemaRegistryConfluent.Config.Authentication.SchemaRegistryAuthenticationBasic.Password.Value = &resolved
						}
					}
				}
			}
		}
	}
	return &apiSpec, nil
}

// GetSensitiveDataSecretRefs returns all Secret references used to populate sensitive SDK payload fields.
func (obj *EventGatewaySchemaRegistry) GetSensitiveDataSecretRefs() []SensitiveDataSecretRef {
	if obj == nil {
		return nil
	}
	var refs []SensitiveDataSecretRef
	if obj.Spec.APISpec.EventGatewaySchemaRegistryConfig != nil {
		if obj.Spec.APISpec.EventGatewaySchemaRegistryConfig.SchemaRegistryConfluent != nil {
			if obj.Spec.APISpec.EventGatewaySchemaRegistryConfig.SchemaRegistryConfluent.Config.Authentication != nil {
				if obj.Spec.APISpec.EventGatewaySchemaRegistryConfig.SchemaRegistryConfluent.Config.Authentication.SchemaRegistryAuthenticationBasic != nil {
					if obj.Spec.APISpec.EventGatewaySchemaRegistryConfig.SchemaRegistryConfluent.Config.Authentication.SchemaRegistryAuthenticationBasic.Password.Type == SensitiveDataSourceTypeSecretRef && obj.Spec.APISpec.EventGatewaySchemaRegistryConfig.SchemaRegistryConfluent.Config.Authentication.SchemaRegistryAuthenticationBasic.Password.SecretRef != nil {
						refs = append(refs, *obj.Spec.APISpec.EventGatewaySchemaRegistryConfig.SchemaRegistryConfluent.Config.Authentication.SchemaRegistryAuthenticationBasic.Password.SecretRef)
					}
				}
			}
		}
	}
	return refs
}

// ToSchemaRegistryCreate converts the EventGatewaySchemaRegistry to the SDK type
// sdkkonnectcomp.SchemaRegistryCreate, resolving referenced Secrets via the provided client.
func (obj *EventGatewaySchemaRegistry) ToSchemaRegistryCreate(ctx context.Context, cl client.Client) (*sdkkonnectcomp.SchemaRegistryCreate, error) {
	spec, err := obj.sdkOpsAPISpec(ctx, cl)
	if err != nil {
		return nil, err
	}
	return spec.ToSchemaRegistryCreate()
}

// ToUpdateEventGatewaySchemaRegistryRequest converts the EventGatewaySchemaRegistry to the SDK type
// sdkkonnectoper.UpdateEventGatewaySchemaRegistryRequest, resolving referenced Secrets via the provided client.
func (obj *EventGatewaySchemaRegistry) ToUpdateEventGatewaySchemaRegistryRequest(ctx context.Context, cl client.Client) (*sdkkonnectoper.UpdateEventGatewaySchemaRegistryRequest, error) {
	spec, err := obj.sdkOpsAPISpec(ctx, cl)
	if err != nil {
		return nil, err
	}
	return spec.ToUpdateEventGatewaySchemaRegistryRequest()
}
