// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"encoding/json"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	sdkkonnectcomp "github.com/Kong/sdk-konnect-go/models/components"
)

func (s *EventGatewayDataPlaneCertificateAPISpec) marshalSDKOpsPayload() ([]byte, error) {
	data, err := json.Marshal(s)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal EventGatewayDataPlaneCertificateAPISpec: %w", err)
	}
	var payload any
	if err := json.Unmarshal(data, &payload); err != nil {
		return nil, fmt.Errorf("failed to decode EventGatewayDataPlaneCertificateAPISpec: %w", err)
	}
	payload = flattenSDKUnions(payload)
	payload = flattenSensitiveData(payload)
	// Convert camelCase CRD wire-format keys and discriminator values to
	// snake_case for the Konnect SDK request types.
	payload = renameKeysToSDK(payload)
	data, err = json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal normalized EventGatewayDataPlaneCertificateAPISpec: %w", err)
	}
	return data, nil
}

// ToCreateEventGatewayDataPlaneCertificateRequest converts the EventGatewayDataPlaneCertificateAPISpec to the SDK type
// sdkkonnectcomp.CreateEventGatewayDataPlaneCertificateRequest using JSON marshal/unmarshal.
// Fields that exist in the CRD spec but not in the SDK type (e.g., Kubernetes
// object references) are naturally excluded because they have different JSON names.
func (s *EventGatewayDataPlaneCertificateAPISpec) ToCreateEventGatewayDataPlaneCertificateRequest() (*sdkkonnectcomp.CreateEventGatewayDataPlaneCertificateRequest, error) {
	data, err := s.marshalSDKOpsPayload()
	if err != nil {
		return nil, err
	}
	var target sdkkonnectcomp.CreateEventGatewayDataPlaneCertificateRequest
	if err := json.Unmarshal(data, &target); err != nil {
		return nil, fmt.Errorf("failed to unmarshal into CreateEventGatewayDataPlaneCertificateRequest: %w", err)
	}
	return &target, nil
}

// ToUpdateEventGatewayDataPlaneCertificateRequest converts the EventGatewayDataPlaneCertificateAPISpec to the SDK type
// sdkkonnectcomp.UpdateEventGatewayDataPlaneCertificateRequest using JSON marshal/unmarshal.
// Fields that exist in the CRD spec but not in the SDK type (e.g., Kubernetes
// object references) are naturally excluded because they have different JSON names.
func (s *EventGatewayDataPlaneCertificateAPISpec) ToUpdateEventGatewayDataPlaneCertificateRequest() (*sdkkonnectcomp.UpdateEventGatewayDataPlaneCertificateRequest, error) {
	data, err := s.marshalSDKOpsPayload()
	if err != nil {
		return nil, err
	}
	var target sdkkonnectcomp.UpdateEventGatewayDataPlaneCertificateRequest
	if err := json.Unmarshal(data, &target); err != nil {
		return nil, fmt.Errorf("failed to unmarshal into UpdateEventGatewayDataPlaneCertificateRequest: %w", err)
	}
	return &target, nil
}

func (obj *EventGatewayDataPlaneCertificate) sdkOpsAPISpec(ctx context.Context, cl client.Client) (*EventGatewayDataPlaneCertificateAPISpec, error) {
	if obj == nil {
		return nil, fmt.Errorf("EventGatewayDataPlaneCertificate is nil")
	}

	apiSpec := obj.Spec.APISpec
	// Resolve spec.apiSpec.certificate
	{
		src := apiSpec.Certificate
		if src.Type == SensitiveDataSourceTypeSecretRef {
			if src.SecretRef == nil {
				return nil, fmt.Errorf("secretRef is nil for spec.apiSpec.certificate")
			}
			namespace := obj.GetNamespace()
			if src.SecretRef.Namespace != nil && *src.SecretRef.Namespace != "" {
				namespace = *src.SecretRef.Namespace
			}
			var secret corev1.Secret
			if err := cl.Get(ctx, client.ObjectKey{Namespace: namespace, Name: src.SecretRef.Name}, &secret); err != nil {
				return nil, fmt.Errorf("failed to fetch Secret %s/%s: %w", namespace, src.SecretRef.Name, err)
			}
			key := src.SecretRef.Key
			if key == "" {
				key = "tls.crt"
			}
			secretBytes, ok := secret.Data[key]
			if !ok {
				return nil, fmt.Errorf("secret %s/%s is missing key %q", namespace, src.SecretRef.Name, key)
			}
			resolved := string(secretBytes)
			apiSpec.Certificate.Value = &resolved
		}
	}
	return &apiSpec, nil
}

// GetSensitiveDataSecretRefs returns all Secret references used to populate sensitive SDK payload fields.
func (obj *EventGatewayDataPlaneCertificate) GetSensitiveDataSecretRefs() []SensitiveDataSecretRef {
	if obj == nil {
		return nil
	}
	var refs []SensitiveDataSecretRef
	if obj.Spec.APISpec.Certificate.Type == SensitiveDataSourceTypeSecretRef && obj.Spec.APISpec.Certificate.SecretRef != nil {
		ref := *obj.Spec.APISpec.Certificate.SecretRef
		if ref.Key == "" {
			ref.Key = "tls.crt"
		}
		refs = append(refs, ref)
	}
	return refs
}

// ToCreateEventGatewayDataPlaneCertificateRequest converts the EventGatewayDataPlaneCertificate to the SDK type
// sdkkonnectcomp.CreateEventGatewayDataPlaneCertificateRequest, resolving referenced Secrets via the provided client.
func (obj *EventGatewayDataPlaneCertificate) ToCreateEventGatewayDataPlaneCertificateRequest(ctx context.Context, cl client.Client) (*sdkkonnectcomp.CreateEventGatewayDataPlaneCertificateRequest, error) {
	spec, err := obj.sdkOpsAPISpec(ctx, cl)
	if err != nil {
		return nil, err
	}
	return spec.ToCreateEventGatewayDataPlaneCertificateRequest()
}

// ToUpdateEventGatewayDataPlaneCertificateRequest converts the EventGatewayDataPlaneCertificate to the SDK type
// sdkkonnectcomp.UpdateEventGatewayDataPlaneCertificateRequest, resolving referenced Secrets via the provided client.
func (obj *EventGatewayDataPlaneCertificate) ToUpdateEventGatewayDataPlaneCertificateRequest(ctx context.Context, cl client.Client) (*sdkkonnectcomp.UpdateEventGatewayDataPlaneCertificateRequest, error) {
	spec, err := obj.sdkOpsAPISpec(ctx, cl)
	if err != nil {
		return nil, err
	}
	return spec.ToUpdateEventGatewayDataPlaneCertificateRequest()
}
