// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"fmt"
	commonv1alpha1 "github.com/kong/kong-operator/v2/api/common/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EventGatewaySchemaRegistry is the Schema for the eventgatewayschemaregistrys API.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories=kong
// +kubebuilder:printcolumn:name="ID",description="Konnect ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="Programmed",description="The Resource is Programmed on Konnect",type=string,JSONPath=`.status.conditions[?(@.type=='Programmed')].status`
// +kubebuilder:printcolumn:name="OrgID",description="Konnect Organization ID this resource belongs to.",type=string,JSONPath=`.status.organizationID`
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:storageversion
// +apireference:kgo:include
// +kong:channels=kong-operator
type EventGatewaySchemaRegistry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +optional
	Spec EventGatewaySchemaRegistrySpec `json:"spec,omitzero"`

	// +optional
	Status EventGatewaySchemaRegistryStatus `json:"status,omitzero"`
}

// EventGatewaySchemaRegistryList contains a list of EventGatewaySchemaRegistry.
//
// +kubebuilder:object:root=true
type EventGatewaySchemaRegistryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []EventGatewaySchemaRegistry `json:"items"`
}

// EventGatewaySchemaRegistrySpec defines the desired state of EventGatewaySchemaRegistry.
type EventGatewaySchemaRegistrySpec struct {
	// GatewayRef is the reference to the parent Gateway object.
	//
	// +required
	GatewayRef commonv1alpha1.ObjectRef `json:"gatewayRef,omitzero"`

	// APISpec defines the desired state of the resource's API spec fields.
	//
	// +optional
	APISpec EventGatewaySchemaRegistryAPISpec `json:"apiSpec,omitzero"`
}

// EventGatewaySchemaRegistryAPISpec defines the API spec fields for EventGatewaySchemaRegistry.
type EventGatewaySchemaRegistryAPISpec struct {
	// EventGatewaySchemaRegistryConfig embeds the union type configuration.
	//
	// +optional
	*EventGatewaySchemaRegistryConfig `json:",inline"`
}

// EventGatewaySchemaRegistryStatus defines the observed state of EventGatewaySchemaRegistry.
type EventGatewaySchemaRegistryStatus struct {
	// Conditions represent the current state of the resource.
	//
	// +optional
	// +listType=map
	// +listMapKey=type
	// +patchStrategy=merge
	// +patchMergeKey=type
	// +kubebuilder:validation:MaxItems=8
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type" protobuf:"bytes,1,rep,name=conditions"`

	// Konnect contains the Konnect entity status.
	//
	// +optional
	KonnectEntityStatus `json:",inline"`

	// GatewayID is the Konnect ID of the parent Gateway.
	//
	// +optional
	GatewayID *KonnectEntityRef `json:"gatewayID,omitempty"`

	// ObservedGeneration is the most recent generation observed
	//
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitzero"`
}

// EventGatewaySchemaRegistryConfig represents a union type for EventGatewaySchemaRegistryConfig.
// Only one of the fields should be set based on the Type.
type EventGatewaySchemaRegistryConfig struct {
	// Type designates the type of configuration.
	//
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:Enum=confluent
	Type EventGatewaySchemaRegistryConfigType `json:"type,omitempty"`

	// SchemaRegistryConfluent configuration.
	//
	// +optional
	SchemaRegistryConfluent *SchemaRegistryConfluent `json:"confluent,omitempty"`
}

// EventGatewaySchemaRegistryConfigType represents the type of EventGatewaySchemaRegistryConfig.
type EventGatewaySchemaRegistryConfigType string

// EventGatewaySchemaRegistryConfigType values.
const (
	EventGatewaySchemaRegistryConfigTypeSchemaRegistryConfluent EventGatewaySchemaRegistryConfigType = "confluent"
)

// MarshalJSON implements json.Marshaler.
func (u EventGatewaySchemaRegistryConfig) MarshalJSON() ([]byte, error) {
	m := map[string]json.RawMessage{}
	typeBytes, err := json.Marshal(string(u.Type))
	if err != nil {
		return nil, fmt.Errorf("marshaling EventGatewaySchemaRegistryConfig type: %w", err)
	}
	m["type"] = typeBytes
	switch u.Type {
	case EventGatewaySchemaRegistryConfigTypeSchemaRegistryConfluent:
		if u.SchemaRegistryConfluent != nil {
			raw, err := json.Marshal(u.SchemaRegistryConfluent)
			if err != nil {
				return nil, fmt.Errorf("marshaling EventGatewaySchemaRegistryConfig confluent: %w", err)
			}
			m["confluent"] = raw
		}
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements json.Unmarshaler.
func (u *EventGatewaySchemaRegistryConfig) UnmarshalJSON(data []byte) error {
	if u == nil {
		return fmt.Errorf("unmarshaling EventGatewaySchemaRegistryConfig: nil receiver")
	}
	var probe struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return err
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	u.Type = EventGatewaySchemaRegistryConfigType(probe.Type)
	switch probe.Type {
	case "confluent":
		payload, ok := raw["confluent"]
		if !ok || len(payload) == 0 {
			return nil
		}
		var val SchemaRegistryConfluent
		if err := json.Unmarshal(payload, &val); err != nil {
			return fmt.Errorf("unmarshaling EventGatewaySchemaRegistryConfig confluent: %w", err)
		}
		u.SchemaRegistryConfluent = &val
	}
	return nil
}

// MarshalJSON implements json.Marshaler.
func (s *EventGatewaySchemaRegistryAPISpec) MarshalJSON() ([]byte, error) {
	if s == nil {
		return []byte("null"), nil
	}
	if s.EventGatewaySchemaRegistryConfig == nil {
		return []byte("{}"), nil
	}
	data, err := json.Marshal(s.EventGatewaySchemaRegistryConfig)
	if err != nil {
		return nil, fmt.Errorf("marshaling EventGatewaySchemaRegistryAPISpec: %w", err)
	}
	return data, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (s *EventGatewaySchemaRegistryAPISpec) UnmarshalJSON(data []byte) error {
	if s == nil {
		return fmt.Errorf("unmarshaling EventGatewaySchemaRegistryAPISpec: nil receiver")
	}
	type alias EventGatewaySchemaRegistryAPISpec
	aux := alias{}
	aux.EventGatewaySchemaRegistryConfig = &EventGatewaySchemaRegistryConfig{}
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("unmarshaling EventGatewaySchemaRegistryAPISpec: %w", err)
	}
	if aux.EventGatewaySchemaRegistryConfig != nil && aux.EventGatewaySchemaRegistryConfig.Type == "" && aux.EventGatewaySchemaRegistryConfig.SchemaRegistryConfluent == nil {
		aux.EventGatewaySchemaRegistryConfig = nil
	}
	*s = EventGatewaySchemaRegistryAPISpec(aux)
	return nil
}
