// Code generated by CRD generation pipeline. DO NOT EDIT.

package sdkmocks

import (
	"testing"

	sdkkonnectgo "github.com/Kong/sdk-konnect-go"
	"github.com/Kong/sdk-konnect-go/test/mocks"
)

type generatedMockSDKWrapper struct {
	EventGatewayListenersSDK             *mocks.MockEventGatewayListenersSDK
	PortalAuthSettingsSDK                *mocks.MockPortalAuthSettingsSDK
	EventGatewayDataPlaneCertificatesSDK *mocks.MockEventGatewayDataPlaneCertificatesSDK
	EventGatewaysSDK                     *mocks.MockEventGatewaysSDK
	PortalsSDK                           *mocks.MockPortalsSDK
	PortalPagesSDK                       *mocks.MockPortalPagesSDK
	PortalTeamsSDK                       *mocks.MockPortalTeamsSDK
}

func newGeneratedMockSDKWrapper(t *testing.T) generatedMockSDKWrapper {
	return generatedMockSDKWrapper{
		EventGatewayListenersSDK:             mocks.NewMockEventGatewayListenersSDK(t),
		PortalAuthSettingsSDK:                mocks.NewMockPortalAuthSettingsSDK(t),
		EventGatewayDataPlaneCertificatesSDK: mocks.NewMockEventGatewayDataPlaneCertificatesSDK(t),
		EventGatewaysSDK:                     mocks.NewMockEventGatewaysSDK(t),
		PortalsSDK:                           mocks.NewMockPortalsSDK(t),
		PortalPagesSDK:                       mocks.NewMockPortalPagesSDK(t),
		PortalTeamsSDK:                       mocks.NewMockPortalTeamsSDK(t),
	}
}

// GetEventGatewayListenersSDK returns the SDK to operate EventGatewayListener.
func (m generatedMockSDKWrapper) GetEventGatewayListenersSDK() sdkkonnectgo.EventGatewayListenersSDK {
	return m.EventGatewayListenersSDK
}

// GetPortalAuthSettingsSDK returns the SDK to operate IdentityProviderRequest.
func (m generatedMockSDKWrapper) GetPortalAuthSettingsSDK() sdkkonnectgo.PortalAuthSettingsSDK {
	return m.PortalAuthSettingsSDK
}

// GetEventGatewayDataPlaneCertificatesSDK returns the SDK to operate KonnectEventDataPlaneCertificate.
func (m generatedMockSDKWrapper) GetEventGatewayDataPlaneCertificatesSDK() sdkkonnectgo.EventGatewayDataPlaneCertificatesSDK {
	return m.EventGatewayDataPlaneCertificatesSDK
}

// GetEventGatewaysSDK returns the SDK to operate KonnectEventGateway.
func (m generatedMockSDKWrapper) GetEventGatewaysSDK() sdkkonnectgo.EventGatewaysSDK {
	return m.EventGatewaysSDK
}

// GetPortalsSDK returns the SDK to operate Portal.
func (m generatedMockSDKWrapper) GetPortalsSDK() sdkkonnectgo.PortalsSDK {
	return m.PortalsSDK
}

// GetPortalPagesSDK returns the SDK to operate PortalPage.
func (m generatedMockSDKWrapper) GetPortalPagesSDK() sdkkonnectgo.PortalPagesSDK {
	return m.PortalPagesSDK
}

// GetPortalTeamsSDK returns the SDK to operate PortalTeam.
func (m generatedMockSDKWrapper) GetPortalTeamsSDK() sdkkonnectgo.PortalTeamsSDK {
	return m.PortalTeamsSDK
}
