// Code generated by CRD generation pipeline. DO NOT EDIT.

package sdk

import (
	sdkkonnectgo "github.com/Kong/sdk-konnect-go"
)

// GeneratedSDK is the interface for generated SDKs.
type GeneratedSDK interface {
	GetPortalAuthSettingsSDK() sdkkonnectgo.PortalAuthSettingsSDK
	GetEventGatewaysSDK() sdkkonnectgo.EventGatewaysSDK
	GetEventGatewayDataPlaneCertificatesSDK() sdkkonnectgo.EventGatewayDataPlaneCertificatesSDK
	GetPortalsSDK() sdkkonnectgo.PortalsSDK
	GetPortalTeamsSDK() sdkkonnectgo.PortalTeamsSDK
}

// GetPortalAuthSettingsSDK returns the SDK to operate IdentityProviderRequest.
func (w sdkWrapper) GetPortalAuthSettingsSDK() sdkkonnectgo.PortalAuthSettingsSDK {
	return w.sdk.PortalAuthSettings
}

// GetEventGatewaysSDK returns the SDK to operate KonnectEventControlPlane.
func (w sdkWrapper) GetEventGatewaysSDK() sdkkonnectgo.EventGatewaysSDK {
	return w.sdk.EventGateways
}

// GetEventGatewayDataPlaneCertificatesSDK returns the SDK to operate KonnectEventDataPlaneCertificate.
func (w sdkWrapper) GetEventGatewayDataPlaneCertificatesSDK() sdkkonnectgo.EventGatewayDataPlaneCertificatesSDK {
	return w.sdk.EventGatewayDataPlaneCertificates
}

// GetPortalsSDK returns the SDK to operate Portal.
func (w sdkWrapper) GetPortalsSDK() sdkkonnectgo.PortalsSDK {
	return w.sdk.Portals
}

// GetPortalTeamsSDK returns the SDK to operate PortalTeam.
func (w sdkWrapper) GetPortalTeamsSDK() sdkkonnectgo.PortalTeamsSDK {
	return w.sdk.PortalTeams
}
