// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"fmt"

	sdkkonnectcomp "github.com/Kong/sdk-konnect-go/models/components"
)


type DcrProviderSDKOpsBoolField struct {
	Label string
	Path  []string
}

var DcrProviderSDKOpsBoolFields = []DcrProviderSDKOpsBoolField{
	{
		Label: "auth0.dcr_config.use_developer_managed_scopes",
		Path: []string{
			"auth0",
			"dcr_config",
			"use_developer_managed_scopes",
		},
	},
	{
		Label: "http.dcr_config.allow_multiple_credentials",
		Path: []string{
			"http",
			"dcr_config",
			"allow_multiple_credentials",
		},
	},
	{
		Label: "http.dcr_config.disable_event_hooks",
		Path: []string{
			"http",
			"dcr_config",
			"disable_event_hooks",
		},
	},
	{
		Label: "http.dcr_config.disable_refresh_secret",
		Path: []string{
			"http",
			"dcr_config",
			"disable_refresh_secret",
		},
	},
}

func normalizeDcrProviderSDKOpsBoolFields(payload map[string]any) error {
	for _, field := range DcrProviderSDKOpsBoolFields {
		if _, err := normalizeDcrProviderSDKOpsBoolField(payload, field.Path); err != nil {
			return fmt.Errorf("%s: %w", field.Label, err)
		}
	}
	return nil
}

func normalizeDcrProviderSDKOpsBoolField(value any, path []string) (any, error) {
	if len(path) == 0 {
		switch typed := value.(type) {
		case nil:
			return nil, nil
		case bool:
			return typed, nil
		case string:
			switch typed {
			case "Enabled":
				return true, nil
			case "Disabled":
				return false, nil
			default:
				return nil, fmt.Errorf("unexpected boolean enum %q", typed)
			}
		default:
			return nil, fmt.Errorf("expected string boolean enum, got %T", value)
		}
	}

	if value == nil {
		return nil, nil
	}

	segment := path[0]
	switch segment {
	case "[]":
		items, ok := value.([]any)
		if !ok {
			return nil, fmt.Errorf("expected array, got %T", value)
		}
		for i, item := range items {
			normalized, err := normalizeDcrProviderSDKOpsBoolField(item, path[1:])
			if err != nil {
				return nil, err
			}
			items[i] = normalized
		}
		return items, nil
	case "{}":
		object, ok := value.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("expected object, got %T", value)
		}
		for key, item := range object {
			normalized, err := normalizeDcrProviderSDKOpsBoolField(item, path[1:])
			if err != nil {
				return nil, err
			}
			object[key] = normalized
		}
		return object, nil
	default:
		object, ok := value.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("expected object, got %T", value)
		}
		child, ok := object[segment]
		if !ok {
			return value, nil
		}
		normalized, err := normalizeDcrProviderSDKOpsBoolField(child, path[1:])
		if err != nil {
			return nil, err
		}
		object[segment] = normalized
		return object, nil
	}
}

func (s *DcrProviderAPISpec) marshalSDKOpsPayload() (map[string]any, error) {
	data, err := json.Marshal(s)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal DcrProviderAPISpec: %w", err)
	}

	var payload map[string]any
	if err := json.Unmarshal(data, &payload); err != nil {
		return nil, fmt.Errorf("failed to decode DcrProviderAPISpec: %w", err)
	}
	if err := normalizeDcrProviderSDKOpsBoolFields(payload); err != nil {
		return nil, fmt.Errorf("failed to normalize DcrProviderAPISpec SDK payload: %w", err)
	}
	return payload, nil
}

func (s *DcrProviderAPISpec) selectedSDKOpsPayload(payload map[string]any) ([]byte, string, error) {
	if s == nil || s.DcrProviderConfig == nil {
		return nil, "", fmt.Errorf("DcrProvider config is required")
	}

	var selected any
	var variant string
	switch s.DcrProviderConfig.Type {
	case DcrProviderConfigTypeAuth0:
		selected = payload["auth0"]
		variant = "Auth0"
	case DcrProviderConfigTypeAzureAd:
		selected = payload["azuread"]
		variant = "AzureAd"
	case DcrProviderConfigTypeCurity:
		selected = payload["curity"]
		variant = "Curity"
	case DcrProviderConfigTypeOkta:
		selected = payload["okta"]
		variant = "Okta"
	case DcrProviderConfigTypeHTTP:
		selected = payload["http"]
		variant = "HTTP"
	default:
		return nil, "", fmt.Errorf("unsupported DcrProvider config type %q", s.DcrProviderConfig.Type)
	}

	if selected == nil {
		return nil, "", fmt.Errorf("DcrProvider config payload missing for type %q", s.DcrProviderConfig.Type)
	}

	data, err := json.Marshal(selected)
	if err != nil {
		return nil, "", fmt.Errorf("failed to marshal selected DcrProvider config: %w", err)
	}
	return data, variant, nil
}


// ToCreateDcrProviderRequest converts the DcrProviderAPISpec to the SDK type
// sdkkonnectcomp.CreateDcrProviderRequest using JSON marshal/unmarshal.
// Fields that exist in the CRD spec but not in the SDK type (e.g., Kubernetes
// object references) are naturally excluded because they have different JSON names.
func (s *DcrProviderAPISpec) ToCreateDcrProviderRequest() (*sdkkonnectcomp.CreateDcrProviderRequest, error) {
	payload, err := s.marshalSDKOpsPayload()
	if err != nil {
		return nil, err
	}
	data, variant, err := s.selectedSDKOpsPayload(payload)
	if err != nil {
		return nil, err
	}
	
	switch variant {
	case "Auth0":
		var member sdkkonnectcomp.CreateDcrProviderRequestAuth0
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into CreateDcrProviderRequestAuth0: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateDcrProviderRequestAuth0(member)
		return &target, nil
	case "AzureAd":
		var member sdkkonnectcomp.CreateDcrProviderRequestAzureAd
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into CreateDcrProviderRequestAzureAd: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateDcrProviderRequestAzureAd(member)
		return &target, nil
	case "Curity":
		var member sdkkonnectcomp.CreateDcrProviderRequestCurity
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into CreateDcrProviderRequestCurity: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateDcrProviderRequestCurity(member)
		return &target, nil
	case "Okta":
		var member sdkkonnectcomp.CreateDcrProviderRequestOkta
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into CreateDcrProviderRequestOkta: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateDcrProviderRequestOkta(member)
		return &target, nil
	case "HTTP":
		var member sdkkonnectcomp.CreateDcrProviderRequestHTTP
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into CreateDcrProviderRequestHTTP: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateDcrProviderRequestHTTP(member)
		return &target, nil
	default:
		return nil, fmt.Errorf("unsupported DcrProvider config variant %q", variant)
	}
}

// ToUpdateDcrProviderRequest converts the DcrProviderAPISpec to the SDK type
// sdkkonnectcomp.UpdateDcrProviderRequest using JSON marshal/unmarshal.
// Fields that exist in the CRD spec but not in the SDK type (e.g., Kubernetes
// object references) are naturally excluded because they have different JSON names.
func (s *DcrProviderAPISpec) ToUpdateDcrProviderRequest() (*sdkkonnectcomp.UpdateDcrProviderRequest, error) {
	payload, err := s.marshalSDKOpsPayload()
	if err != nil {
		return nil, err
	}
	data, variant, err := s.selectedSDKOpsPayload(payload)
	if err != nil {
		return nil, err
	}
	
	var selected map[string]any
	if err := json.Unmarshal(data, &selected); err != nil {
		return nil, fmt.Errorf("failed to decode selected DcrProvider config: %w", err)
	}
	var target sdkkonnectcomp.UpdateDcrProviderRequest
	if err := json.Unmarshal(data, &target); err != nil {
		return nil, fmt.Errorf("failed to unmarshal into UpdateDcrProviderRequest: %w", err)
	}
	switch variant {
	case "Auth0":
		configPayload, ok := selected["dcr_config"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("DcrProvider config payload missing dcr_config")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal DcrProvider dcr_config payload: %w", err)
		}
		var member sdkkonnectcomp.UpdateDcrConfigAuth0InRequest
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into UpdateDcrConfigAuth0InRequest: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateDcrConfigUpdateDcrConfigAuth0InRequest(member)
		target.DcrConfig = &unionValue
		return &target, nil
	case "AzureAd":
		configPayload, ok := selected["dcr_config"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("DcrProvider config payload missing dcr_config")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal DcrProvider dcr_config payload: %w", err)
		}
		var member sdkkonnectcomp.UpdateDcrConfigAzureAdInRequest
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into UpdateDcrConfigAzureAdInRequest: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateDcrConfigUpdateDcrConfigAzureAdInRequest(member)
		target.DcrConfig = &unionValue
		return &target, nil
	case "Curity":
		configPayload, ok := selected["dcr_config"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("DcrProvider config payload missing dcr_config")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal DcrProvider dcr_config payload: %w", err)
		}
		var member sdkkonnectcomp.UpdateDcrConfigCurityInRequest
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into UpdateDcrConfigCurityInRequest: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateDcrConfigUpdateDcrConfigCurityInRequest(member)
		target.DcrConfig = &unionValue
		return &target, nil
	case "Okta":
		configPayload, ok := selected["dcr_config"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("DcrProvider config payload missing dcr_config")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal DcrProvider dcr_config payload: %w", err)
		}
		var member sdkkonnectcomp.UpdateDcrConfigOktaInRequest
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into UpdateDcrConfigOktaInRequest: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateDcrConfigUpdateDcrConfigOktaInRequest(member)
		target.DcrConfig = &unionValue
		return &target, nil
	case "HTTP":
		configPayload, ok := selected["dcr_config"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("DcrProvider config payload missing dcr_config")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal DcrProvider dcr_config payload: %w", err)
		}
		var member sdkkonnectcomp.UpdateDcrConfigHTTPInRequest
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into UpdateDcrConfigHTTPInRequest: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateDcrConfigUpdateDcrConfigHTTPInRequest(member)
		target.DcrConfig = &unionValue
		return &target, nil
	default:
		return nil, fmt.Errorf("unsupported DcrProvider config variant %q", variant)
	}
}
