// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestDcrProviderAPISpec_ToCreateDcrProviderRequest(t *testing.T) {
	spec := &DcrProviderAPISpec{
	}
	result, err := spec.ToCreateDcrProviderRequest()
	require.Error(t, err)
	require.Nil(t, result)
	return
	require.NoError(t, err)
	require.NotNil(t, result)

	data, err := json.Marshal(result)
	require.NoError(t, err)

	var payload map[string]any
	err = json.Unmarshal(data, &payload)
	require.NoError(t, err)
}

func TestDcrProviderAPISpec_ToUpdateDcrProviderRequest(t *testing.T) {
	spec := &DcrProviderAPISpec{
	}
	result, err := spec.ToUpdateDcrProviderRequest()
	require.Error(t, err)
	require.Nil(t, result)
	return
	require.NoError(t, err)
	require.NotNil(t, result)

	data, err := json.Marshal(result)
	require.NoError(t, err)

	var payload map[string]any
	err = json.Unmarshal(data, &payload)
	require.NoError(t, err)
}
