kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth-1
  namespace: default
spec:
  type: token
  token: kpat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # For a complete list of available API URLs see:https://docs.konghq.com/konnect/network/#kong-gateway-hostnames
  serverURL: eu.api.konghq.com
---
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: cp-cloud-gateway-test1
  namespace: default
spec:
  createControlPlaneRequest:
    cloud_gateway: true
    cluster_type: CLUSTER_TYPE_CONTROL_PLANE
    name: cp-cloud-gateway-test1
    labels:
      app: test1
  konnect:
    authRef:
      name: konnect-api-auth-1
---
kind: KonnectCloudGatewayNetwork
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: mynetwork1
  namespace: default
spec:
  name: mynetwork1
  cloud_gateway_provider_account_id: "11111111-1111-1111-1111-111111111111"
  availability_zones:
  - euc2-az1
  - euc2-az2
  cidr_block: "10.1.0.0/16"
  region: eu-central-2
  konnect:
    authRef:
      name: konnect-api-auth-1
---
# NOTE:
# Data Plane Group Configuration will override any other configuration
# that is applied outside of this configuration.
# Using more than 1 configuration will result in configurations overriding each other.
apiVersion: konnect.konghq.com/v1alpha1
kind: KonnectCloudGatewayDataPlaneGroupConfiguration
metadata:
  name: eu-central-1
  namespace: default
spec:
  api_access: private+public
  version: "3.9"
  dataplane_groups:
    - provider: aws
      region: eu-central-2
      networkRef:
        type: namespacedRef
        namespacedRef:
          name: mynetwork1
      autoscale:
        type: static
        static:
          instance_type: small
          requested_instances: 2
      environment:
        - name: KONG_LOG_LEVEL
          value: debug
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: cp-cloud-gateway-test1
