kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth-dev-1
  namespace: default
spec:
  type: token
  token: kpat_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  serverURL: us.api.konghq.com
---
kind: KonnectGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha2
metadata:
  name: test-cp-basic-auth
  namespace: default
spec:
  createControlPlaneRequest:
    name: test-cp-basic-auth
    labels:
      app: test-cp-basic-auth
      key1: test-cp-basic-auth
  konnect:
    authRef:
      name: konnect-api-auth-dev-1
---
kind: KongConsumer
apiVersion: configuration.konghq.com/v1
metadata:
  name: consumer-hmac-1
  namespace: default
username: consumer1-hmac-1
spec:
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: test-cp-basic-auth
---
apiVersion: configuration.konghq.com/v1alpha1
kind: KongCredentialHMAC
metadata:
  name: hmac-1
  namespace: default
spec:
  consumerRef:
    name: consumer-hmac-1
  secret: secretkey
  username: consumer1-hmac-1
