kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth-1
  namespace: default
spec:
  type: token
  token: kpat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # For a complete list of available API URLs see:https://docs.konghq.com/konnect/network/#kong-gateway-hostnames
  serverURL: us.api.konghq.tech
---
kind: AIGatewayControlPlane
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: ai-gw-cp-1
  namespace: default
spec:
  apiSpec:
    name: ai-gw-cp-1
    displayName: My AI Gateway
    description: AI Gateway control plane
    labels:
      app: test1
  konnect:
    authRef:
      name: konnect-api-auth-1
