kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth
  namespace: default
spec:
  type: token
  token: kpat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # For a complete list of available API URLs see:https://docs.konghq.com/konnect/network/#kong-gateway-hostnames
  serverURL: us.api.konghq.tech
---
kind: KonnectAIGateway
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: ai-gw-cp-1
  namespace: default
spec:
  apiSpec:
    name: ai-gw-cp-1
    displayName: My AI Gateway
    description: AI Gateway control plane
  konnect:
    authRef:
      name: konnect-api-auth
---
kind: AIGatewayConsumer
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: ai-gw-consumer-1
  namespace: default
spec:
  aiGatewayRef:
    type: namespacedRef
    namespacedRef:
      name: ai-gw-cp-1
  apiSpec:
    name: dev-consumer
    displayName: Dev Team Consumer
    type: api-key
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-gw-consumer-1-credential-apikey
  namespace: default
  labels:
    konghq.com/secret: "true"
type: Opaque
stringData:
  api-key: sk-dev-consumer-xxxxxxxxxxxxxxxxxxxx
---
kind: AIGatewayConsumerCredential
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: ai-gw-consumer-credential-1
  namespace: default
spec:
  aiGatewayConsumerRef:
    type: namespacedRef
    namespacedRef:
      name: ai-gw-consumer-1
  apiSpec:
    name: dev-consumer-key
    displayName: Dev Consumer API Key
    type: api-key
    apiKey:
      type: secretRef
      secretRef:
        name: ai-gw-consumer-1-credential-apikey
        key: api-key
