kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth-1
  namespace: default
spec:
  type: token
  token: kpat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # For a complete list of available API URLs see:https://docs.konghq.com/konnect/network/#kong-gateway-hostnames
  serverURL: us.api.konghq.tech
---
kind: KonnectAIGateway
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: ai-gw-cp-1
  namespace: default
spec:
  apiSpec:
    name: ai-gw-cp-1
    displayName: My AI Gateway
    description: AI Gateway control plane
    labels:
      app: test1
  konnect:
    authRef:
      name: konnect-api-auth-1
---
apiVersion: konnect.konghq.com/v1alpha1
kind: AIGatewayPolicy
metadata:
  name: aigw-policy-prompt-decorator
  namespace: default
spec:
  aiGatewayRef:
    type: namespacedRef
    namespacedRef:
      name: ai-gw-cp-1
      namespace: default
  apiSpec:
    displayName: "AIGateway Policy Prompt Decorator"
    name: "aigw-policy-prompt-decorator"
    type: "ai-prompt-decorator"
    enabled: "Enabled"
    global: "Enabled"
    config:
      type: secretRef
      secretRef:
        name: aigw-policy-prompt-decorator-config
        namespace: default
        key: config
---
apiVersion: v1
kind: Secret
metadata:
  name: aigw-policy-prompt-decorator-config
  namespace: default
  labels:
    konghq.com/secret: "true"
type: Opaque
stringData:
  config: '{"llm_format": "openai", "max_request_body_size": 8388608, "prompts": {"append": null, "prepend": [{"content": "In short words.", "role": "user"}]}}'
