kind: KonnectAPIAuthConfiguration
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: konnect-api-auth
  namespace: default
spec:
  type: token
  token: kpat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # For a complete list of available API URLs see:https://docs.konghq.com/konnect/network/#kong-gateway-hostnames
  serverURL: us.api.konghq.tech
---
kind: KonnectAIGateway
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: ai-gw-cp-1
  namespace: default
spec:
  apiSpec:
    name: ai-gw-cp-1
    displayName: My AI Gateway
    description: AI Gateway control plane
  konnect:
    authRef:
      name: konnect-api-auth
---
kind: AIGatewayConsumer
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: ai-gw-consumer-1
  namespace: default
spec:
  aiGatewayRef:
    type: namespacedRef
    namespacedRef:
      name: ai-gw-cp-1
  apiSpec:
    name: dev-consumer
    displayName: Dev Team Consumer
    # References to AIGatewayPolicy CRs (by metadata.name) applied to this
    # consumer group. See config/samples/konnect_aigatewaypolicy.yaml for the
    # referenced policy.
    policies:
      - name: aigw-policy-prompt-decorator
    type: api-key
    labels:
      team: platform-dev
