kind: Portal
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: portal1
  namespace: default
spec:
  konnect:
    authRef:
      name: konnect-api-auth
  apiSpec:
    name: portal1
    authenticationEnabled: Enabled
---
kind: PortalCustomization
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: portal1-customization
  namespace: default
spec:
  portalRef:
    type: namespacedRef
    namespacedRef:
      name: portal1
  apiSpec:
    css: |
      body { background-color: #f0f0f0; }
