kind: Portal
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: portal1
  namespace: default
spec:
  konnect:
    authRef:
      name: konnect-api-auth
  apiSpec:
    name: portal1
    authenticationEnabled: Enabled
---
kind: PortalIPAllowList
apiVersion: konnect.konghq.com/v1alpha1
metadata:
  name: portal1-ipallowlist
  namespace: default
spec:
  portalRef:
    type: namespacedRef
    namespacedRef:
      name: portal1
  apiSpec:
    allowedIps:
    - "10.0.0.0/24"
    - "12.0.0.2"
