# TODO: Enable conversion webhooks for test suites:
# https://github.com/Kong/kong-operator/issues/1986
# kind: GatewayConfiguration
# apiVersion: gateway-operator.konghq.com/v1beta1
# metadata:
#   name: kong
#   namespace: default
# spec:
#   dataPlaneOptions:
#     deployment:
#       replicas: 1
#       podTemplateSpec:
#         metadata:
#           labels:
#             dataplane-pod-label: example
#           annotations:
#             dataplane-pod-annotation: example
#         spec:
#           containers:
#           - name: proxy
#             # renovate: datasource=docker versioning=docker
#             image: kong:3.9
#             env:
#             - name: KONG_LOG_LEVEL
#               value: debug
#             readinessProbe:
#               initialDelaySeconds: 1
#               periodSeconds: 1
#     network:
#       services:
#         ingress:
#           annotations:
#             foo: bar
#   controlPlaneOptions:
#     deployment:
#       podTemplateSpec:
#         metadata:
#           labels:
#             controlplane-pod-label: example
#         spec:
#           containers:
#           - name: controller
#             env:
#             - name: CONTROLLER_LOG_LEVEL
#               value: debug
#             readinessProbe:
#               initialDelaySeconds: 1
#               periodSeconds: 1
#     extensions:
#     - kind: DataPlaneMetricsExtension
#       group: gateway-operator.konghq.com
#       name: kong
# ---
# kind: DataPlaneMetricsExtension
# apiVersion: gateway-operator.konghq.com/v1alpha1
# metadata:
#   name: kong
#   namespace: default
# spec:
#   serviceSelector:
#     matchNames:
#     - name: echo
#   config:
#     latency: true
# ---
# kind: GatewayClass
# apiVersion: gateway.networking.k8s.io/v1
# metadata:
#   name: kong
# spec:
#   controllerName: konghq.com/gateway-operator
#   parametersRef:
#     group: gateway-operator.konghq.com
#     kind: GatewayConfiguration
#     name: kong
#     namespace: default
# ---
# kind: Gateway
# apiVersion: gateway.networking.k8s.io/v1
# metadata:
#   name: kong
#   namespace: default
# spec:
#   gatewayClassName: kong
#   listeners:
#   - name: http
#     protocol: HTTP
#     port: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: echo
#   namespace: default
# spec:
#   ports:
#     - protocol: TCP
#       name: http
#       port: 80
#       targetPort: http
#   selector:
#     app: echo
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: echo
#   name: echo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: echo
#   template:
#     metadata:
#       labels:
#         app: echo
#     spec:
#       containers:
#         - name: echo
#           image: registry.k8s.io/e2e-test-images/agnhost:2.40
#           command:
#             - /agnhost
#             - netexec
#             - --http-port=8080
#           ports:
#             - containerPort: 8080
#               name: http
#           env:
#             - name: NODE_NAME
#               valueFrom:
#                 fieldRef:
#                   fieldPath: spec.nodeName
#             - name: POD_NAME
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.name
#             - name: NAMESPACE
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.namespace
#             - name: POD_IP
#               valueFrom:
#                 fieldRef:
#                   fieldPath: status.podIP
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: httproute-echo
#   namespace: default
#   annotations:
#     konghq.com/strip-path: "true"
# spec:
#   parentRefs:
#   - name: kong
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /echo
#     backendRefs:
#     - name: echo
#       kind: Service
#       port: 80
