# TODO: Enable conversion webhooks for test suites:
# https://github.com/Kong/kong-operator/issues/1986
# apiVersion: gateway-operator.konghq.com/v1beta1
# kind: DataPlane
# metadata:
#   name: dataplane-cp-watchnamespace
#   namespace: default
# spec:
#   deployment:
#     podTemplateSpec:
#       spec:
#         containers:
#         - name: proxy
#           # renovate: datasource=docker versioning=docker
#           image: kong:3.9
#           env:
#           - name: KONG_LOG_LEVEL
#             value: debug
#           resources:
#             requests:
#               memory: "64Mi"
#               cpu: "250m"
#             limits:
#               memory: "1024Mi"
#               cpu: "1000m"
#           readinessProbe:
#             initialDelaySeconds: 1
#             periodSeconds: 1
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: namespace-a
# ---
# apiVersion: gateway-operator.konghq.com/v1alpha1
# kind: WatchNamespaceGrant
# metadata:
#   name: watchnamespacegrant
#   namespace: namespace-a
# spec:
#   from:
#   - group: gateway-operator.konghq.com
#     kind: ControlPlane
#     namespace: default
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: namespace-b
# ---
# apiVersion: gateway-operator.konghq.com/v1alpha1
# kind: WatchNamespaceGrant
# metadata:
#   name: watchnamespacegrant
#   namespace: namespace-b
# spec:
#   from:
#   - group: gateway-operator.konghq.com
#     kind: ControlPlane
#     namespace: default
# ---
# apiVersion: gateway-operator.konghq.com/v1beta1
# kind: ControlPlane
# metadata:
#   name: controlplane-example
#   namespace: default
# spec:
#   dataplane: dataplane-cp-watchnamespace
#   gatewayClass: kong
#   watchNamespaces:
#     # Using "list" also adds ControlPlane's own namespace to the list
#     # of watched namespaces because that's that KIC does. The reason
#     # for this is the publish service (DataPlane's Service exposed by Kong) by default
#     # would exist in the same namespace as ControlPlane.
#     type: list
#     list:
#     - namespace-a
#     - namespace-b
#   deployment:
#     podTemplateSpec:
#       metadata:
#         labels:
#           controlplane-pod-label: example
#       spec:
#         containers:
#         - name: controller
#           # renovate: datasource=docker versioning=docker
#           image: kong/kubernetes-ingress-controller:3.5.2
#           readinessProbe:
#             initialDelaySeconds: 1
#             periodSeconds: 3
#           resources:
#             requests:
#               memory: "64Mi"
#               cpu: "250m"
#             limits:
#               memory: "1024Mi"
#               cpu: "1000m"
