# TODO: Enable conversion webhooks for test suites:
# https://github.com/Kong/kong-operator/issues/1986
# apiVersion: v1
# kind: Service
# metadata:
#   name: echo
# spec:
#   ports:
#     - protocol: TCP
#       name: http
#       port: 80
#       targetPort: http
#   selector:
#     app: echo
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: echo
#   name: echo
# spec:
#   selector:
#     matchLabels:
#       app: echo
#   template:
#     metadata:
#       labels:
#         app: echo
#     spec:
#       containers:
#         - name: echo
#           image: registry.k8s.io/e2e-test-images/agnhost:2.40
#           command:
#             - /agnhost
#             - netexec
#             - --http-port=8080
#           ports:
#             - containerPort: 8080
#               name: http
#           env:
#             - name: NODE_NAME
#               valueFrom:
#                 fieldRef:
#                   fieldPath: spec.nodeName
#             - name: POD_NAME
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.name
#             - name: NAMESPACE
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.namespace
#             - name: POD_IP
#               valueFrom:
#                 fieldRef:
#                   fieldPath: status.podIP
# ---
# kind: GatewayConfiguration
# apiVersion: gateway-operator.konghq.com/v1beta1
# metadata:
#   name: kong
#   namespace: default
# spec:
#   dataPlaneOptions:
#     deployment:
#       podTemplateSpec:
#         spec:
#           containers:
#           - name: proxy
#             # renovate: datasource=docker versioning=docker
#             image: kong:3.9
#             readinessProbe:
#               initialDelaySeconds: 1
#               periodSeconds: 1
#   controlPlaneOptions:
#     deployment:
#       podTemplateSpec:
#         spec:
#           containers:
#           - name: controller
#             # renovate: datasource=docker versioning=docker
#             image: kong/kubernetes-ingress-controller:3.5.0
#             readinessProbe:
#               initialDelaySeconds: 1
#               periodSeconds: 1
#             env:
#             - name: CONTROLLER_ADMISSION_WEBHOOK_LISTEN
#               value: "off"
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: GatewayClass
# metadata:
#   name: kong
# spec:
#   controllerName: konghq.com/gateway-operator
#   parametersRef:
#     group: gateway-operator.konghq.com
#     kind: GatewayConfiguration
#     name: kong
#     namespace: default
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: kong
#   namespace: default
# spec:
#   gatewayClassName: kong
#   listeners:
#   - name: http
#     protocol: HTTP
#     port: 80
