package service

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"

	commonv1alpha1 "github.com/kong/kong-operator/api/common/v1alpha1"
	configurationv1alpha1 "github.com/kong/kong-operator/api/configuration/v1alpha1"
	"github.com/kong/kong-operator/controller/hybridgateway/namegen"
	gwtypes "github.com/kong/kong-operator/internal/types"
	"github.com/kong/kong-operator/pkg/consts"
)

func TestServiceForRule(t *testing.T) {
	ctx := context.Background()
	logger := zap.New()

	// Create a scheme with the necessary types
	scheme := runtime.NewScheme()
	require.NoError(t, configurationv1alpha1.AddToScheme(scheme))

	// Create test HTTPRoute
	httpRoute := &gwtypes.HTTPRoute{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "test-route",
			Namespace: "test-namespace",
		},
		Spec: gatewayv1.HTTPRouteSpec{
			CommonRouteSpec: gatewayv1.CommonRouteSpec{
				ParentRefs: []gatewayv1.ParentReference{
					{Name: "test-gateway"},
				},
			},
		},
	}

	// Create test rule
	rule := gwtypes.HTTPRouteRule{
		Matches: []gatewayv1.HTTPRouteMatch{
			{Path: &gatewayv1.HTTPPathMatch{Type: &[]gatewayv1.PathMatchType{gatewayv1.PathMatchPathPrefix}[0], Value: &[]string{"/test"}[0]}},
		},
	}

	// Create parent reference
	pRef := &gwtypes.ParentReference{Name: "test-gateway"}

	// Create control plane reference
	cp := &commonv1alpha1.ControlPlaneRef{
		Type: commonv1alpha1.ControlPlaneRefKonnectNamespacedRef,
		KonnectNamespacedRef: &commonv1alpha1.KonnectNamespacedRef{
			Name: "test-cp",
		},
	}

	upstreamName := "test-upstream"
	serviceName := namegen.NewKongServiceName(httpRoute, cp, rule)

	tests := []struct {
		name               string
		existingService    *configurationv1alpha1.KongService
		expectedAnnotation string
		expectUpdate       bool
		expectedHost       string
	}{
		{
			name:               "new service creation",
			existingService:    nil,
			expectedAnnotation: "test-namespace/test-route",
			expectUpdate:       false,
			expectedHost:       upstreamName,
		},
		{
			name: "existing service with no annotation",
			existingService: &configurationv1alpha1.KongService{
				ObjectMeta: metav1.ObjectMeta{
					Name:      serviceName,
					Namespace: "test-namespace",
				},
			},
			expectedAnnotation: "test-namespace/test-route",
			expectUpdate:       true,
			expectedHost:       upstreamName,
		},
		{
			name: "existing service with different route annotation",
			existingService: &configurationv1alpha1.KongService{
				ObjectMeta: metav1.ObjectMeta{
					Name:      serviceName,
					Namespace: "test-namespace",
					Annotations: map[string]string{
						consts.GatewayOperatorHybridRoutesAnnotation: "other-namespace/other-route",
					},
				},
			},
			expectedAnnotation: "other-namespace/other-route,test-namespace/test-route",
			expectUpdate:       true,
			expectedHost:       upstreamName,
		},
		{
			name: "existing service with same route annotation",
			existingService: &configurationv1alpha1.KongService{
				ObjectMeta: metav1.ObjectMeta{
					Name:      serviceName,
					Namespace: "test-namespace",
					Annotations: map[string]string{
						consts.GatewayOperatorHybridRoutesAnnotation: "test-namespace/test-route",
					},
				},
			},
			expectedAnnotation: "test-namespace/test-route",
			expectUpdate:       false,
			expectedHost:       upstreamName,
		},
		{
			name: "existing service with multiple routes",
			existingService: &configurationv1alpha1.KongService{
				ObjectMeta: metav1.ObjectMeta{
					Name:      serviceName,
					Namespace: "test-namespace",
					Annotations: map[string]string{
						consts.GatewayOperatorHybridRoutesAnnotation: "ns1/route1,ns2/route2",
					},
				},
			},
			expectedAnnotation: "ns1/route1,ns2/route2,test-namespace/test-route",
			expectUpdate:       true,
			expectedHost:       upstreamName,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Create client with or without existing service
			var objects []client.Object
			if tt.existingService != nil {
				objects = append(objects, tt.existingService)
			}

			cl := fake.NewClientBuilder().
				WithScheme(scheme).
				WithObjects(objects...).
				Build()

			service, err := ServiceForRule(ctx, logger, cl, httpRoute, rule, pRef, cp, upstreamName)

			assert.NoError(t, err)
			assert.NotNil(t, service)
			assert.NotEmpty(t, service.Name) // Name is generated by namegen
			assert.Equal(t, "test-namespace", service.Namespace)
			assert.Equal(t, tt.expectedHost, service.Spec.Host)

			// Check annotation
			annotations := service.GetAnnotations()
			assert.NotNil(t, annotations)
			assert.Equal(t, tt.expectedAnnotation, annotations[consts.GatewayOperatorHybridRoutesAnnotation])
		})
	}
}
