// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kong/kong-operator/v2/api/common/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// KonnectConfigStore is the Schema for the konnectconfigstores API.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories=konnect;kong
// +kubebuilder:printcolumn:name="ID",description="Konnect ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="Programmed",description="The Resource is Programmed on Konnect",type=string,JSONPath=`.status.conditions[?(@.type=='Programmed')].status`
// +kubebuilder:printcolumn:name="OrgID",description="Konnect Organization ID this resource belongs to.",type=string,JSONPath=`.status.organizationID`
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:storageversion
// +apireference:kgo:include
// +kong:channels=kong-operator
type KonnectConfigStore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +optional
	Spec KonnectConfigStoreSpec `json:"spec,omitzero"`

	// +optional
	Status KonnectConfigStoreStatus `json:"status,omitzero"`
}

// KonnectConfigStoreList contains a list of KonnectConfigStore.
//
// +kubebuilder:object:root=true
type KonnectConfigStoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []KonnectConfigStore `json:"items"`
}

// KonnectConfigStoreSpec defines the desired state of KonnectConfigStore.
type KonnectConfigStoreSpec struct {
	// ControlPlaneRef is the reference to the parent ControlPlane object.
	//
	// +required
	ControlPlaneRef commonv1alpha1.ObjectRef `json:"controlPlaneRef,omitzero"`

	// APISpec defines the desired state of the resource's API spec fields.
	//
	// +optional
	APISpec KonnectConfigStoreAPISpec `json:"apiSpec,omitzero"`
}

// KonnectConfigStoreAPISpec defines the API spec fields for KonnectConfigStore.
type KonnectConfigStoreAPISpec struct {
	//
	//
	// +optional
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=100
	Name string `json:"name,omitzero"`
}

// KonnectConfigStoreStatus defines the observed state of KonnectConfigStore.
type KonnectConfigStoreStatus struct {
	// Conditions represent the current state of the resource.
	//
	// +optional
	// +listType=map
	// +listMapKey=type
	// +patchStrategy=merge
	// +patchMergeKey=type
	// +kubebuilder:validation:MaxItems=8
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type" protobuf:"bytes,1,rep,name=conditions"`

	// Konnect contains the Konnect entity status.
	//
	// +optional
	KonnectEntityStatus `json:",inline"`

	// ControlPlaneID is the Konnect ID of the parent ControlPlane.
	//
	// +optional
	ControlPlaneID *KonnectEntityRef `json:"controlPlaneID,omitempty"`

	// ObservedGeneration is the most recent generation observed
	//
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitzero"`
}
