// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"fmt"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	commonv1alpha1 "github.com/kong/kong-operator/v2/api/common/v1alpha1"
)

// EventGatewayListenerPolicy is the Schema for the eventgatewaylistenerpolicys API.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories=konnect;kong
// +kubebuilder:printcolumn:name="ID",description="Konnect ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="Programmed",description="The Resource is Programmed on Konnect",type=string,JSONPath=`.status.conditions[?(@.type=='Programmed')].status`
// +kubebuilder:printcolumn:name="OrgID",description="Konnect Organization ID this resource belongs to.",type=string,JSONPath=`.status.organizationID`
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:storageversion
// +apireference:kgo:include
// +kong:channels=kong-operator
type EventGatewayListenerPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +optional
	Spec EventGatewayListenerPolicySpec `json:"spec,omitzero"`

	// +optional
	Status EventGatewayListenerPolicyStatus `json:"status,omitzero"`
}

// EventGatewayListenerPolicyList contains a list of EventGatewayListenerPolicy.
//
// +kubebuilder:object:root=true
type EventGatewayListenerPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []EventGatewayListenerPolicy `json:"items"`
}

// EventGatewayListenerPolicySpec defines the desired state of EventGatewayListenerPolicy.
type EventGatewayListenerPolicySpec struct {
	// EventGatewayListenerRef is the reference to the parent EventGatewayListener object.
	//
	// +required
	EventGatewayListenerRef commonv1alpha1.ObjectRef `json:"eventGatewayListenerRef,omitzero"`

	// APISpec defines the desired state of the resource's API spec fields.
	//
	// +optional
	APISpec EventGatewayListenerPolicyAPISpec `json:"apiSpec,omitzero"`
}

// EventGatewayListenerPolicyAPISpec defines the API spec fields for EventGatewayListenerPolicy.
type EventGatewayListenerPolicyAPISpec struct {
	// EventGatewayListenerPolicyConfig embeds the union type configuration.
	//
	// +optional
	*EventGatewayListenerPolicyConfig `json:",inline"`
}

// EventGatewayListenerPolicyStatus defines the observed state of EventGatewayListenerPolicy.
type EventGatewayListenerPolicyStatus struct {
	// Conditions represent the current state of the resource.
	//
	// +optional
	// +listType=map
	// +listMapKey=type
	// +patchStrategy=merge
	// +patchMergeKey=type
	// +kubebuilder:validation:MaxItems=8
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type" protobuf:"bytes,1,rep,name=conditions"`

	// Konnect contains the Konnect entity status.
	//
	// +optional
	KonnectEntityStatus `json:",inline"`

	// GatewayID is the Konnect ID of the parent Gateway.
	//
	// +optional
	GatewayID *KonnectEntityRef `json:"gatewayID,omitempty"`

	// EventGatewayListenerID is the Konnect ID of the parent EventGatewayListener.
	//
	// +optional
	EventGatewayListenerID *KonnectEntityRef `json:"eventgatewaylistenerID,omitempty"`

	// ObservedGeneration is the most recent generation observed
	//
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
}

// EventGatewayListenerPolicyConfig represents a union type for EventGatewayListenerPolicyConfig.
// Only one of the fields should be set based on the Type.
//
type EventGatewayListenerPolicyConfig struct {
	// Type designates the type of configuration.
	//
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:Enum=forwardToVirtualCluster;tlsServer
	Type EventGatewayListenerPolicyConfigType `json:"type,omitempty"`

	// ForwardToVirtualClust configuration.
	//
	// +optional
	ForwardToVirtualClust *ForwardToVirtualClusterPolicy `json:"forwardToVirtualCluster,omitempty"`
	// EventGatewayTLSListen configuration.
	//
	// +optional
	EventGatewayTLSListen *EventGatewayTLSListenerPolicy `json:"tlsServer,omitempty"`
}

// EventGatewayListenerPolicyConfigType represents the type of EventGatewayListenerPolicyConfig.
type EventGatewayListenerPolicyConfigType string

// EventGatewayListenerPolicyConfigType values.
const (
	EventGatewayListenerPolicyConfigTypeForwardToVirtualClust EventGatewayListenerPolicyConfigType = "forwardToVirtualCluster"
	EventGatewayListenerPolicyConfigTypeEventGatewayTLSListen EventGatewayListenerPolicyConfigType = "tlsServer"
)

// MarshalJSON implements json.Marshaler.
func (u EventGatewayListenerPolicyConfig) MarshalJSON() ([]byte, error) {
	m := map[string]json.RawMessage{}
	typeBytes, _ := json.Marshal(string(u.Type))
	m["type"] = typeBytes
	switch u.Type {
	case "forwardToVirtualCluster":
		if u.ForwardToVirtualClust != nil {
			raw, err := json.Marshal(u.ForwardToVirtualClust)
			if err != nil {
				return nil, fmt.Errorf("marshaling EventGatewayListenerPolicyConfig forward_to_virtual_cluster: %w", err)
			}
			m["forwardToVirtualCluster"] = raw
		}
	case "tlsServer":
		if u.EventGatewayTLSListen != nil {
			raw, err := json.Marshal(u.EventGatewayTLSListen)
			if err != nil {
				return nil, fmt.Errorf("marshaling EventGatewayListenerPolicyConfig tls_server: %w", err)
			}
			m["tlsServer"] = raw
		}
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements json.Unmarshaler.
func (u *EventGatewayListenerPolicyConfig) UnmarshalJSON(data []byte) error {
	if u == nil {
		return fmt.Errorf("unmarshaling EventGatewayListenerPolicyConfig: nil receiver")
	}
	var probe struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return err
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	u.Type = EventGatewayListenerPolicyConfigType(probe.Type)
	switch probe.Type {
	case "forwardToVirtualCluster":
		payload, ok := raw["forwardToVirtualCluster"]
		if !ok || len(payload) == 0 {
			return nil
		}
		var val ForwardToVirtualClusterPolicy
		if err := json.Unmarshal(payload, &val); err != nil {
			return fmt.Errorf("unmarshaling EventGatewayListenerPolicyConfig forward_to_virtual_cluster: %w", err)
		}
		u.ForwardToVirtualClust = &val
	case "tlsServer":
		payload, ok := raw["tlsServer"]
		if !ok || len(payload) == 0 {
			return nil
		}
		var val EventGatewayTLSListenerPolicy
		if err := json.Unmarshal(payload, &val); err != nil {
			return fmt.Errorf("unmarshaling EventGatewayListenerPolicyConfig tls_server: %w", err)
		}
		u.EventGatewayTLSListen = &val
	}
	return nil
}

// MarshalJSON implements json.Marshaler.
func (s *EventGatewayListenerPolicyAPISpec) MarshalJSON() ([]byte, error) {
	if s == nil {
		return []byte("null"), nil
	}
	if s.EventGatewayListenerPolicyConfig == nil {
		return []byte("{}"), nil
	}
	data, err := json.Marshal(s.EventGatewayListenerPolicyConfig)
	if err != nil {
		return nil, fmt.Errorf("marshaling EventGatewayListenerPolicyAPISpec: %w", err)
	}
	return data, nil
}


// UnmarshalJSON implements json.Unmarshaler.
func (s *EventGatewayListenerPolicyAPISpec) UnmarshalJSON(data []byte) error {
	if s == nil {
		return fmt.Errorf("unmarshaling EventGatewayListenerPolicyAPISpec: nil receiver")
	}
	type alias EventGatewayListenerPolicyAPISpec
	aux := alias{}
	aux.EventGatewayListenerPolicyConfig = &EventGatewayListenerPolicyConfig{}
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("unmarshaling EventGatewayListenerPolicyAPISpec: %w", err)
	}
	if aux.EventGatewayListenerPolicyConfig != nil && aux.EventGatewayListenerPolicyConfig.Type == "" && aux.EventGatewayListenerPolicyConfig.ForwardToVirtualClust == nil && aux.EventGatewayListenerPolicyConfig.EventGatewayTLSListen == nil {
		aux.EventGatewayListenerPolicyConfig = nil
	}
	*s = EventGatewayListenerPolicyAPISpec(aux)
	return nil
}

