// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"fmt"
	commonv1alpha1 "github.com/kong/kong-operator/v2/api/common/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PortalCustomDomain is the Schema for the portalcustomdomains API.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories=konnect;kong
// +kubebuilder:printcolumn:name="Programmed",description="The Resource is Programmed on Konnect",type=string,JSONPath=`.status.conditions[?(@.type=='Programmed')].status`
// +kubebuilder:printcolumn:name="OrgID",description="Konnect Organization ID this resource belongs to.",type=string,JSONPath=`.status.organizationID`
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:storageversion
// +apireference:kgo:include
// +kong:channels=kong-operator
type PortalCustomDomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +optional
	Spec PortalCustomDomainSpec `json:"spec,omitzero"`

	// +optional
	Status PortalCustomDomainStatus `json:"status,omitzero"`
}

// PortalCustomDomainList contains a list of PortalCustomDomain.
//
// +kubebuilder:object:root=true
type PortalCustomDomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []PortalCustomDomain `json:"items"`
}

// PortalCustomDomainSpec defines the desired state of PortalCustomDomain.
type PortalCustomDomainSpec struct {
	// PortalRef is the reference to the parent Portal object.
	//
	// +required
	PortalRef commonv1alpha1.ObjectRef `json:"portalRef,omitzero"`

	// APISpec defines the desired state of the resource's API spec fields.
	//
	// +optional
	APISpec PortalCustomDomainAPISpec `json:"apiSpec,omitzero"`
}

// PortalCustomDomainAPISpec defines the API spec fields for PortalCustomDomain.
type PortalCustomDomainAPISpec struct {
	//
	//
	// +required
	// +kubebuilder:validation:Enum=Enabled;Disabled
	Enabled string `json:"enabled,omitzero"`

	//
	//
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=253
	Hostname string `json:"hostname,omitzero"`

	//
	//
	// +required
	SSL *PortalCustomDomainSSL `json:"ssl,omitempty"`
}

// PortalCustomDomainStatus defines the observed state of PortalCustomDomain.
type PortalCustomDomainStatus struct {
	// Conditions represent the current state of the resource.
	//
	// +optional
	// +listType=map
	// +listMapKey=type
	// +patchStrategy=merge
	// +patchMergeKey=type
	// +kubebuilder:validation:MaxItems=8
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type" protobuf:"bytes,1,rep,name=conditions"`

	// Konnect contains the Konnect entity status.
	//
	// +optional
	KonnectEntityStatus `json:",inline"`

	// PortalID is the Konnect ID of the parent Portal.
	//
	// +optional
	PortalID *KonnectEntityRef `json:"portalID,omitempty"`

	// ObservedGeneration is the most recent generation observed
	//
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitzero"`
}

// PortalCustomDomainSSL represents a union type for ssl.
// Only one of the fields should be set based on the Type.
type PortalCustomDomainSSL struct {
	// Type designates the type of configuration.
	//
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:Enum=withCustomCertificate;standard
	Type PortalCustomDomainSSLType `json:"type,omitempty"`

	// WithCustomCertificate configuration.
	//
	// +optional
	WithCustomCertificate *CreatePortalCustomDomainSSLWithCustomCertificate `json:"withCustomCertificate,omitempty"`
	// Standard configuration.
	//
	// +optional
	Standard *CreatePortalCustomDomainSSLStandard `json:"standard,omitempty"`
}

// PortalCustomDomainSSLType represents the type of ssl.
type PortalCustomDomainSSLType string

// PortalCustomDomainSSLType values.
const (
	PortalCustomDomainSSLTypeWithCustomCertificate PortalCustomDomainSSLType = "withCustomCertificate"
	PortalCustomDomainSSLTypeStandard              PortalCustomDomainSSLType = "standard"
)

// MarshalJSON implements json.Marshaler.
func (u PortalCustomDomainSSL) MarshalJSON() ([]byte, error) {
	m := map[string]json.RawMessage{}
	typeBytes, err := json.Marshal(string(u.Type))
	if err != nil {
		return nil, fmt.Errorf("marshaling PortalCustomDomainSSL type: %w", err)
	}
	m["type"] = typeBytes
	switch u.Type {
	case PortalCustomDomainSSLTypeWithCustomCertificate:
		if u.WithCustomCertificate != nil {
			raw, err := json.Marshal(u.WithCustomCertificate)
			if err != nil {
				return nil, fmt.Errorf("marshaling PortalCustomDomainSSL WithCustomCertificate: %w", err)
			}
			m["withCustomCertificate"] = raw
		}
	case PortalCustomDomainSSLTypeStandard:
		if u.Standard != nil {
			raw, err := json.Marshal(u.Standard)
			if err != nil {
				return nil, fmt.Errorf("marshaling PortalCustomDomainSSL Standard: %w", err)
			}
			m["standard"] = raw
		}
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements json.Unmarshaler.
func (u *PortalCustomDomainSSL) UnmarshalJSON(data []byte) error {
	if u == nil {
		return fmt.Errorf("unmarshaling PortalCustomDomainSSL: nil receiver")
	}
	var probe struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return err
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	u.Type = PortalCustomDomainSSLType(probe.Type)
	switch probe.Type {
	case "withCustomCertificate":
		payload, ok := raw["withCustomCertificate"]
		if !ok || len(payload) == 0 {
			return nil
		}
		var val CreatePortalCustomDomainSSLWithCustomCertificate
		if err := json.Unmarshal(payload, &val); err != nil {
			return fmt.Errorf("unmarshaling PortalCustomDomainSSL WithCustomCertificate: %w", err)
		}
		u.WithCustomCertificate = &val
	case "standard":
		payload, ok := raw["standard"]
		if !ok || len(payload) == 0 {
			return nil
		}
		var val CreatePortalCustomDomainSSLStandard
		if err := json.Unmarshal(payload, &val); err != nil {
			return fmt.Errorf("unmarshaling PortalCustomDomainSSL Standard: %w", err)
		}
		u.Standard = &val
	}
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (s *PortalCustomDomainAPISpec) UnmarshalJSON(data []byte) error {
	if s == nil {
		return fmt.Errorf("unmarshaling PortalCustomDomainAPISpec: nil receiver")
	}
	type alias PortalCustomDomainAPISpec
	aux := alias{}
	aux.SSL = &PortalCustomDomainSSL{}
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("unmarshaling PortalCustomDomainAPISpec: %w", err)
	}
	if aux.SSL != nil && aux.SSL.Type == "" && aux.SSL.WithCustomCertificate == nil && aux.SSL.Standard == nil {
		aux.SSL = nil
	}
	*s = PortalCustomDomainAPISpec(aux)
	return nil
}
