// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"fmt"

	sdkkonnectcomp "github.com/Kong/sdk-konnect-go/models/components"
	sdkkonnectoper "github.com/Kong/sdk-konnect-go/models/operations"
)


type EventGatewayListenerPolicySDKOpsBoolField struct {
	Label string
	Path  []string
}

var EventGatewayListenerPolicySDKOpsBoolFields = []EventGatewayListenerPolicySDKOpsBoolField{
	{
		Label: "eventgatewaytlslisten.config.allow_plaintext",
		Path: []string{
			"eventgatewaytlslisten",
			"config",
			"allow_plaintext",
		},
	},
	{
		Label: "eventgatewaytlslisten.enabled",
		Path: []string{
			"eventgatewaytlslisten",
			"enabled",
		},
	},
	{
		Label: "forwardtovirtualclust.enabled",
		Path: []string{
			"forwardtovirtualclust",
			"enabled",
		},
	},
}

func normalizeEventGatewayListenerPolicySDKOpsBoolFields(payload map[string]any) error {
	for _, field := range EventGatewayListenerPolicySDKOpsBoolFields {
		if _, err := normalizeEventGatewayListenerPolicySDKOpsBoolField(payload, field.Path); err != nil {
			return fmt.Errorf("%s: %w", field.Label, err)
		}
	}
	return nil
}

func normalizeEventGatewayListenerPolicySDKOpsBoolField(value any, path []string) (any, error) {
	if len(path) == 0 {
		switch typed := value.(type) {
		case nil:
			return nil, nil
		case bool:
			return typed, nil
		case string:
			switch typed {
			case "Enabled":
				return true, nil
			case "Disabled":
				return false, nil
			default:
				return nil, fmt.Errorf("unexpected boolean enum %q", typed)
			}
		default:
			return nil, fmt.Errorf("expected string boolean enum, got %T", value)
		}
	}

	if value == nil {
		return nil, nil
	}

	segment := path[0]
	switch segment {
	case "[]":
		items, ok := value.([]any)
		if !ok {
			return nil, fmt.Errorf("expected array, got %T", value)
		}
		for i, item := range items {
			normalized, err := normalizeEventGatewayListenerPolicySDKOpsBoolField(item, path[1:])
			if err != nil {
				return nil, err
			}
			items[i] = normalized
		}
		return items, nil
	case "{}":
		object, ok := value.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("expected object, got %T", value)
		}
		for key, item := range object {
			normalized, err := normalizeEventGatewayListenerPolicySDKOpsBoolField(item, path[1:])
			if err != nil {
				return nil, err
			}
			object[key] = normalized
		}
		return object, nil
	default:
		object, ok := value.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("expected object, got %T", value)
		}
		child, ok := object[segment]
		if !ok {
			return value, nil
		}
		normalized, err := normalizeEventGatewayListenerPolicySDKOpsBoolField(child, path[1:])
		if err != nil {
			return nil, err
		}
		object[segment] = normalized
		return object, nil
	}
}

func (s *EventGatewayListenerPolicyAPISpec) marshalSDKOpsPayload() (map[string]any, error) {
	data, err := json.Marshal(s)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal EventGatewayListenerPolicyAPISpec: %w", err)
	}

	var payload map[string]any
	if err := json.Unmarshal(data, &payload); err != nil {
		return nil, fmt.Errorf("failed to decode EventGatewayListenerPolicyAPISpec: %w", err)
	}
	if err := normalizeEventGatewayListenerPolicySDKOpsBoolFields(payload); err != nil {
		return nil, fmt.Errorf("failed to normalize EventGatewayListenerPolicyAPISpec SDK payload: %w", err)
	}
	return payload, nil
}

func (s *EventGatewayListenerPolicyAPISpec) selectedSDKOpsPayload(payload map[string]any) ([]byte, string, error) {
	if s == nil || s.EventGatewayListenerPolicyConfig == nil {
		return nil, "", fmt.Errorf("EventGatewayListenerPolicy config is required")
	}

	var selected any
	var variant string
	switch s.EventGatewayListenerPolicyConfig.Type {
	case EventGatewayListenerPolicyConfigTypeEventGatewayTLSListen:
		selected = payload["eventgatewaytlslisten"]
		variant = "EventGatewayTLSListen"
	case EventGatewayListenerPolicyConfigTypeForwardToVirtualClust:
		selected = payload["forwardtovirtualclust"]
		variant = "ForwardToVirtualClust"
	default:
		return nil, "", fmt.Errorf("unsupported EventGatewayListenerPolicy config type %q", s.EventGatewayListenerPolicyConfig.Type)
	}

	if selected == nil {
		return nil, "", fmt.Errorf("EventGatewayListenerPolicy config payload missing for type %q", s.EventGatewayListenerPolicyConfig.Type)
	}

	data, err := json.Marshal(selected)
	if err != nil {
		return nil, "", fmt.Errorf("failed to marshal selected EventGatewayListenerPolicy config: %w", err)
	}
	return data, variant, nil
}

// ToCreateEventGatewayListenerPolicyRequest converts the EventGatewayListenerPolicyAPISpec to the SDK type
// sdkkonnectoper.CreateEventGatewayListenerPolicyRequest using JSON marshal/unmarshal.
// Fields that exist in the CRD spec but not in the SDK type (e.g., Kubernetes
// object references) are naturally excluded because they have different JSON names.
func (s *EventGatewayListenerPolicyAPISpec) ToCreateEventGatewayListenerPolicyRequest() (*sdkkonnectoper.CreateEventGatewayListenerPolicyRequest, error) {
	payload, err := s.marshalSDKOpsPayload()
	if err != nil {
		return nil, err
	}
	data, variant, err := s.selectedSDKOpsPayload(payload)
	if err != nil {
		return nil, err
	}
	
	switch variant {
	case "EventGatewayTLSListen":
		var member sdkkonnectcomp.EventGatewayTLSListenerPolicy
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into EventGatewayTLSListenerPolicy: %w", err)
		}
		body := sdkkonnectcomp.CreateEventGatewayListenerPolicyCreateTLSServer(member)
		return &sdkkonnectoper.CreateEventGatewayListenerPolicyRequest{
			EventGatewayListenerPolicyCreate: body,
		}, nil
	case "ForwardToVirtualClust":
		var member sdkkonnectcomp.ForwardToVirtualClusterPolicy
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into ForwardToVirtualClusterPolicy: %w", err)
		}
		body := sdkkonnectcomp.CreateEventGatewayListenerPolicyCreateForwardToVirtualCluster(member)
		return &sdkkonnectoper.CreateEventGatewayListenerPolicyRequest{
			EventGatewayListenerPolicyCreate: body,
		}, nil
	default:
		return nil, fmt.Errorf("unsupported EventGatewayListenerPolicy config variant %q", variant)
	}
}

// ToUpdateEventGatewayListenerPolicyRequest converts the EventGatewayListenerPolicyAPISpec to the SDK type
// sdkkonnectoper.UpdateEventGatewayListenerPolicyRequest using JSON marshal/unmarshal.
// Fields that exist in the CRD spec but not in the SDK type (e.g., Kubernetes
// object references) are naturally excluded because they have different JSON names.
func (s *EventGatewayListenerPolicyAPISpec) ToUpdateEventGatewayListenerPolicyRequest() (*sdkkonnectoper.UpdateEventGatewayListenerPolicyRequest, error) {
	payload, err := s.marshalSDKOpsPayload()
	if err != nil {
		return nil, err
	}
	data, variant, err := s.selectedSDKOpsPayload(payload)
	if err != nil {
		return nil, err
	}
	
	_ = variant
	var body sdkkonnectcomp.EventGatewayListenerPolicyUpdate
	if err := json.Unmarshal(data, &body); err != nil {
		return nil, fmt.Errorf("failed to unmarshal into EventGatewayListenerPolicyUpdate: %w", err)
	}
	return &sdkkonnectoper.UpdateEventGatewayListenerPolicyRequest{
		EventGatewayListenerPolicyUpdate: body,
	}, nil
}
