// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kong/kong-operator/v2/api/common/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PortalEmailConfig is the Schema for the portalemailconfigs API.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories=konnect;kong
// +kubebuilder:printcolumn:name="ID",description="Konnect ID",type="string",JSONPath=".status.id"
// +kubebuilder:printcolumn:name="Programmed",description="The Resource is Programmed on Konnect",type=string,JSONPath=`.status.conditions[?(@.type=='Programmed')].status`
// +kubebuilder:printcolumn:name="OrgID",description="Konnect Organization ID this resource belongs to.",type=string,JSONPath=`.status.organizationID`
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:storageversion
// +apireference:kgo:include
// +kong:channels=kong-operator
type PortalEmailConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +optional
	Spec PortalEmailConfigSpec `json:"spec,omitzero"`

	// +optional
	Status PortalEmailConfigStatus `json:"status,omitzero"`
}

// PortalEmailConfigList contains a list of PortalEmailConfig.
//
// +kubebuilder:object:root=true
type PortalEmailConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []PortalEmailConfig `json:"items"`
}

// PortalEmailConfigSpec defines the desired state of PortalEmailConfig.
type PortalEmailConfigSpec struct {
	// PortalRef is the reference to the parent Portal object.
	//
	// +required
	PortalRef commonv1alpha1.ObjectRef `json:"portalRef,omitzero"`

	// APISpec defines the desired state of the resource's API spec fields.
	//
	// +optional
	APISpec PortalEmailConfigAPISpec `json:"apiSpec,omitzero"`
}

// PortalEmailConfigAPISpec defines the API spec fields for PortalEmailConfig.
type PortalEmailConfigAPISpec struct {
	// The domain name to use for sending emails. Null means default.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=253
	DomainName *string `json:"domainName,omitempty"`

	// The email address to use in the 'From' field.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=253
	FromEmail *string `json:"fromEmail,omitempty"`

	// The name to display in the 'From' field of emails.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=253
	FromName *string `json:"fromName,omitempty"`

	// The email address to use in the 'Reply-To' field.
	// 'Reply-To' header is omitted if omitted or null.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=253
	ReplyToEmail *string `json:"replyToEmail,omitempty"`
}

// PortalEmailConfigStatus defines the observed state of PortalEmailConfig.
type PortalEmailConfigStatus struct {
	// Conditions represent the current state of the resource.
	//
	// +optional
	// +listType=map
	// +listMapKey=type
	// +patchStrategy=merge
	// +patchMergeKey=type
	// +kubebuilder:validation:MaxItems=8
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type" protobuf:"bytes,1,rep,name=conditions"`

	// Konnect contains the Konnect entity status.
	//
	// +optional
	KonnectEntityStatus `json:",inline"`

	// PortalID is the Konnect ID of the parent Portal.
	//
	// +optional
	PortalID *KonnectEntityRef `json:"portalID,omitempty"`

	// ObservedGeneration is the most recent generation observed
	//
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitzero"`
}
