// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"fmt"

	sdkkonnectcomp "github.com/Kong/sdk-konnect-go/models/components"
)

// AIGatewayPolicySDKOpsBoolField describes a boolean enum field that must be normalized for SDK payloads.
type AIGatewayPolicySDKOpsBoolField struct {
	Label string
	Path  []string
}

// AIGatewayPolicySDKOpsBoolFields lists all boolean enum fields that must be normalized for SDK payloads.
var AIGatewayPolicySDKOpsBoolFields = []AIGatewayPolicySDKOpsBoolField{
	{
		Label: "enabled",
		Path: []string{
			"enabled",
		},
	},
	{
		Label: "global",
		Path: []string{
			"global",
		},
	},
}

func normalizeAIGatewayPolicySDKOpsBoolFields(payload map[string]any) error {
	for _, field := range AIGatewayPolicySDKOpsBoolFields {
		if _, err := normalizeAIGatewayPolicySDKOpsBoolField(payload, field.Path); err != nil {
			return fmt.Errorf("%s: %w", field.Label, err)
		}
	}
	return nil
}

func normalizeAIGatewayPolicySDKOpsBoolField(value any, path []string) (any, error) {
	if len(path) == 0 {
		switch typed := value.(type) {
		case nil:
			return nil, nil
		case bool:
			return typed, nil
		case string:
			switch typed {
			case "Enabled":
				return true, nil
			case "Disabled":
				return false, nil
			default:
				return nil, fmt.Errorf("unexpected boolean enum %q", typed)
			}
		default:
			return nil, fmt.Errorf("expected string boolean enum, got %T", value)
		}
	}

	if value == nil {
		return nil, nil
	}

	segment := path[0]
	switch segment {
	case "[]":
		items, ok := value.([]any)
		if !ok {
			return nil, fmt.Errorf("expected array, got %T", value)
		}
		for i, item := range items {
			normalized, err := normalizeAIGatewayPolicySDKOpsBoolField(item, path[1:])
			if err != nil {
				return nil, err
			}
			items[i] = normalized
		}
		return items, nil
	case "{}":
		object, ok := value.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("expected object, got %T", value)
		}
		for key, item := range object {
			normalized, err := normalizeAIGatewayPolicySDKOpsBoolField(item, path[1:])
			if err != nil {
				return nil, err
			}
			object[key] = normalized
		}
		return object, nil
	default:
		object, ok := value.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("expected object, got %T", value)
		}
		child, ok := object[segment]
		if !ok {
			return value, nil
		}
		normalized, err := normalizeAIGatewayPolicySDKOpsBoolField(child, path[1:])
		if err != nil {
			return nil, err
		}
		object[segment] = normalized
		return object, nil
	}
}

func (s *AIGatewayPolicyAPISpec) marshalSDKOpsPayload() ([]byte, error) {
	data, err := json.Marshal(s)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal AIGatewayPolicyAPISpec: %w", err)
	}
	var payload any
	if err := json.Unmarshal(data, &payload); err != nil {
		return nil, fmt.Errorf("failed to decode AIGatewayPolicyAPISpec: %w", err)
	}
	payload = flattenSDKUnions(payload)
	// Convert camelCase CRD wire-format keys and discriminator values to
	// snake_case for the Konnect SDK request types.
	payload = renameKeysToSDK(payload)
	if pm, ok := payload.(map[string]any); ok {
		if err := normalizeAIGatewayPolicySDKOpsBoolFields(pm); err != nil {
			return nil, fmt.Errorf("failed to normalize AIGatewayPolicyAPISpec SDK payload: %w", err)
		}
	}
	data, err = json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal normalized AIGatewayPolicyAPISpec: %w", err)
	}
	return data, nil
}

// ToCreateAIGatewayPolicyRequest converts the AIGatewayPolicyAPISpec to the SDK type
// sdkkonnectcomp.CreateAIGatewayPolicyRequest using JSON marshal/unmarshal.
// Fields that exist in the CRD spec but not in the SDK type (e.g., Kubernetes
// object references) are naturally excluded because they have different JSON names.
func (s *AIGatewayPolicyAPISpec) ToCreateAIGatewayPolicyRequest() (*sdkkonnectcomp.CreateAIGatewayPolicyRequest, error) {
	data, err := s.marshalSDKOpsPayload()
	if err != nil {
		return nil, err
	}
	var target sdkkonnectcomp.CreateAIGatewayPolicyRequest
	if err := json.Unmarshal(data, &target); err != nil {
		return nil, fmt.Errorf("failed to unmarshal into CreateAIGatewayPolicyRequest: %w", err)
	}
	return &target, nil
}

// ToUpdateAIGatewayPolicyRequest converts the AIGatewayPolicyAPISpec to the SDK type
// sdkkonnectcomp.UpdateAIGatewayPolicyRequest using JSON marshal/unmarshal.
// Fields that exist in the CRD spec but not in the SDK type (e.g., Kubernetes
// object references) are naturally excluded because they have different JSON names.
func (s *AIGatewayPolicyAPISpec) ToUpdateAIGatewayPolicyRequest() (*sdkkonnectcomp.UpdateAIGatewayPolicyRequest, error) {
	data, err := s.marshalSDKOpsPayload()
	if err != nil {
		return nil, err
	}
	var target sdkkonnectcomp.UpdateAIGatewayPolicyRequest
	if err := json.Unmarshal(data, &target); err != nil {
		return nil, fmt.Errorf("failed to unmarshal into UpdateAIGatewayPolicyRequest: %w", err)
	}
	return &target, nil
}
