// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	konnectv1alpha2 "github.com/kong/kong-operator/v2/api/konnect/v1alpha2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	commonv1alpha1 "github.com/kong/kong-operator/v2/api/common/v1alpha1"
)

// GetKonnectStatus returns the Konnect status contained in the KonnectEventDataPlaneCertificate status.
func (obj *KonnectEventDataPlaneCertificate) GetKonnectStatus() *konnectv1alpha2.KonnectEntityStatus {
	return &obj.Status.KonnectEntityStatus
}

// SetKonnectID sets the Konnect ID in the KonnectEventDataPlaneCertificate status.
func (obj *KonnectEventDataPlaneCertificate) SetKonnectID(id string) {
	obj.Status.ID = id
}

// GetKonnectID returns the Konnect ID in the KonnectEventDataPlaneCertificate status.
func (obj *KonnectEventDataPlaneCertificate) GetKonnectID() string {
	return obj.Status.ID
}

// GetTypeName returns the KonnectEventDataPlaneCertificate Kind name.
func (obj KonnectEventDataPlaneCertificate) GetTypeName() string {
	return "KonnectEventDataPlaneCertificate"
}

// GetConditions returns the Status Conditions.
func (obj *KonnectEventDataPlaneCertificate) GetConditions() []metav1.Condition {
	return obj.Status.Conditions
}

// SetConditions sets the Status Conditions.
func (obj *KonnectEventDataPlaneCertificate) SetConditions(conditions []metav1.Condition) {
	obj.Status.Conditions = conditions
}

// GetGatewayID returns the Konnect ID of the parent Gateway.
func (obj *KonnectEventDataPlaneCertificate) GetGatewayID() string {
	if obj.Status.GatewayID == nil {
		return ""
	}
	return obj.Status.GatewayID.ID
}

// SetGatewayID sets the Konnect ID of the parent Gateway.
func (obj *KonnectEventDataPlaneCertificate) SetGatewayID(id string) {
	if obj.Status.GatewayID == nil {
		obj.Status.GatewayID = &KonnectEntityRef{}
	}
	obj.Status.GatewayID.ID = id
}

// GetGatewayRef returns the reference to the root Gateway.
func (obj *KonnectEventDataPlaneCertificate) GetGatewayRef() commonv1alpha1.ObjectRef {
	return obj.Spec.GatewayRef
}

// GetEventGatewayRef returns the reference to the root EventGateway.
func (obj *KonnectEventDataPlaneCertificate) GetEventGatewayRef() commonv1alpha1.ObjectRef {
	return obj.Spec.GatewayRef
}
