// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"fmt"

	sdkkonnectcomp "github.com/Kong/sdk-konnect-go/models/components"
)

func (s *AIGatewayProviderAPISpec) marshalSDKOpsPayload() (map[string]any, error) {
	data, err := json.Marshal(s)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal AIGatewayProviderAPISpec: %w", err)
	}

	var rawPayload any
	if err := json.Unmarshal(data, &rawPayload); err != nil {
		return nil, fmt.Errorf("failed to decode AIGatewayProviderAPISpec: %w", err)
	}
	// Convert camelCase CRD wire-format keys and discriminator values to
	// snake_case for the Konnect SDK request types.
	renamed := renameKeysToSDK(rawPayload)
	payload, ok := renamed.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("failed to convert AIGatewayProviderAPISpec SDK payload to map")
	}
	return payload, nil
}

func (s *AIGatewayProviderAPISpec) selectedSDKOpsPayload(payload map[string]any) ([]byte, string, error) {
	if s == nil || s.AIGatewayProviderConfig == nil {
		return nil, "", fmt.Errorf("AIGatewayProvider config is required")
	}

	var selected any
	var variant string
	switch s.AIGatewayProviderConfig.Type {
	case AIGatewayProviderConfigTypeAnthropic:
		selected = payload["anthropic"]
		variant = "Anthropic"
	case AIGatewayProviderConfigTypeAzure:
		selected = payload["azure"]
		variant = "Azure"
	case AIGatewayProviderConfigTypeBedrock:
		selected = payload["bedrock"]
		variant = "Bedrock"
	case AIGatewayProviderConfigTypeCerebras:
		selected = payload["cerebras"]
		variant = "Cerebras"
	case AIGatewayProviderConfigTypeCohere:
		selected = payload["cohere"]
		variant = "Cohere"
	case AIGatewayProviderConfigTypeDashscope:
		selected = payload["dashscope"]
		variant = "Dashscope"
	case AIGatewayProviderConfigTypeDatabricks:
		selected = payload["databricks"]
		variant = "Databricks"
	case AIGatewayProviderConfigTypeDeepseek:
		selected = payload["deepseek"]
		variant = "Deepseek"
	case AIGatewayProviderConfigTypeGemini:
		selected = payload["gemini"]
		variant = "Gemini"
	case AIGatewayProviderConfigTypeHuggingface:
		selected = payload["huggingface"]
		variant = "Huggingface"
	case AIGatewayProviderConfigTypeKimi:
		selected = payload["kimi"]
		variant = "Kimi"
	case AIGatewayProviderConfigTypeLlama2:
		selected = payload["llama2"]
		variant = "Llama2"
	case AIGatewayProviderConfigTypeMistral:
		selected = payload["mistral"]
		variant = "Mistral"
	case AIGatewayProviderConfigTypeOllama:
		selected = payload["ollama"]
		variant = "Ollama"
	case AIGatewayProviderConfigTypeOpenai:
		selected = payload["openai"]
		variant = "Openai"
	case AIGatewayProviderConfigTypeVercel:
		selected = payload["vercel"]
		variant = "Vercel"
	case AIGatewayProviderConfigTypeVllm:
		selected = payload["vllm"]
		variant = "Vllm"
	case AIGatewayProviderConfigTypeXai:
		selected = payload["xai"]
		variant = "Xai"
	case AIGatewayProviderConfigTypeVertex:
		selected = payload["vertex"]
		variant = "Vertex"
	default:
		return nil, "", fmt.Errorf("unsupported AIGatewayProvider config type %q", s.AIGatewayProviderConfig.Type)
	}

	if selected == nil {
		return nil, "", fmt.Errorf("AIGatewayProvider config payload missing for type %q", s.AIGatewayProviderConfig.Type)
	}
	selected = flattenSDKUnions(selected)
	if selectedMap, ok := selected.(map[string]any); ok {
		if typeValue, ok := payload["type"]; ok {
			if _, hasType := selectedMap["type"]; !hasType {
				withType := make(map[string]any)
				for key, value := range selectedMap {
					withType[key] = value
				}
				withType["type"] = typeValue
				selected = withType
			}
		}
	}

	data, err := json.Marshal(selected)
	if err != nil {
		return nil, "", fmt.Errorf("failed to marshal selected AIGatewayProvider config: %w", err)
	}
	return data, variant, nil
}

// ToCreateAIGatewayProviderRequest converts the AIGatewayProviderAPISpec to the SDK type
// sdkkonnectcomp.CreateAIGatewayProviderRequest using JSON marshal/unmarshal.
// Fields that exist in the CRD spec but not in the SDK type (e.g., Kubernetes
// object references) are naturally excluded because they have different JSON names.
func (s *AIGatewayProviderAPISpec) ToCreateAIGatewayProviderRequest() (*sdkkonnectcomp.CreateAIGatewayProviderRequest, error) {
	payload, err := s.marshalSDKOpsPayload()
	if err != nil {
		return nil, err
	}
	data, variant, err := s.selectedSDKOpsPayload(payload)
	if err != nil {
		return nil, err
	}
	
	switch variant {
	case "Anthropic":
		var member sdkkonnectcomp.AIGatewayProviderAnthropic
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderAnthropic: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestAnthropic(member)
		return &target, nil
	case "Azure":
		var member sdkkonnectcomp.AIGatewayProviderAzure
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderAzure: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestAzure(member)
		return &target, nil
	case "Bedrock":
		var member sdkkonnectcomp.AIGatewayProviderBedrock
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderBedrock: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestBedrock(member)
		return &target, nil
	case "Cerebras":
		var member sdkkonnectcomp.AIGatewayProviderCerebras
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderCerebras: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestCerebras(member)
		return &target, nil
	case "Cohere":
		var member sdkkonnectcomp.AIGatewayProviderCohere
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderCohere: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestCohere(member)
		return &target, nil
	case "Dashscope":
		var member sdkkonnectcomp.AIGatewayProviderDashscope
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderDashscope: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestDashscope(member)
		return &target, nil
	case "Databricks":
		var member sdkkonnectcomp.AIGatewayProviderDatabricks
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderDatabricks: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestDatabricks(member)
		return &target, nil
	case "Deepseek":
		var member sdkkonnectcomp.AIGatewayProviderDeepseek
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderDeepseek: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestDeepseek(member)
		return &target, nil
	case "Gemini":
		var member sdkkonnectcomp.AIGatewayProviderGemini
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderGemini: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestGemini(member)
		return &target, nil
	case "Huggingface":
		var member sdkkonnectcomp.AIGatewayProviderHuggingface
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderHuggingface: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestHuggingface(member)
		return &target, nil
	case "Kimi":
		var member sdkkonnectcomp.AIGatewayProviderKimi
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderKimi: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestKimi(member)
		return &target, nil
	case "Llama2":
		var member sdkkonnectcomp.AIGatewayProviderLlama2
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderLlama2: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestLlama2(member)
		return &target, nil
	case "Mistral":
		var member sdkkonnectcomp.AIGatewayProviderMistral
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderMistral: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestMistral(member)
		return &target, nil
	case "Ollama":
		var member sdkkonnectcomp.AIGatewayProviderOllama
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderOllama: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestOllama(member)
		return &target, nil
	case "Openai":
		var member sdkkonnectcomp.AIGatewayProviderOpenai
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderOpenai: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestOpenai(member)
		return &target, nil
	case "Vercel":
		var member sdkkonnectcomp.AIGatewayProviderVercel
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderVercel: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestVercel(member)
		return &target, nil
	case "Vllm":
		var member sdkkonnectcomp.AIGatewayProviderVllm
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderVllm: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestVllm(member)
		return &target, nil
	case "Xai":
		var member sdkkonnectcomp.AIGatewayProviderXai
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderXai: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestXai(member)
		return &target, nil
	case "Vertex":
		var member sdkkonnectcomp.AIGatewayProviderVertex
		if err := json.Unmarshal(data, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayProviderVertex: %w", err)
		}
		target := sdkkonnectcomp.CreateCreateAIGatewayProviderRequestVertex(member)
		return &target, nil
	default:
		return nil, fmt.Errorf("unsupported AIGatewayProvider config variant %q", variant)
	}
}

// ToUpdateAIGatewayProviderRequest converts the AIGatewayProviderAPISpec to the SDK type
// sdkkonnectcomp.UpdateAIGatewayProviderRequest using JSON marshal/unmarshal.
// Fields that exist in the CRD spec but not in the SDK type (e.g., Kubernetes
// object references) are naturally excluded because they have different JSON names.
func (s *AIGatewayProviderAPISpec) ToUpdateAIGatewayProviderRequest() (*sdkkonnectcomp.UpdateAIGatewayProviderRequest, error) {
	payload, err := s.marshalSDKOpsPayload()
	if err != nil {
		return nil, err
	}
	data, variant, err := s.selectedSDKOpsPayload(payload)
	if err != nil {
		return nil, err
	}
	
	var selected map[string]any
	if err := json.Unmarshal(data, &selected); err != nil {
		return nil, fmt.Errorf("failed to decode selected AIGatewayProvider config: %w", err)
	}
	var target sdkkonnectcomp.UpdateAIGatewayProviderRequest
	if err := json.Unmarshal(data, &target); err != nil {
		return nil, fmt.Errorf("failed to unmarshal into UpdateAIGatewayProviderRequest: %w", err)
	}
	switch variant {
	case "Anthropic":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Azure":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Bedrock":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Cerebras":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Cohere":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Dashscope":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Databricks":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Deepseek":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Gemini":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Huggingface":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Kimi":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Llama2":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Mistral":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Ollama":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Openai":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Vercel":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Vllm":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Xai":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	case "Vertex":
		configPayload, ok := selected["name"]
		if !ok || configPayload == nil {
			return nil, fmt.Errorf("AIGatewayProvider config payload missing name")
		}
		configData, err := json.Marshal(configPayload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal AIGatewayProvider name payload: %w", err)
		}
		var member sdkkonnectcomp.AIGatewayEntityIdentifier
		if err := json.Unmarshal(configData, &member); err != nil {
			return nil, fmt.Errorf("failed to unmarshal into AIGatewayEntityIdentifier: %w", err)
		}
		unionValue := sdkkonnectcomp.CreateNameAIGatewayEntityIdentifier(member)
		target.Name = &unionValue
		return &target, nil
	default:
		return nil, fmt.Errorf("unsupported AIGatewayProvider config variant %q", variant)
	}
}
