// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestPortalIdentityProviderRequestAPISpec_ToPortalCreateIdentityProvider(t *testing.T) {
	spec := &PortalIdentityProviderRequestAPISpec{
		Enabled: "Enabled",
		Type:    IdentityProviderType("oidc"),
	}
	result, err := spec.ToPortalCreateIdentityProvider()
	require.NoError(t, err)
	require.NotNil(t, result)

	data, err := spec.marshalSDKOpsPayload()
	require.NoError(t, err)

	var payload map[string]any
	err = json.Unmarshal(data, &payload)
	require.NoError(t, err)
	require.Equal(t, true, payload["enabled"])
	require.Equal(t, "oidc", payload["type"])
}

func TestPortalIdentityProviderRequestAPISpec_ToPortalUpdateIdentityProvider(t *testing.T) {
	spec := &PortalIdentityProviderRequestAPISpec{
		Enabled: "Enabled",
		Type:    IdentityProviderType("oidc"),
	}
	result, err := spec.ToPortalUpdateIdentityProvider()
	require.NoError(t, err)
	require.NotNil(t, result)

	data, err := spec.marshalSDKOpsPayload()
	require.NoError(t, err)

	var payload map[string]any
	err = json.Unmarshal(data, &payload)
	require.NoError(t, err)
	require.Equal(t, true, payload["enabled"])
	require.Equal(t, "oidc", payload["type"])
}
