// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func addKnownTypesGenerated(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(GroupVersion,
		&AIGatewayAgent{},
		&AIGatewayAgentList{},
		&AIGatewayConsumer{},
		&AIGatewayConsumerList{},
		&AIGatewayConsumerCredential{},
		&AIGatewayConsumerCredentialList{},
		&AIGatewayControlPlane{},
		&AIGatewayControlPlaneList{},
		&AIGatewayModel{},
		&AIGatewayModelList{},
		&AIGatewayPolicy{},
		&AIGatewayPolicyList{},
		&AIGatewayProvider{},
		&AIGatewayProviderList{},
		&KonnectEventGateway{},
		&KonnectEventGatewayList{},
		&Portal{},
		&PortalList{},
		&PortalCustomDomain{},
		&PortalCustomDomainList{},
		&PortalCustomization{},
		&PortalCustomizationList{},
		&PortalEmailConfig{},
		&PortalEmailConfigList{},
		&PortalIPAllowList{},
		&PortalIPAllowListList{},
		&PortalIdentityProviderRequest{},
		&PortalIdentityProviderRequestList{},
		&PortalPage{},
		&PortalPageList{},
		&PortalTeam{},
		&PortalTeamList{},
	)

	metav1.AddToGroupVersion(scheme, GroupVersion)
	return nil
}
