package v1alpha1

// Code generated by scripts/apitypes-funcs/main.go; DO NOT EDIT.

// GetItems returns the list of KonnectGatewayControlPlane items.
func (obj KonnectGatewayControlPlaneList) GetItems() []KonnectGatewayControlPlane {
	return obj.Items
}

// GetItems returns the list of KonnectAPIAuthConfiguration items.
func (obj KonnectAPIAuthConfigurationList) GetItems() []KonnectAPIAuthConfiguration {
	return obj.Items
}

// GetItems returns the list of KonnectCloudGatewayNetwork items.
func (obj KonnectCloudGatewayNetworkList) GetItems() []KonnectCloudGatewayNetwork {
	return obj.Items
}

// GetItems returns the list of KonnectCloudGatewayDataPlaneGroupConfiguration items.
func (obj KonnectCloudGatewayDataPlaneGroupConfigurationList) GetItems() []KonnectCloudGatewayDataPlaneGroupConfiguration {
	return obj.Items
}

// GetItems returns the list of MCPServer items.
func (obj MCPServerList) GetItems() []MCPServer {
	return obj.Items
}

// GetItems returns the list of KonnectCloudGatewayTransitGateway items.
func (obj KonnectCloudGatewayTransitGatewayList) GetItems() []KonnectCloudGatewayTransitGateway {
	return obj.Items
}

// GetItems returns the list of PortalIdentityProviderRequest items.
func (obj PortalIdentityProviderRequestList) GetItems() []PortalIdentityProviderRequest {
	return obj.Items
}

// GetItems returns the list of KonnectEventDataPlaneCertificate items.
func (obj KonnectEventDataPlaneCertificateList) GetItems() []KonnectEventDataPlaneCertificate {
	return obj.Items
}

// GetItems returns the list of KonnectEventGateway items.
func (obj KonnectEventGatewayList) GetItems() []KonnectEventGateway {
	return obj.Items
}

// GetItems returns the list of Portal items.
func (obj PortalList) GetItems() []Portal {
	return obj.Items
}

// GetItems returns the list of PortalCustomDomain items.
func (obj PortalCustomDomainList) GetItems() []PortalCustomDomain {
	return obj.Items
}

// GetItems returns the list of PortalCustomization items.
func (obj PortalCustomizationList) GetItems() []PortalCustomization {
	return obj.Items
}

// GetItems returns the list of PortalEmailConfig items.
func (obj PortalEmailConfigList) GetItems() []PortalEmailConfig {
	return obj.Items
}

// GetItems returns the list of PortalIPAllowList items.
func (obj PortalIPAllowListList) GetItems() []PortalIPAllowList {
	return obj.Items
}

// GetItems returns the list of PortalPage items.
func (obj PortalPageList) GetItems() []PortalPage {
	return obj.Items
}

// GetItems returns the list of PortalTeam items.
func (obj PortalTeamList) GetItems() []PortalTeam {
	return obj.Items
}
