apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aigateway.konghq.com_aigatewaydataplanes.yaml
  - configuration.konghq.com_aigatewaydataplanecertificates.yaml
  - configuration.konghq.com_eventgatewaybackendclusters.yaml
  - configuration.konghq.com_eventgatewaydataplanecertificates.yaml
  - configuration.konghq.com_eventgatewaylistenerpolicies.yaml
  - configuration.konghq.com_eventgatewaylisteners.yaml
  - configuration.konghq.com_eventgatewayvirtualclusterconsumepolicies.yaml
  - configuration.konghq.com_eventgatewayvirtualclusterpolicies.yaml
  - configuration.konghq.com_eventgatewayvirtualclusterproducepolicies.yaml
  - configuration.konghq.com_eventgatewayvirtualclusters.yaml
  - configuration.konghq.com_ingressclassparameterses.yaml
  - configuration.konghq.com_kongcacertificates.yaml
  - configuration.konghq.com_kongcertificates.yaml
  - configuration.konghq.com_kongclusterplugins.yaml
  - configuration.konghq.com_kongconsumergroups.yaml
  - configuration.konghq.com_kongconsumers.yaml
  - configuration.konghq.com_kongcredentialacls.yaml
  - configuration.konghq.com_kongcredentialapikeys.yaml
  - configuration.konghq.com_kongcredentialbasicauths.yaml
  - configuration.konghq.com_kongcredentialhmacs.yaml
  - configuration.konghq.com_kongcredentialjwts.yaml
  - configuration.konghq.com_kongcustomentities.yaml
  - configuration.konghq.com_kongdataplaneclientcertificates.yaml
  - configuration.konghq.com_kongkeys.yaml
  - configuration.konghq.com_kongkeysets.yaml
  - configuration.konghq.com_konglicenses.yaml
  - configuration.konghq.com_kongpluginbindings.yaml
  - configuration.konghq.com_kongplugins.yaml
  - configuration.konghq.com_kongreferencegrants.yaml
  - configuration.konghq.com_kongroutes.yaml
  - configuration.konghq.com_kongservices.yaml
  - configuration.konghq.com_kongsnis.yaml
  - configuration.konghq.com_kongtargets.yaml
  - configuration.konghq.com_kongupstreampolicies.yaml
  - configuration.konghq.com_kongupstreams.yaml
  - configuration.konghq.com_kongvaults.yaml
  - eventgateway.konghq.com_kegdataplanes.yaml
  - gateway-operator.konghq.com_aigateways.yaml
  - gateway-operator.konghq.com_controlplanes.yaml
  - gateway-operator.konghq.com_dataplanemetricsextensions.yaml
  - gateway-operator.konghq.com_dataplanes.yaml
  - gateway-operator.konghq.com_gatewayconfigurations.yaml
  - gateway-operator.konghq.com_kongplugininstallations.yaml
  - gateway-operator.konghq.com_watchnamespacegrants.yaml
  - konnect.konghq.com_aigatewayagents.yaml
  - konnect.konghq.com_aigatewayconsumercredentials.yaml
  - konnect.konghq.com_aigatewayconsumers.yaml
  - konnect.konghq.com_aigatewaycontrolplanes.yaml
  - konnect.konghq.com_aigatewaymodelproviders.yaml
  - konnect.konghq.com_aigatewaymodels.yaml
  - konnect.konghq.com_aigatewaypolicies.yaml
  - konnect.konghq.com_konnectapiauthconfigurations.yaml
  - konnect.konghq.com_konnectcloudgatewaydataplanegroupconfigurations.yaml
  - konnect.konghq.com_konnectcloudgatewaynetworks.yaml
  - konnect.konghq.com_konnectcloudgatewaytransitgateways.yaml
  - konnect.konghq.com_konnecteventgateways.yaml
  - konnect.konghq.com_konnectextensions.yaml
  - konnect.konghq.com_konnectgatewaycontrolplanes.yaml
  - konnect.konghq.com_mcpservers.yaml
  - konnect.konghq.com_portalcustomdomains.yaml
  - konnect.konghq.com_portalcustomizations.yaml
  - konnect.konghq.com_portalemailconfigs.yaml
  - konnect.konghq.com_portalidentityproviderrequests.yaml
  - konnect.konghq.com_portalipallowlists.yaml
  - konnect.konghq.com_portalpages.yaml
  - konnect.konghq.com_portals.yaml
  - konnect.konghq.com_portalteams.yaml
