// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestAIGatewayCACertificateAPISpec_ToCreateAIGatewayCACertificateRequest(t *testing.T) {
	spec := &AIGatewayCACertificateAPISpec{
		Cert:      SensitiveDataSource{Type: SensitiveDataSourceTypeInline, Value: new("test-value")},
		Labels:    PublicLabels{"test-key": "test-value"},
		ManagedBy: ManagedBy{"test-key": "test-value"},
		Name:      AIGatewayEntityIdentifier("test-value"),
	}
	result, err := spec.ToCreateAIGatewayCACertificateRequest()
	require.NoError(t, err)
	require.NotNil(t, result)

	data, err := spec.marshalSDKOpsPayload()
	require.NoError(t, err)

	var payload map[string]any
	err = json.Unmarshal(data, &payload)
	require.NoError(t, err)
	require.Equal(t, "test-value", payload["cert"])
	require.Equal(t, map[string]any{"test-key": "test-value"}, payload["labels"])
	require.Equal(t, map[string]any{"test-key": "test-value"}, payload["managed_by"])
	require.Equal(t, "test-value", payload["name"])
}

func TestAIGatewayCACertificateAPISpec_ToUpdateAIGatewayCACertificateRequest(t *testing.T) {
	spec := &AIGatewayCACertificateAPISpec{
		Cert:      SensitiveDataSource{Type: SensitiveDataSourceTypeInline, Value: new("test-value")},
		Labels:    PublicLabels{"test-key": "test-value"},
		ManagedBy: ManagedBy{"test-key": "test-value"},
		Name:      AIGatewayEntityIdentifier("test-value"),
	}
	result, err := spec.ToUpdateAIGatewayCACertificateRequest()
	require.NoError(t, err)
	require.NotNil(t, result)

	data, err := spec.marshalSDKOpsPayload()
	require.NoError(t, err)

	var payload map[string]any
	err = json.Unmarshal(data, &payload)
	require.NoError(t, err)
	require.Equal(t, "test-value", payload["cert"])
	require.Equal(t, map[string]any{"test-key": "test-value"}, payload["labels"])
	require.Equal(t, map[string]any{"test-key": "test-value"}, payload["managed_by"])
	require.Equal(t, "test-value", payload["name"])
}
