// Code generated by CRD generation pipeline. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/kong/kong-operator/v2/api/common/v1alpha1"
)

const (
	// KonnectReferencesResolvedConditionType indicates whether all CR references
	// declared on the entity's spec have been resolved to Konnect IDs/names.
	KonnectReferencesResolvedConditionType = commonv1alpha1.KonnectReferencesResolvedConditionType

	// KonnectReferencesResolvedReasonResolved indicates all references resolved.
	KonnectReferencesResolvedReasonResolved = commonv1alpha1.KonnectReferencesResolvedReasonResolved
	// KonnectReferencesResolvedReasonNotFound indicates a referenced CR does not exist.
	KonnectReferencesResolvedReasonNotFound = commonv1alpha1.KonnectReferencesResolvedReasonNotFound
	// KonnectReferencesResolvedReasonNotProgrammed indicates a referenced CR exists
	// but has not been programmed in Konnect yet.
	KonnectReferencesResolvedReasonNotProgrammed = commonv1alpha1.KonnectReferencesResolvedReasonNotProgrammed
	// KonnectReferencesResolvedReasonInvalid indicates a reference is invalid
	// and cannot be resolved by waiting for the referenced CR to be programmed.
	KonnectReferencesResolvedReasonInvalid = commonv1alpha1.KonnectReferencesResolvedReasonInvalid
	// KonnectReferencesResolvedReasonNotPermitted indicates a cross-namespace
	// reference is not permitted by any KongReferenceGrant in the referenced
	// namespace.
	KonnectReferencesResolvedReasonNotPermitted = commonv1alpha1.KonnectReferencesResolvedReasonNotPermitted
	// KonnectReferencesResolvedReasonResolutionFailed indicates references failed
	// for multiple reasons. The condition message contains per-reference details.
	KonnectReferencesResolvedReasonResolutionFailed = commonv1alpha1.KonnectReferencesResolvedReasonResolutionFailed
)

// CrossNamespaceReferenceCheck describes one cross-namespace sibling
// reference (a ReferenceConfig entry with SupportCrossNamespaceReference:
// true whose target namespace differs from the referrer's) that must be
// authorized by a KongReferenceGrant before it is resolved. Entities that
// declare such references expose them via CrossNamespaceSiblingReferences,
// for callers outside this package to check against KongReferenceGrant
// before calling ResolveKonnectReferences.
type CrossNamespaceReferenceCheck = commonv1alpha1.CrossNamespaceReferenceCheck

// ReferenceNotFoundError is returned when a referenced CR does not exist.
type ReferenceNotFoundError = commonv1alpha1.ReferenceNotFoundError

// ReferenceNotProgrammedError is returned when a referenced CR exists but has
// no Konnect ID yet.
type ReferenceNotProgrammedError = commonv1alpha1.ReferenceNotProgrammedError

// ReferenceCrossNamespaceError is returned when a reference points to another
// namespace. Cross-namespace references are rejected until explicit
// cross-namespace support and authorization checks are implemented.
type ReferenceCrossNamespaceError = commonv1alpha1.ReferenceCrossNamespaceError

// ReferenceDifferentGatewayError is returned when a reference points to a CR
// programmed under a different AIGatewayControlPlane. References must stay
// within the same Konnect Gateway because Konnect only accepts policy and ACL
// references from the same AI Gateway.
type ReferenceDifferentGatewayError = commonv1alpha1.ReferenceDifferentGatewayError

// AIGatewayACLRef references an AIGatewayConsumerGroup in the cluster. The referenced
// object's Konnect name is used where the Konnect API accepts it.
type AIGatewayACLRef struct {
	// Kind is the kind of the referenced object.
	//
	// +optional
	// +kubebuilder:validation:Enum=AIGatewayConsumerGroup
	// +kubebuilder:default=AIGatewayConsumerGroup
	Kind string `json:"kind,omitempty"`

	// Name is the name of the referenced object.
	//
	// +required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Namespace, if set to a namespace other than the referrer's, must be
	// permitted by a KongReferenceGrant in that namespace.
	//
	// +optional
	Namespace string `json:"namespace,omitempty"`
}

// AIGatewayAuthStrategyRef references an AIGatewayAuthStrategy in the cluster. The referenced
// object's Konnect name is used where the Konnect API accepts it.
type AIGatewayAuthStrategyRef struct {
	// Kind is the kind of the referenced object.
	//
	// +optional
	// +kubebuilder:validation:Enum=AIGatewayAuthStrategy
	// +kubebuilder:default=AIGatewayAuthStrategy
	Kind string `json:"kind,omitempty"`

	// Name is the name of the referenced object.
	//
	// +required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Namespace is reserved for future cross-namespace support.
	//
	// +optional
	Namespace string `json:"namespace,omitempty"`
}

// AIGatewayModelProviderRef references an AIGatewayModelProvider in the cluster. The referenced
// object's Konnect name is used where the Konnect API accepts it.
type AIGatewayModelProviderRef struct {
	// Kind is the kind of the referenced object.
	//
	// +optional
	// +kubebuilder:validation:Enum=AIGatewayModelProvider
	// +kubebuilder:default=AIGatewayModelProvider
	Kind string `json:"kind,omitempty"`

	// Name is the name of the referenced object.
	//
	// +required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Namespace is reserved for future cross-namespace support.
	//
	// +optional
	Namespace string `json:"namespace,omitempty"`
}

// AIGatewayPolicyRef references an AIGatewayPolicy in the cluster. The referenced
// object's Konnect name is used where the Konnect API accepts it.
type AIGatewayPolicyRef struct {
	// Kind is the kind of the referenced object.
	//
	// +optional
	// +kubebuilder:validation:Enum=AIGatewayPolicy
	// +kubebuilder:default=AIGatewayPolicy
	Kind string `json:"kind,omitempty"`

	// Name is the name of the referenced object.
	//
	// +required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Namespace is reserved for future cross-namespace support.
	//
	// +optional
	Namespace string `json:"namespace,omitempty"`
}
