// Code generated by mockery. DO NOT EDIT.

package ops

import (
	context "context"

	components "github.com/Kong/sdk-konnect-go/models/components"

	mock "github.com/stretchr/testify/mock"

	operations "github.com/Kong/sdk-konnect-go/models/operations"
)

// MockControlPlaneGroupSDK is an autogenerated mock type for the ControlPlaneGroupSDK type
type MockControlPlaneGroupSDK struct {
	mock.Mock
}

type MockControlPlaneGroupSDK_Expecter struct {
	mock *mock.Mock
}

func (_m *MockControlPlaneGroupSDK) EXPECT() *MockControlPlaneGroupSDK_Expecter {
	return &MockControlPlaneGroupSDK_Expecter{mock: &_m.Mock}
}

// PutControlPlanesIDGroupMemberships provides a mock function with given fields: ctx, id, groupMembership, opts
func (_m *MockControlPlaneGroupSDK) PutControlPlanesIDGroupMemberships(ctx context.Context, id string, groupMembership *components.GroupMembership, opts ...operations.Option) (*operations.PutControlPlanesIDGroupMembershipsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id, groupMembership)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutControlPlanesIDGroupMemberships")
	}

	var r0 *operations.PutControlPlanesIDGroupMembershipsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *components.GroupMembership, ...operations.Option) (*operations.PutControlPlanesIDGroupMembershipsResponse, error)); ok {
		return rf(ctx, id, groupMembership, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *components.GroupMembership, ...operations.Option) *operations.PutControlPlanesIDGroupMembershipsResponse); ok {
		r0 = rf(ctx, id, groupMembership, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.PutControlPlanesIDGroupMembershipsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *components.GroupMembership, ...operations.Option) error); ok {
		r1 = rf(ctx, id, groupMembership, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockControlPlaneGroupSDK_PutControlPlanesIDGroupMemberships_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutControlPlanesIDGroupMemberships'
type MockControlPlaneGroupSDK_PutControlPlanesIDGroupMemberships_Call struct {
	*mock.Call
}

// PutControlPlanesIDGroupMemberships is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - groupMembership *components.GroupMembership
//   - opts ...operations.Option
func (_e *MockControlPlaneGroupSDK_Expecter) PutControlPlanesIDGroupMemberships(ctx interface{}, id interface{}, groupMembership interface{}, opts ...interface{}) *MockControlPlaneGroupSDK_PutControlPlanesIDGroupMemberships_Call {
	return &MockControlPlaneGroupSDK_PutControlPlanesIDGroupMemberships_Call{Call: _e.mock.On("PutControlPlanesIDGroupMemberships",
		append([]interface{}{ctx, id, groupMembership}, opts...)...)}
}

func (_c *MockControlPlaneGroupSDK_PutControlPlanesIDGroupMemberships_Call) Run(run func(ctx context.Context, id string, groupMembership *components.GroupMembership, opts ...operations.Option)) *MockControlPlaneGroupSDK_PutControlPlanesIDGroupMemberships_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]operations.Option, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(operations.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(*components.GroupMembership), variadicArgs...)
	})
	return _c
}

func (_c *MockControlPlaneGroupSDK_PutControlPlanesIDGroupMemberships_Call) Return(_a0 *operations.PutControlPlanesIDGroupMembershipsResponse, _a1 error) *MockControlPlaneGroupSDK_PutControlPlanesIDGroupMemberships_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockControlPlaneGroupSDK_PutControlPlanesIDGroupMemberships_Call) RunAndReturn(run func(context.Context, string, *components.GroupMembership, ...operations.Option) (*operations.PutControlPlanesIDGroupMembershipsResponse, error)) *MockControlPlaneGroupSDK_PutControlPlanesIDGroupMemberships_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockControlPlaneGroupSDK creates a new instance of MockControlPlaneGroupSDK. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockControlPlaneGroupSDK(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockControlPlaneGroupSDK {
	mock := &MockControlPlaneGroupSDK{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
