// Code generated by CRD generation pipeline. DO NOT EDIT.

package ops

import (
	"context"
	"fmt"

	sdkkonnectgo "github.com/Kong/sdk-konnect-go"
	sdkkonnectops "github.com/Kong/sdk-konnect-go/models/operations"

	configurationv1alpha1 "github.com/kong/kong-operator/v2/api/configuration/v1alpha1"
)

func createEventGatewayVirtualClusterPolicy(
	ctx context.Context,
	sdk sdkkonnectgo.EventGatewayVirtualClusterPoliciesSDK,
	obj *configurationv1alpha1.EventGatewayVirtualClusterPolicy,
) error {
	gatewayID := obj.GetGatewayID()
	if gatewayID == "" {
		return CantPerformOperationWithoutParentIDError{Entity: obj, Parent: "Gateway", Op: CreateOp}
	}
	virtualClusterID := obj.GetVirtualClusterID()
	if virtualClusterID == "" {
		return CantPerformOperationWithoutParentIDError{Entity: obj, Parent: "EventGatewayVirtualCluster", Op: CreateOp}
	}
	req, err := obj.Spec.APISpec.ToCreateEventGatewayVirtualClusterClusterLevelPolicyRequest()
	if err != nil {
		return fmt.Errorf("failed creating %s SDK request: %w", obj.GetTypeName(), err)
	}
	if req.EventGatewayClusterPolicyModify != nil && req.EventGatewayClusterPolicyModify.EventGatewayACLsPolicy != nil {
		req.EventGatewayClusterPolicyModify.EventGatewayACLsPolicy.Labels = WithKubernetesMetadataLabels(obj, req.EventGatewayClusterPolicyModify.EventGatewayACLsPolicy.Labels)
	}
	if req.EventGatewayClusterPolicyModify != nil && req.EventGatewayClusterPolicyModify.EventGatewayRequestRuleValidatorPolicy != nil {
		req.EventGatewayClusterPolicyModify.EventGatewayRequestRuleValidatorPolicy.Labels = WithKubernetesMetadataLabels(obj, req.EventGatewayClusterPolicyModify.EventGatewayRequestRuleValidatorPolicy.Labels)
	}
	req.GatewayID = gatewayID
	req.VirtualClusterID = virtualClusterID

	resp, err := sdk.CreateEventGatewayVirtualClusterClusterLevelPolicy(ctx, *req)
	if errWrap := wrapErrIfKonnectOpFailed(err, CreateOp, obj); errWrap != nil {
		return errWrap
	}
	if resp == nil || resp.EventGatewayPolicy == nil || resp.EventGatewayPolicy.ID == "" {
		return fmt.Errorf("failed creating %s: %w", obj.GetTypeName(), ErrNilResponse)
	}

	obj.SetKonnectID(resp.EventGatewayPolicy.ID)
	return nil
}

func updateEventGatewayVirtualClusterPolicy(
	ctx context.Context,
	sdk sdkkonnectgo.EventGatewayVirtualClusterPoliciesSDK,
	obj *configurationv1alpha1.EventGatewayVirtualClusterPolicy,
) error {
	gatewayID := obj.GetGatewayID()
	if gatewayID == "" {
		return CantPerformOperationWithoutParentIDError{Entity: obj, Parent: "Gateway", Op: UpdateOp}
	}
	virtualClusterID := obj.GetVirtualClusterID()
	if virtualClusterID == "" {
		return CantPerformOperationWithoutParentIDError{Entity: obj, Parent: "EventGatewayVirtualCluster", Op: UpdateOp}
	}
	id := obj.GetKonnectStatus().GetKonnectID()
	req, err := obj.Spec.APISpec.ToUpdateEventGatewayVirtualClusterClusterLevelPolicyRequest()
	if err != nil {
		return fmt.Errorf("failed building %s SDK update request: %w", obj.GetTypeName(), err)
	}
	if req.EventGatewayClusterPolicyModify != nil && req.EventGatewayClusterPolicyModify.EventGatewayACLsPolicy != nil {
		req.EventGatewayClusterPolicyModify.EventGatewayACLsPolicy.Labels = WithKubernetesMetadataLabels(obj, req.EventGatewayClusterPolicyModify.EventGatewayACLsPolicy.Labels)
	}
	if req.EventGatewayClusterPolicyModify != nil && req.EventGatewayClusterPolicyModify.EventGatewayRequestRuleValidatorPolicy != nil {
		req.EventGatewayClusterPolicyModify.EventGatewayRequestRuleValidatorPolicy.Labels = WithKubernetesMetadataLabels(obj, req.EventGatewayClusterPolicyModify.EventGatewayRequestRuleValidatorPolicy.Labels)
	}
	req.GatewayID = gatewayID
	req.VirtualClusterID = virtualClusterID
	req.PolicyID = id

	_, err = sdk.UpdateEventGatewayVirtualClusterClusterLevelPolicy(ctx, *req)
	if errWrap := wrapErrIfKonnectOpFailed(err, UpdateOp, obj); errWrap != nil {
		return handleUpdateError(ctx, err, obj, func(ctx context.Context) error {
			return createEventGatewayVirtualClusterPolicy(ctx, sdk, obj)
		})
	}
	return nil
}

func deleteEventGatewayVirtualClusterPolicy(
	ctx context.Context,
	sdk sdkkonnectgo.EventGatewayVirtualClusterPoliciesSDK,
	obj *configurationv1alpha1.EventGatewayVirtualClusterPolicy,
) error {
	gatewayID := obj.GetGatewayID()
	if gatewayID == "" {
		return CantPerformOperationWithoutParentIDError{Entity: obj, Parent: "Gateway", Op: DeleteOp}
	}
	virtualClusterID := obj.GetVirtualClusterID()
	if virtualClusterID == "" {
		return CantPerformOperationWithoutParentIDError{Entity: obj, Parent: "EventGatewayVirtualCluster", Op: DeleteOp}
	}
	id := obj.GetKonnectStatus().GetKonnectID()

	_, err := sdk.DeleteEventGatewayVirtualClusterClusterLevelPolicy(ctx, sdkkonnectops.DeleteEventGatewayVirtualClusterClusterLevelPolicyRequest{
		GatewayID:        gatewayID,
		VirtualClusterID: virtualClusterID,
		PolicyID:         id,
	})
	if errWrap := wrapErrIfKonnectOpFailed(err, DeleteOp, obj); errWrap != nil {
		return handleDeleteError(ctx, errWrap, obj)
	}
	return nil
}

func getEventGatewayVirtualClusterPolicyForUID(
	ctx context.Context,
	sdk sdkkonnectgo.EventGatewayVirtualClusterPoliciesSDK,
	obj *configurationv1alpha1.EventGatewayVirtualClusterPolicy,
) (string, error) {
	gatewayID := obj.GetGatewayID()
	if gatewayID == "" {
		return "", CantPerformOperationWithoutParentIDError{Entity: obj, Parent: "Gateway", Op: GetOp}
	}
	virtualClusterID := obj.GetVirtualClusterID()
	if virtualClusterID == "" {
		return "", CantPerformOperationWithoutParentIDError{Entity: obj, Parent: "EventGatewayVirtualCluster", Op: GetOp}
	}

	// Without a UID every unlabeled Konnect entity would match below.
	uid := string(obj.GetUID())
	if uid == "" {
		return "", EntityWithMatchingUIDNotFoundError{Entity: obj}
	}

	// TODO: pass a Filter to ListEventGatewayVirtualClusterClusterLevelPolicies (e.g. by name/labels) so we
	// do not page through every entity in the tenant. Filter types and
	// fields are entity-specific; derive from OpenAPI schema.
	resp, err := sdk.ListEventGatewayVirtualClusterClusterLevelPolicies(ctx, sdkkonnectops.ListEventGatewayVirtualClusterClusterLevelPoliciesRequest{
		GatewayID:        gatewayID,
		VirtualClusterID: virtualClusterID,
	})
	if err != nil {
		return "", fmt.Errorf("failed listing %s: %w", obj.GetTypeName(), err)
	}
	if resp == nil {
		return "", fmt.Errorf("failed listing %s: %w", obj.GetTypeName(), ErrNilResponse)
	}

	for _, entry := range resp.ListClusterPoliciesResponse {
		if entry.GetLabels()[KubernetesUIDLabelKey] != uid {
			continue
		}
		if entry.GetID() != "" {
			return entry.GetID(), nil
		}
	}

	return "", EntityWithMatchingUIDNotFoundError{Entity: obj}
}
