// Code generated by CRD generation pipeline. DO NOT EDIT.

package ops

import (
	"errors"
	"testing"
	sdkkonnectcomp "github.com/Kong/sdk-konnect-go/models/components"
	sdkkonnectops "github.com/Kong/sdk-konnect-go/models/operations"
	"github.com/Kong/sdk-konnect-go/test/mocks"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	konnectv1alpha1 "github.com/kong/kong-operator/v2/api/konnect/v1alpha1"
)

func testGeneratedAIGatewayControlPlaneForSDKOps() *konnectv1alpha1.AIGatewayControlPlane {
	return &konnectv1alpha1.AIGatewayControlPlane{
		TypeMeta: metav1.TypeMeta{
			APIVersion: konnectv1alpha1.GroupVersion.String(),
			Kind:       "AIGatewayControlPlane",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:       "aigatewaycontrolplane",
			Namespace:  "default",
			UID:        "aigatewaycontrolplane-uid",
			Generation: 3,
		},
		Spec: konnectv1alpha1.AIGatewayControlPlaneSpec{
			APISpec: konnectv1alpha1.AIGatewayControlPlaneAPISpec{
				Description: "test-value",
				DisplayName: "test-value",
				Labels: konnectv1alpha1.PublicLabels{"test-key": "test-value"},
				Name: "test-value",
			},
		},
	}
}

func TestCreateAIGatewayControlPlane_UsesSDKOpsConversion(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewaysSDK(t)
	obj := testGeneratedAIGatewayControlPlaneForSDKOps()
	expectedRequest, err := obj.Spec.APISpec.ToCreateAIGatewayRequest()
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	expectedID := "aigatewaycontrolplane-id"

	sdk.EXPECT().
		CreateAiGateway(
			mock.Anything,
			*expectedRequest,
		).
		Return(&sdkkonnectops.CreateAiGatewayResponse{
			AIGateway: &sdkkonnectcomp.AIGateway{
				ID: expectedID,
			},
		}, nil).
		Once()

	require.NoError(t, createAIGatewayControlPlane(ctx, sdk, obj))
	require.Equal(t, expectedID, obj.GetKonnectID())
}

func TestCreateAIGatewayControlPlane_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewaysSDK(t)
	obj := testGeneratedAIGatewayControlPlaneForSDKOps()
	expectedRequest, err := obj.Spec.APISpec.ToCreateAIGatewayRequest()
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		CreateAiGateway(
			mock.Anything,
			*expectedRequest,
		).
		Return(nil, sdkErr).
		Once()

	err = createAIGatewayControlPlane(ctx, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}

func TestUpdateAIGatewayControlPlane_UsesSDKOpsConversion(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewaysSDK(t)
	obj := testGeneratedAIGatewayControlPlaneForSDKOps()
	obj.SetKonnectID("aigatewaycontrolplane-id")
	expectedRequest, err := obj.Spec.APISpec.ToUpdateAIGatewayRequest()
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)

	sdk.EXPECT().
		UpdateAiGateway(
			mock.Anything,
			obj.GetKonnectStatus().GetKonnectID(),
			*expectedRequest,
		).
		Return(&sdkkonnectops.UpdateAiGatewayResponse{}, nil).
		Once()

	require.NoError(t, updateAIGatewayControlPlane(ctx, sdk, obj))
}

func TestUpdateAIGatewayControlPlane_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewaysSDK(t)
	obj := testGeneratedAIGatewayControlPlaneForSDKOps()
	obj.SetKonnectID("aigatewaycontrolplane-id")
	expectedRequest, err := obj.Spec.APISpec.ToUpdateAIGatewayRequest()
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		UpdateAiGateway(
			mock.Anything,
			obj.GetKonnectStatus().GetKonnectID(),
			*expectedRequest,
		).
		Return(nil, sdkErr).
		Once()

	err = updateAIGatewayControlPlane(ctx, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}

func TestDeleteAIGatewayControlPlane_UsesGeneratedSDKOps(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewaysSDK(t)
	obj := testGeneratedAIGatewayControlPlaneForSDKOps()
	obj.SetKonnectID("aigatewaycontrolplane-id")

	sdk.EXPECT().
		DeleteAiGateway(
			mock.Anything,
			obj.GetKonnectStatus().GetKonnectID(),
		).
		Return(&sdkkonnectops.DeleteAiGatewayResponse{}, nil).
		Once()

	require.NoError(t, deleteAIGatewayControlPlane(ctx, sdk, obj))
}

func TestDeleteAIGatewayControlPlane_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewaysSDK(t)
	obj := testGeneratedAIGatewayControlPlaneForSDKOps()
	obj.SetKonnectID("aigatewaycontrolplane-id")
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		DeleteAiGateway(
			mock.Anything,
			obj.GetKonnectStatus().GetKonnectID(),
		).
		Return(nil, sdkErr).
		Once()

	err := deleteAIGatewayControlPlane(ctx, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}