// Code generated by CRD generation pipeline. DO NOT EDIT.

package ops

import (
	"errors"
	sdkkonnectcomp "github.com/Kong/sdk-konnect-go/models/components"
	sdkkonnectops "github.com/Kong/sdk-konnect-go/models/operations"
	"github.com/Kong/sdk-konnect-go/test/mocks"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"testing"

	aiconfigurationv1alpha1 "github.com/kong/kong-operator/v2/api/aiconfiguration/v1alpha1"
	managerscheme "github.com/kong/kong-operator/v2/modules/manager/scheme"
)

func testGeneratedAIGatewayCACertificateForSDKOps() *aiconfigurationv1alpha1.AIGatewayCACertificate {
	return &aiconfigurationv1alpha1.AIGatewayCACertificate{
		TypeMeta: metav1.TypeMeta{
			APIVersion: aiconfigurationv1alpha1.GroupVersion.String(),
			Kind:       "AIGatewayCACertificate",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:       "aigatewaycacertificate",
			Namespace:  "default",
			UID:        "aigatewaycacertificate-uid",
			Generation: 3,
		},
		Spec: aiconfigurationv1alpha1.AIGatewayCACertificateSpec{
			APISpec: aiconfigurationv1alpha1.AIGatewayCACertificateAPISpec{
				Cert:      aiconfigurationv1alpha1.SensitiveDataSource{Type: aiconfigurationv1alpha1.SensitiveDataSourceTypeInline, Value: new("test-value")},
				Labels:    aiconfigurationv1alpha1.PublicLabels{"test-key": "test-value"},
				ManagedBy: aiconfigurationv1alpha1.ManagedBy{"test-key": "test-value"},
				Name:      "test-value",
			},
		},
	}
}

func TestCreateAIGatewayCACertificate_UsesSDKOpsConversion(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayCACertificatesSDK(t)
	cl := fake.NewClientBuilder().WithScheme(managerscheme.Get()).Build()
	obj := testGeneratedAIGatewayCACertificateForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	expectedRequest, err := obj.ToCreateAIGatewayCACertificateRequest(ctx, cl)
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	expectedID := "aigatewaycacertificate-id"

	sdk.EXPECT().
		CreateAiGatewayCaCertificate(
			mock.Anything,
			parentID,
			*expectedRequest,
		).
		Return(&sdkkonnectops.CreateAiGatewayCaCertificateResponse{
			AIGatewayCACertificate: &sdkkonnectcomp.AIGatewayCACertificate{
				ID: expectedID,
			},
		}, nil).
		Once()

	require.NoError(t, createAIGatewayCACertificate(ctx, cl, sdk, obj))
	require.Equal(t, expectedID, obj.GetKonnectID())
}

func TestCreateAIGatewayCACertificate_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayCACertificatesSDK(t)
	cl := fake.NewClientBuilder().WithScheme(managerscheme.Get()).Build()
	obj := testGeneratedAIGatewayCACertificateForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	expectedRequest, err := obj.ToCreateAIGatewayCACertificateRequest(ctx, cl)
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		CreateAiGatewayCaCertificate(
			mock.Anything,
			parentID,
			*expectedRequest,
		).
		Return(nil, sdkErr).
		Once()

	err = createAIGatewayCACertificate(ctx, cl, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}

func TestUpdateAIGatewayCACertificate_UsesSDKOpsConversion(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayCACertificatesSDK(t)
	cl := fake.NewClientBuilder().WithScheme(managerscheme.Get()).Build()
	obj := testGeneratedAIGatewayCACertificateForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("aigatewaycacertificate-id")
	expectedRequest, err := obj.ToUpdateAIGatewayCACertificateRequest(ctx, cl)
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)

	sdk.EXPECT().
		UpdateAiGatewayCaCertificate(
			mock.Anything,
			sdkkonnectops.UpdateAiGatewayCaCertificateRequest{
				GatewayID:                           parentID,
				CaCertificateIDOrName:               obj.GetKonnectStatus().GetKonnectID(),
				UpdateAIGatewayCACertificateRequest: *expectedRequest,
			},
		).
		Return(&sdkkonnectops.UpdateAiGatewayCaCertificateResponse{}, nil).
		Once()

	require.NoError(t, updateAIGatewayCACertificate(ctx, cl, sdk, obj))
}

func TestUpdateAIGatewayCACertificate_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayCACertificatesSDK(t)
	cl := fake.NewClientBuilder().WithScheme(managerscheme.Get()).Build()
	obj := testGeneratedAIGatewayCACertificateForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("aigatewaycacertificate-id")
	expectedRequest, err := obj.ToUpdateAIGatewayCACertificateRequest(ctx, cl)
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		UpdateAiGatewayCaCertificate(
			mock.Anything,
			sdkkonnectops.UpdateAiGatewayCaCertificateRequest{
				GatewayID:                           parentID,
				CaCertificateIDOrName:               obj.GetKonnectStatus().GetKonnectID(),
				UpdateAIGatewayCACertificateRequest: *expectedRequest,
			},
		).
		Return(nil, sdkErr).
		Once()

	err = updateAIGatewayCACertificate(ctx, cl, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}

func TestDeleteAIGatewayCACertificate_UsesGeneratedSDKOps(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayCACertificatesSDK(t)
	obj := testGeneratedAIGatewayCACertificateForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("aigatewaycacertificate-id")

	sdk.EXPECT().
		DeleteAiGatewayCaCertificate(
			mock.Anything,
			parentID,
			obj.GetKonnectStatus().GetKonnectID(),
		).
		Return(&sdkkonnectops.DeleteAiGatewayCaCertificateResponse{}, nil).
		Once()

	require.NoError(t, deleteAIGatewayCACertificate(ctx, sdk, obj))
}

func TestDeleteAIGatewayCACertificate_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayCACertificatesSDK(t)
	obj := testGeneratedAIGatewayCACertificateForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("aigatewaycacertificate-id")
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		DeleteAiGatewayCaCertificate(
			mock.Anything,
			parentID,
			obj.GetKonnectStatus().GetKonnectID(),
		).
		Return(nil, sdkErr).
		Once()

	err := deleteAIGatewayCACertificate(ctx, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}
