// Code generated by CRD generation pipeline. DO NOT EDIT.

package ops

import (
	"context"
	"fmt"

	sdkkonnectgo "github.com/Kong/sdk-konnect-go"
	sdkkonnectops "github.com/Kong/sdk-konnect-go/models/operations"

	konnectv1alpha1 "github.com/kong/kong-operator/v2/api/konnect/v1alpha1"
)

func createAIGatewayModel(
	ctx context.Context,
	sdk sdkkonnectgo.AIGatewayModelsSDK,
	obj *konnectv1alpha1.AIGatewayModel,
) error {
	parentID := obj.GetGatewayID()
	if parentID == "" {
		return CantPerformOperationWithoutParentIDError{Entity: obj, Parent: "AIGatewayControlPlane", Op: CreateOp}
	}
	req, err := obj.Spec.APISpec.ToCreateAIGatewayModelRequest()
	if err != nil {
		return fmt.Errorf("failed creating %s SDK request: %w", obj.GetTypeName(), err)
	}

	resp, err := sdk.CreateAiGatewayModel(ctx, parentID, *req)
	if errWrap := wrapErrIfKonnectOpFailed(err, CreateOp, obj); errWrap != nil {
		return errWrap
	}
	if resp == nil || resp.AIGatewayModel == nil {
		return fmt.Errorf("failed creating %s: %w", obj.GetTypeName(), ErrNilResponse)
	}

	var id string
	if id == "" && resp.AIGatewayModel.AIGatewayModelAIGatewayModelAPI != nil {
		switch extractedID := any(resp.AIGatewayModel.AIGatewayModelAIGatewayModelAPI.GetID()).(type) {
		case string:
			if extractedID != "" {
				id = extractedID
			}
		case *string:
			if extractedID != nil && *extractedID != "" {
				id = *extractedID
			}
		}
	}
	if id == "" && resp.AIGatewayModel.AIGatewayModelAIGatewayModelModel != nil {
		switch extractedID := any(resp.AIGatewayModel.AIGatewayModelAIGatewayModelModel.GetID()).(type) {
		case string:
			if extractedID != "" {
				id = extractedID
			}
		case *string:
			if extractedID != nil && *extractedID != "" {
				id = *extractedID
			}
		}
	}
	if id == "" {
		return fmt.Errorf("failed creating %s: %w", obj.GetTypeName(), ErrNilResponse)
	}

	obj.SetKonnectID(id)
	return nil
}

func updateAIGatewayModel(
	ctx context.Context,
	sdk sdkkonnectgo.AIGatewayModelsSDK,
	obj *konnectv1alpha1.AIGatewayModel,
) error {
	parentID := obj.GetGatewayID()
	if parentID == "" {
		return CantPerformOperationWithoutParentIDError{Entity: obj, Parent: "AIGatewayControlPlane", Op: UpdateOp}
	}
	id := obj.GetKonnectStatus().GetKonnectID()
	req, err := obj.Spec.APISpec.ToUpdateAIGatewayModelRequest()
	if err != nil {
		return fmt.Errorf("failed building %s SDK update request: %w", obj.GetTypeName(), err)
	}

	_, err = sdk.UpdateAiGatewayModel(ctx, sdkkonnectops.UpdateAiGatewayModelRequest{
		GatewayID: parentID,
		ModelIDOrName: id,
		UpdateAIGatewayModelRequest: *req,
	})
	if errWrap := wrapErrIfKonnectOpFailed(err, UpdateOp, obj); errWrap != nil {
		return handleUpdateError(ctx, err, obj, func(ctx context.Context) error {
			return createAIGatewayModel(ctx, sdk, obj)
		})
	}
	return nil
}

func deleteAIGatewayModel(
	ctx context.Context,
	sdk sdkkonnectgo.AIGatewayModelsSDK,
	obj *konnectv1alpha1.AIGatewayModel,
) error {
	parentID := obj.GetGatewayID()
	if parentID == "" {
		return CantPerformOperationWithoutParentIDError{Entity: obj, Parent: "AIGatewayControlPlane", Op: DeleteOp}
	}
	id := obj.GetKonnectStatus().GetKonnectID()

	_, err := sdk.DeleteAiGatewayModel(ctx, parentID, id)
	if errWrap := wrapErrIfKonnectOpFailed(err, DeleteOp, obj); errWrap != nil {
		return handleDeleteError(ctx, errWrap, obj)
	}
	return nil
}
