// Code generated by CRD generation pipeline. DO NOT EDIT.

package ops

import (
	"context"
	"fmt"
	"sigs.k8s.io/controller-runtime/pkg/client"

	konnectv1alpha1 "github.com/kong/kong-operator/v2/api/konnect/v1alpha1"
	"github.com/kong/kong-operator/v2/controller/konnect/constraints"
	sdkops "github.com/kong/kong-operator/v2/controller/konnect/ops/sdk"
)

// UpdateGeneratedOps dispatches update operations to per-entity generated
// update functions. It is a stub dispatcher intended for Konnect entities whose
// ops layer is fully generated; entities handled by hand-written ops remain in
// the Update function in ops.go.
func UpdateGeneratedOps[
	T constraints.SupportedKonnectEntityType,
	TEnt constraints.EntityType[T],
](
	ctx context.Context,
	sdk sdkops.SDKWrapper,
	cl client.Client,
	e TEnt,
) error {
	switch ent := any(e).(type) {
	case *konnectv1alpha1.EventGatewayBackendCluster:
		return updateEventGatewayBackendCluster(ctx, sdk.GetEventGatewayBackendClustersSDK(), ent)
	case *konnectv1alpha1.EventGatewayListener:
		return updateEventGatewayListener(ctx, sdk.GetEventGatewayListenersSDK(), ent)
	case *konnectv1alpha1.EventGatewayListenerPolicy:
		return updateEventGatewayListenerPolicy(ctx, sdk.GetEventGatewayListenerPoliciesSDK(), ent)
	case *konnectv1alpha1.EventGatewayVirtualCluster:
		return updateEventGatewayVirtualCluster(ctx, sdk.GetEventGatewayVirtualClustersSDK(), ent)
	case *konnectv1alpha1.IdentityProviderRequest:
		return updateIdentityProviderRequest(ctx, sdk.GetPortalAuthSettingsSDK(), ent)
	case *konnectv1alpha1.KonnectEventDataPlaneCertificate:
		return updateKonnectEventDataPlaneCertificate(ctx, cl, sdk.GetEventGatewayDataPlaneCertificatesSDK(), ent)
	case *konnectv1alpha1.KonnectEventGateway:
		return updateKonnectEventGateway(ctx, sdk.GetEventGatewaysSDK(), ent)
	case *konnectv1alpha1.Portal:
		return updatePortal(ctx, sdk.GetPortalsSDK(), ent)
	case *konnectv1alpha1.PortalEmailConfig:
		return updatePortalEmailConfig(ctx, sdk.GetPortalEmailsSDK(), ent)
	case *konnectv1alpha1.PortalIPAllowList:
		return updatePortalIPAllowList(ctx, sdk.GetPortalsIPAllowListSDK(), ent)
	case *konnectv1alpha1.PortalPage:
		return updatePortalPage(ctx, sdk.GetPortalPagesSDK(), ent)
	case *konnectv1alpha1.PortalTeam:
		return updatePortalTeam(ctx, sdk.GetPortalTeamsSDK(), ent)
	default:
		return fmt.Errorf("unsupported entity type %T", ent)
	}
}
