// Code generated by CRD generation pipeline. DO NOT EDIT.

package ops

import (
	"errors"
	sdkkonnectcomp "github.com/Kong/sdk-konnect-go/models/components"
	sdkkonnectops "github.com/Kong/sdk-konnect-go/models/operations"
	"github.com/Kong/sdk-konnect-go/test/mocks"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"testing"

	configurationv1alpha1 "github.com/kong/kong-operator/v2/api/configuration/v1alpha1"
	managerscheme "github.com/kong/kong-operator/v2/modules/manager/scheme"
)

func testGeneratedEventGatewayDataPlaneCertificateForSDKOps() *configurationv1alpha1.EventGatewayDataPlaneCertificate {
	return &configurationv1alpha1.EventGatewayDataPlaneCertificate{
		TypeMeta: metav1.TypeMeta{
			APIVersion: configurationv1alpha1.GroupVersion.String(),
			Kind:       "EventGatewayDataPlaneCertificate",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:       "eventgatewaydataplanecertificate",
			Namespace:  "default",
			UID:        "eventgatewaydataplanecertificate-uid",
			Generation: 3,
		},
		Spec: configurationv1alpha1.EventGatewayDataPlaneCertificateSpec{
			APISpec: configurationv1alpha1.EventGatewayDataPlaneCertificateAPISpec{
				Certificate: configurationv1alpha1.SensitiveDataSource{Type: configurationv1alpha1.SensitiveDataSourceTypeInline, Value: new("test-value")},
				Description: "test-value",
				Name:        "test-value",
			},
		},
	}
}

func TestCreateEventGatewayDataPlaneCertificate_UsesSDKOpsConversion(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockEventGatewayDataPlaneCertificatesSDK(t)
	cl := fake.NewClientBuilder().WithScheme(managerscheme.Get()).Build()
	obj := testGeneratedEventGatewayDataPlaneCertificateForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	expectedRequest, err := obj.ToCreateEventGatewayDataPlaneCertificateRequest(ctx, cl)
	require.NoError(t, err)
	expectedID := "eventgatewaydataplanecertificate-id"

	sdk.EXPECT().
		CreateEventGatewayDataPlaneCertificate(
			mock.Anything,
			parentID,
			expectedRequest,
		).
		Return(&sdkkonnectops.CreateEventGatewayDataPlaneCertificateResponse{
			EventGatewayDataPlaneCertificate: &sdkkonnectcomp.EventGatewayDataPlaneCertificate{
				ID: expectedID,
			},
		}, nil).
		Once()

	require.NoError(t, createEventGatewayDataPlaneCertificate(ctx, cl, sdk, obj))
	require.Equal(t, expectedID, obj.GetKonnectID())
}

func TestCreateEventGatewayDataPlaneCertificate_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockEventGatewayDataPlaneCertificatesSDK(t)
	cl := fake.NewClientBuilder().WithScheme(managerscheme.Get()).Build()
	obj := testGeneratedEventGatewayDataPlaneCertificateForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	expectedRequest, err := obj.ToCreateEventGatewayDataPlaneCertificateRequest(ctx, cl)
	require.NoError(t, err)
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		CreateEventGatewayDataPlaneCertificate(
			mock.Anything,
			parentID,
			expectedRequest,
		).
		Return(nil, sdkErr).
		Once()

	err = createEventGatewayDataPlaneCertificate(ctx, cl, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}

func TestUpdateEventGatewayDataPlaneCertificate_UsesSDKOpsConversion(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockEventGatewayDataPlaneCertificatesSDK(t)
	cl := fake.NewClientBuilder().WithScheme(managerscheme.Get()).Build()
	obj := testGeneratedEventGatewayDataPlaneCertificateForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("eventgatewaydataplanecertificate-id")
	expectedRequest, err := obj.ToUpdateEventGatewayDataPlaneCertificateRequest(ctx, cl)
	require.NoError(t, err)

	sdk.EXPECT().
		UpdateEventGatewayDataPlaneCertificate(
			mock.Anything,
			sdkkonnectops.UpdateEventGatewayDataPlaneCertificateRequest{
				GatewayID:     parentID,
				CertificateID: obj.GetKonnectStatus().GetKonnectID(),
				UpdateEventGatewayDataPlaneCertificateRequest: expectedRequest,
			},
		).
		Return(&sdkkonnectops.UpdateEventGatewayDataPlaneCertificateResponse{}, nil).
		Once()

	require.NoError(t, updateEventGatewayDataPlaneCertificate(ctx, cl, sdk, obj))
}

func TestUpdateEventGatewayDataPlaneCertificate_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockEventGatewayDataPlaneCertificatesSDK(t)
	cl := fake.NewClientBuilder().WithScheme(managerscheme.Get()).Build()
	obj := testGeneratedEventGatewayDataPlaneCertificateForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("eventgatewaydataplanecertificate-id")
	expectedRequest, err := obj.ToUpdateEventGatewayDataPlaneCertificateRequest(ctx, cl)
	require.NoError(t, err)
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		UpdateEventGatewayDataPlaneCertificate(
			mock.Anything,
			sdkkonnectops.UpdateEventGatewayDataPlaneCertificateRequest{
				GatewayID:     parentID,
				CertificateID: obj.GetKonnectStatus().GetKonnectID(),
				UpdateEventGatewayDataPlaneCertificateRequest: expectedRequest,
			},
		).
		Return(nil, sdkErr).
		Once()

	err = updateEventGatewayDataPlaneCertificate(ctx, cl, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}

func TestDeleteEventGatewayDataPlaneCertificate_UsesGeneratedSDKOps(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockEventGatewayDataPlaneCertificatesSDK(t)
	obj := testGeneratedEventGatewayDataPlaneCertificateForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("eventgatewaydataplanecertificate-id")

	sdk.EXPECT().
		DeleteEventGatewayDataPlaneCertificate(
			mock.Anything,
			parentID,
			obj.GetKonnectStatus().GetKonnectID(),
		).
		Return(&sdkkonnectops.DeleteEventGatewayDataPlaneCertificateResponse{}, nil).
		Once()

	require.NoError(t, deleteEventGatewayDataPlaneCertificate(ctx, sdk, obj))
}

func TestDeleteEventGatewayDataPlaneCertificate_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockEventGatewayDataPlaneCertificatesSDK(t)
	obj := testGeneratedEventGatewayDataPlaneCertificateForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("eventgatewaydataplanecertificate-id")
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		DeleteEventGatewayDataPlaneCertificate(
			mock.Anything,
			parentID,
			obj.GetKonnectStatus().GetKonnectID(),
		).
		Return(nil, sdkErr).
		Once()

	err := deleteEventGatewayDataPlaneCertificate(ctx, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}
