// Code generated by CRD generation pipeline. DO NOT EDIT.

package ops

import (
	"errors"
	"testing"
	sdkkonnectcomp "github.com/Kong/sdk-konnect-go/models/components"
	sdkkonnectops "github.com/Kong/sdk-konnect-go/models/operations"
	"github.com/Kong/sdk-konnect-go/test/mocks"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	konnectv1alpha1 "github.com/kong/kong-operator/v2/api/konnect/v1alpha1"
)

func testGeneratedEventGatewayVirtualClusterForSDKOps() *konnectv1alpha1.EventGatewayVirtualCluster {
	return &konnectv1alpha1.EventGatewayVirtualCluster{
		TypeMeta: metav1.TypeMeta{
			APIVersion: konnectv1alpha1.GroupVersion.String(),
			Kind:       "EventGatewayVirtualCluster",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:       "eventgatewayvirtualcluster",
			Namespace:  "default",
			UID:        "eventgatewayvirtualcluster-uid",
			Generation: 3,
		},
		Spec: konnectv1alpha1.EventGatewayVirtualClusterSpec{
			APISpec: konnectv1alpha1.EventGatewayVirtualClusterAPISpec{
				AclMode: konnectv1alpha1.VirtualClusterACLMode("test-value"),
				Description: "test-value",
				DNSLabel: konnectv1alpha1.VirtualClusterDNSLabel("test-value"),
				Labels: konnectv1alpha1.Labels{"test-key": "test-value"},
				Name: konnectv1alpha1.VirtualClusterName("test-value"),
			},
		},
	}
}

func TestCreateEventGatewayVirtualCluster_UsesSDKOpsConversion(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockEventGatewayVirtualClustersSDK(t)
	obj := testGeneratedEventGatewayVirtualClusterForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	expectedRequest, err := obj.ToCreateVirtualClusterRequest()
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	expectedID := "eventgatewayvirtualcluster-id"

	sdk.EXPECT().
		CreateEventGatewayVirtualCluster(
			mock.Anything,
			parentID,
			expectedRequest,
		).
		Return(&sdkkonnectops.CreateEventGatewayVirtualClusterResponse{
			VirtualCluster: &sdkkonnectcomp.VirtualCluster{
				ID: expectedID,
			},
		}, nil).
		Once()

	require.NoError(t, createEventGatewayVirtualCluster(ctx, sdk, obj))
	require.Equal(t, expectedID, obj.GetKonnectID())
}

func TestCreateEventGatewayVirtualCluster_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockEventGatewayVirtualClustersSDK(t)
	obj := testGeneratedEventGatewayVirtualClusterForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	expectedRequest, err := obj.ToCreateVirtualClusterRequest()
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		CreateEventGatewayVirtualCluster(
			mock.Anything,
			parentID,
			expectedRequest,
		).
		Return(nil, sdkErr).
		Once()

	err = createEventGatewayVirtualCluster(ctx, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}

func TestUpdateEventGatewayVirtualCluster_UsesSDKOpsConversion(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockEventGatewayVirtualClustersSDK(t)
	obj := testGeneratedEventGatewayVirtualClusterForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("eventgatewayvirtualcluster-id")
	expectedRequest, err := obj.ToUpdateVirtualClusterRequest()
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)

	sdk.EXPECT().
		UpdateEventGatewayVirtualCluster(
			mock.Anything,
			sdkkonnectops.UpdateEventGatewayVirtualClusterRequest{
				GatewayID: parentID,
				VirtualClusterID: obj.GetKonnectStatus().GetKonnectID(),
				UpdateVirtualClusterRequest: expectedRequest,
			},
		).
		Return(&sdkkonnectops.UpdateEventGatewayVirtualClusterResponse{}, nil).
		Once()

	require.NoError(t, updateEventGatewayVirtualCluster(ctx, sdk, obj))
}

func TestUpdateEventGatewayVirtualCluster_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockEventGatewayVirtualClustersSDK(t)
	obj := testGeneratedEventGatewayVirtualClusterForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("eventgatewayvirtualcluster-id")
	expectedRequest, err := obj.ToUpdateVirtualClusterRequest()
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		UpdateEventGatewayVirtualCluster(
			mock.Anything,
			sdkkonnectops.UpdateEventGatewayVirtualClusterRequest{
				GatewayID: parentID,
				VirtualClusterID: obj.GetKonnectStatus().GetKonnectID(),
				UpdateVirtualClusterRequest: expectedRequest,
			},
		).
		Return(nil, sdkErr).
		Once()

	err = updateEventGatewayVirtualCluster(ctx, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}

func TestDeleteEventGatewayVirtualCluster_UsesGeneratedSDKOps(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockEventGatewayVirtualClustersSDK(t)
	obj := testGeneratedEventGatewayVirtualClusterForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("eventgatewayvirtualcluster-id")

	sdk.EXPECT().
		DeleteEventGatewayVirtualCluster(
			mock.Anything,
			parentID,
			obj.GetKonnectStatus().GetKonnectID(),
		).
		Return(&sdkkonnectops.DeleteEventGatewayVirtualClusterResponse{}, nil).
		Once()

	require.NoError(t, deleteEventGatewayVirtualCluster(ctx, sdk, obj))
}

func TestDeleteEventGatewayVirtualCluster_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockEventGatewayVirtualClustersSDK(t)
	obj := testGeneratedEventGatewayVirtualClusterForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("eventgatewayvirtualcluster-id")
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		DeleteEventGatewayVirtualCluster(
			mock.Anything,
			parentID,
			obj.GetKonnectStatus().GetKonnectID(),
		).
		Return(nil, sdkErr).
		Once()

	err := deleteEventGatewayVirtualCluster(ctx, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}