// Code generated by CRD generation pipeline. DO NOT EDIT.

package ops

import (
	"errors"
	"testing"
	sdkkonnectcomp "github.com/Kong/sdk-konnect-go/models/components"
	sdkkonnectops "github.com/Kong/sdk-konnect-go/models/operations"
	"github.com/Kong/sdk-konnect-go/test/mocks"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
	"k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	konnectv1alpha1 "github.com/kong/kong-operator/v2/api/konnect/v1alpha1"
)

func testGeneratedAIGatewayAgentForSDKOps() *konnectv1alpha1.AIGatewayAgent {
	return &konnectv1alpha1.AIGatewayAgent{
		TypeMeta: metav1.TypeMeta{
			APIVersion: konnectv1alpha1.GroupVersion.String(),
			Kind:       "AIGatewayAgent",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:       "aigatewayagent",
			Namespace:  "default",
			UID:        "aigatewayagent-uid",
			Generation: 3,
		},
		Spec: konnectv1alpha1.AIGatewayAgentSpec{
			APISpec: konnectv1alpha1.AIGatewayAgentAPISpec{
				DisplayName: "test-value",
				Enabled: "Enabled",
				Labels: konnectv1alpha1.PublicLabels{"test-key": "test-value"},
				ManagedBy: konnectv1alpha1.ManagedBy{"test-key": "test-value"},
				Name: "test-value",
				Type: "a2a",
			},
		},
	}
}

func TestCreateAIGatewayAgent_UsesSDKOpsConversion(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayAgentsSDK(t)
	cl := fake.NewClientBuilder().WithScheme(scheme.Scheme).Build()
	obj := testGeneratedAIGatewayAgentForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	expectedRequest, err := obj.ToCreateAIGatewayAgentRequest(ctx, cl)
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	expectedID := "aigatewayagent-id"

	sdk.EXPECT().
		CreateAiGatewayAgent(
			mock.Anything,
			parentID,
			*expectedRequest,
		).
		Return(&sdkkonnectops.CreateAiGatewayAgentResponse{
			AIGatewayAgent: &sdkkonnectcomp.AIGatewayAgent{
				ID: expectedID,
			},
		}, nil).
		Once()

	require.NoError(t, createAIGatewayAgent(ctx, cl, sdk, obj))
	require.Equal(t, expectedID, obj.GetKonnectID())
}

func TestCreateAIGatewayAgent_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayAgentsSDK(t)
	cl := fake.NewClientBuilder().WithScheme(scheme.Scheme).Build()
	obj := testGeneratedAIGatewayAgentForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	expectedRequest, err := obj.ToCreateAIGatewayAgentRequest(ctx, cl)
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		CreateAiGatewayAgent(
			mock.Anything,
			parentID,
			*expectedRequest,
		).
		Return(nil, sdkErr).
		Once()

	err = createAIGatewayAgent(ctx, cl, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}

func TestUpdateAIGatewayAgent_UsesSDKOpsConversion(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayAgentsSDK(t)
	cl := fake.NewClientBuilder().WithScheme(scheme.Scheme).Build()
	obj := testGeneratedAIGatewayAgentForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("aigatewayagent-id")
	expectedRequest, err := obj.ToUpdateAIGatewayAgentRequest(ctx, cl)
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)

	sdk.EXPECT().
		UpdateAiGatewayAgent(
			mock.Anything,
			sdkkonnectops.UpdateAiGatewayAgentRequest{
				GatewayID: parentID,
				AgentIDOrName: obj.GetKonnectStatus().GetKonnectID(),
				UpdateAIGatewayAgentRequest: *expectedRequest,
			},
		).
		Return(&sdkkonnectops.UpdateAiGatewayAgentResponse{}, nil).
		Once()

	require.NoError(t, updateAIGatewayAgent(ctx, cl, sdk, obj))
}

func TestUpdateAIGatewayAgent_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayAgentsSDK(t)
	cl := fake.NewClientBuilder().WithScheme(scheme.Scheme).Build()
	obj := testGeneratedAIGatewayAgentForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("aigatewayagent-id")
	expectedRequest, err := obj.ToUpdateAIGatewayAgentRequest(ctx, cl)
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		UpdateAiGatewayAgent(
			mock.Anything,
			sdkkonnectops.UpdateAiGatewayAgentRequest{
				GatewayID: parentID,
				AgentIDOrName: obj.GetKonnectStatus().GetKonnectID(),
				UpdateAIGatewayAgentRequest: *expectedRequest,
			},
		).
		Return(nil, sdkErr).
		Once()

	err = updateAIGatewayAgent(ctx, cl, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}

func TestDeleteAIGatewayAgent_UsesGeneratedSDKOps(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayAgentsSDK(t)
	obj := testGeneratedAIGatewayAgentForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("aigatewayagent-id")

	sdk.EXPECT().
		DeleteAiGatewayAgent(
			mock.Anything,
			parentID,
			obj.GetKonnectStatus().GetKonnectID(),
		).
		Return(&sdkkonnectops.DeleteAiGatewayAgentResponse{}, nil).
		Once()

	require.NoError(t, deleteAIGatewayAgent(ctx, sdk, obj))
}

func TestDeleteAIGatewayAgent_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayAgentsSDK(t)
	obj := testGeneratedAIGatewayAgentForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("aigatewayagent-id")
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		DeleteAiGatewayAgent(
			mock.Anything,
			parentID,
			obj.GetKonnectStatus().GetKonnectID(),
		).
		Return(nil, sdkErr).
		Once()

	err := deleteAIGatewayAgent(ctx, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}