// Code generated by CRD generation pipeline. DO NOT EDIT.

package ops

import (
	"errors"
	sdkkonnectcomp "github.com/Kong/sdk-konnect-go/models/components"
	sdkkonnectops "github.com/Kong/sdk-konnect-go/models/operations"
	"github.com/Kong/sdk-konnect-go/test/mocks"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"testing"

	konnectv1alpha1 "github.com/kong/kong-operator/v2/api/konnect/v1alpha1"
)

func testGeneratedAIGatewayPolicyForSDKOps() *konnectv1alpha1.AIGatewayPolicy {
	return &konnectv1alpha1.AIGatewayPolicy{
		TypeMeta: metav1.TypeMeta{
			APIVersion: konnectv1alpha1.GroupVersion.String(),
			Kind:       "AIGatewayPolicy",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:       "aigatewaypolicy",
			Namespace:  "default",
			UID:        "aigatewaypolicy-uid",
			Generation: 3,
		},
		Spec: konnectv1alpha1.AIGatewayPolicySpec{
			APISpec: konnectv1alpha1.AIGatewayPolicyAPISpec{
				DisplayName: "test-value",
				Enabled:     "Enabled",
				Global:      "Enabled",
				Labels:      konnectv1alpha1.PublicLabels{"test-key": "test-value"},
				ManagedBy:   konnectv1alpha1.ManagedBy{"test-key": "test-value"},
				Name:        "test-value",
				Type:        "test-value",
			},
		},
	}
}

func TestCreateAIGatewayPolicy_UsesSDKOpsConversion(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayPoliciesSDK(t)
	cl := fake.NewClientBuilder().WithScheme(scheme.Scheme).Build()
	obj := testGeneratedAIGatewayPolicyForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	expectedRequest, err := obj.ToCreateAIGatewayPolicyRequest(ctx, cl)
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	expectedID := "aigatewaypolicy-id"

	sdk.EXPECT().
		CreateAiGatewayPolicy(
			mock.Anything,
			parentID,
			*expectedRequest,
		).
		Return(&sdkkonnectops.CreateAiGatewayPolicyResponse{
			AIGatewayPolicy: &sdkkonnectcomp.AIGatewayPolicy{
				ID: expectedID,
			},
		}, nil).
		Once()

	require.NoError(t, createAIGatewayPolicy(ctx, cl, sdk, obj))
	require.Equal(t, expectedID, obj.GetKonnectID())
}

func TestCreateAIGatewayPolicy_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayPoliciesSDK(t)
	cl := fake.NewClientBuilder().WithScheme(scheme.Scheme).Build()
	obj := testGeneratedAIGatewayPolicyForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	expectedRequest, err := obj.ToCreateAIGatewayPolicyRequest(ctx, cl)
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		CreateAiGatewayPolicy(
			mock.Anything,
			parentID,
			*expectedRequest,
		).
		Return(nil, sdkErr).
		Once()

	err = createAIGatewayPolicy(ctx, cl, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}

func TestUpdateAIGatewayPolicy_UsesSDKOpsConversion(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayPoliciesSDK(t)
	cl := fake.NewClientBuilder().WithScheme(scheme.Scheme).Build()
	obj := testGeneratedAIGatewayPolicyForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("aigatewaypolicy-id")
	expectedRequest, err := obj.ToUpdateAIGatewayPolicyRequest(ctx, cl)
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)

	sdk.EXPECT().
		UpdateAiGatewayPolicy(
			mock.Anything,
			sdkkonnectops.UpdateAiGatewayPolicyRequest{
				GatewayID:                    parentID,
				PolicyIDOrName:               obj.GetKonnectStatus().GetKonnectID(),
				UpdateAIGatewayPolicyRequest: *expectedRequest,
			},
		).
		Return(&sdkkonnectops.UpdateAiGatewayPolicyResponse{}, nil).
		Once()

	require.NoError(t, updateAIGatewayPolicy(ctx, cl, sdk, obj))
}

func TestUpdateAIGatewayPolicy_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayPoliciesSDK(t)
	cl := fake.NewClientBuilder().WithScheme(scheme.Scheme).Build()
	obj := testGeneratedAIGatewayPolicyForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("aigatewaypolicy-id")
	expectedRequest, err := obj.ToUpdateAIGatewayPolicyRequest(ctx, cl)
	require.NoError(t, err)
	expectedRequest.Labels = WithKubernetesMetadataLabels(obj, expectedRequest.Labels)
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		UpdateAiGatewayPolicy(
			mock.Anything,
			sdkkonnectops.UpdateAiGatewayPolicyRequest{
				GatewayID:                    parentID,
				PolicyIDOrName:               obj.GetKonnectStatus().GetKonnectID(),
				UpdateAIGatewayPolicyRequest: *expectedRequest,
			},
		).
		Return(nil, sdkErr).
		Once()

	err = updateAIGatewayPolicy(ctx, cl, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}

func TestDeleteAIGatewayPolicy_UsesGeneratedSDKOps(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayPoliciesSDK(t)
	obj := testGeneratedAIGatewayPolicyForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("aigatewaypolicy-id")

	sdk.EXPECT().
		DeleteAiGatewayPolicy(
			mock.Anything,
			parentID,
			obj.GetKonnectStatus().GetKonnectID(),
		).
		Return(&sdkkonnectops.DeleteAiGatewayPolicyResponse{}, nil).
		Once()

	require.NoError(t, deleteAIGatewayPolicy(ctx, sdk, obj))
}

func TestDeleteAIGatewayPolicy_PropagatesSDKError(t *testing.T) {
	t.Parallel()

	ctx := t.Context()
	sdk := mocks.NewMockAIGatewayPoliciesSDK(t)
	obj := testGeneratedAIGatewayPolicyForSDKOps()
	parentID := "parentID-1"
	obj.SetGatewayID(parentID)
	obj.SetKonnectID("aigatewaypolicy-id")
	sdkErr := errors.New("sdk error")

	sdk.EXPECT().
		DeleteAiGatewayPolicy(
			mock.Anything,
			parentID,
			obj.GetKonnectStatus().GetKonnectID(),
		).
		Return(nil, sdkErr).
		Once()

	err := deleteAIGatewayPolicy(ctx, sdk, obj)
	require.ErrorContains(t, err, sdkErr.Error())
}
