{{- define "gvList" -}}
{{- $groupVersions := . -}}

<!-- This document is generated by KGO's 'generate.docs' make target, DO NOT EDIT -->

{{- /* Prepare a GV -> hasSupportedTypes mapping for later lookups */ -}}
{{- $supportedTypesByGV := dict -}}
{{- range $groupVersions -}}
    {{- $hasSupportedTypes := false -}}
    {{- range $typ := .SortedTypes -}}
        {{- if index $typ.Markers "apireference:kgo:include" -}}
            {{- $hasSupportedTypes = true -}}
        {{- end -}}
    {{- end -}}
    {{- if $hasSupportedTypes -}}
        {{- $_ := set $supportedTypesByGV .GroupVersionString $hasSupportedTypes -}}
    {{- end -}}
{{- end }}

## Packages
{{- range $groupVersions }}
{{- if hasKey $supportedTypesByGV .GroupVersionString }}
- {{ markdownRenderGVLink . }}
{{- end }}
{{- end }}

{{ range $groupVersions }}
{{- if hasKey $supportedTypesByGV .GroupVersionString }}
{{ template "gvDetails" . }}
{{- end }}
{{ end }}

{{- end -}}
