// Code generated by CRD generation pipeline. DO NOT EDIT.

package konnect

import (
	"sigs.k8s.io/controller-runtime/pkg/client"

	konnectv1alpha1 "github.com/kong/kong-operator/v2/api/konnect/v1alpha1"
	"github.com/kong/kong-operator/v2/controller/konnect/constraints"
	"github.com/kong/kong-operator/v2/internal/utils/index"
)

var generatedKonnectAPIAuthReferencingTypes = []constraints.EntityWithKonnectAPIAuthConfigurationRef{
	&konnectv1alpha1.KonnectAIGateway{},
	&konnectv1alpha1.KonnectEventGateway{},
	&konnectv1alpha1.Portal{},
}

var generatedKonnectAPIAuthReferencingTypeListsWithIndexes = map[client.ObjectList]string{
	&konnectv1alpha1.KonnectAIGatewayList{}:    index.IndexFieldKonnectAIGatewayOnAPIAuthConfiguration,
	&konnectv1alpha1.KonnectEventGatewayList{}: index.IndexFieldKonnectEventGatewayOnAPIAuthConfiguration,
	&konnectv1alpha1.PortalList{}:              index.IndexFieldPortalOnAPIAuthConfiguration,
}
