// Code generated by CRD generation pipeline. DO NOT EDIT.

package konnect

import (
	"context"

	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
	konnectapiauthv1alpha1 "github.com/kong/kong-operator/v2/api/konnect/v1alpha1"
	xkonnectv1alpha1 "github.com/kong/kong-operator/v2/api/x-konnect/v1alpha1"
	"github.com/kong/kong-operator/v2/internal/utils/index"
)

// PortalReconciliationWatchOptions returns the watch options for
// the Portal.
func PortalReconciliationWatchOptions(
	cl client.Client,
) []func(*ctrl.Builder) *ctrl.Builder {
	return []func(*ctrl.Builder) *ctrl.Builder{
		func(b *ctrl.Builder) *ctrl.Builder {
			return b.For(&xkonnectv1alpha1.Portal{})
		},
		func(b *ctrl.Builder) *ctrl.Builder {
			return b.Watches(
				&konnectapiauthv1alpha1.KonnectAPIAuthConfiguration{},
				handler.EnqueueRequestsFromMapFunc(
					enqueuePortalForKonnectAPIAuthConfiguration(cl),
				),
			)
		},
	}
}

func enqueuePortalForKonnectAPIAuthConfiguration(
	cl client.Client,
) func(ctx context.Context, obj client.Object) []reconcile.Request {
	return func(ctx context.Context, obj client.Object) []reconcile.Request {
		auth, ok := obj.(*konnectapiauthv1alpha1.KonnectAPIAuthConfiguration)
		if !ok {
			return nil
		}
		var l xkonnectv1alpha1.PortalList
		if err := cl.List(ctx, &l,
			// TODO: change this when cross namespace refs are allowed.
			client.InNamespace(auth.GetNamespace()),
			client.MatchingFields{
				index.IndexFieldPortalOnAPIAuthConfiguration: auth.Namespace + "/" + auth.Name,
			},
		); err != nil {
			return nil
		}
		return objectListToReconcileRequests(l.Items)
	}
}
