name: envtest tests
run-name: "envtest tests ${{ format('{0}', inputs.cluster_version) }} "

on:
  workflow_call:
    inputs:
      cluster_version:
        description: "The Kubernetes cluster version to use for envtest"
        type: string
        required: true

permissions:
  contents: read

env:
  MISE_VERBOSE: 1
  MISE_DEBUG: 1

jobs:
  envtest-tests:
    timeout-minutes: ${{ fromJSON(vars.GHA_EXTENDED_TIMEOUT_MINUTES || 60) }}
    runs-on: ubuntu-latest
    name: ${{ format('{0}', inputs.cluster_version) }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: go.mod
        cache: false
    - run: echo "GO_MOD_CACHE=$(go env GOMODCACHE)" >> $GITHUB_ENV
    - run: echo "GO_BUILD_CACHE=$(go env GOCACHE)" >> $GITHUB_ENV

    - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      with:
        install: false

    - uses: Kong/kong-license@62d5e200998d4b19ed6b78591332a092536c63f5 # master @ 20260330
      id: license
      with:
        op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    - run: echo "GO_CACHE_KEY=go-envtest-${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.mod') }}" >> $GITHUB_ENV
    - run: echo "GO_CACHE_KEY_2=go-envtest-${{ runner.os }}-${{ runner.arch }}-go-" >> $GITHUB_ENV

    - name: Go cache main branch
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8
      with:
        path: |
          ${{ env.GO_MOD_CACHE }}
          ${{ env.GO_BUILD_CACHE }}
        key: ${{ env.GO_CACHE_KEY }}
        restore-keys: |
          ${{ env.GO_CACHE_KEY }}
          ${{ env.GO_CACHE_KEY_2 }}

    - name: Go cache (restore only for non-main branches)
      if: ${{ github.ref != 'refs/heads/main' }}
      uses: actions/cache/restore@2c8a9bd7457de244a408f35966fab2fb45fda9c8
      with:
        path: |
          ${{ env.GO_MOD_CACHE }}
          ${{ env.GO_BUILD_CACHE }}
        key: ${{ env.GO_CACHE_KEY }}
        restore-keys: |
          ${{ env.GO_CACHE_KEY }}
          ${{ env.GO_CACHE_KEY_2 }}

    - name: run envtest tests
      env:
        KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        GOTESTSUM_JUNITFILE: envtest-tests.xml
      run: |
        VERSION="${{ inputs.cluster_version }}"
        # Remove leading 'v'
        VERSION="${VERSION#v}"
        # Remove patch number as envtest releases are not provided for every patch version
        VERSION="${VERSION%.*}"
        echo "Cluster version: $VERSION"
        make test.envtest CLUSTER_VERSION=${VERSION}

    - name: collect test coverage
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: coverage-envtest-tests
        path: coverage.envtest.out

    - name: collect test report
      if: ${{ always() }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: tests-report-envtest-tests
        path: envtest-tests.xml
