name: Reusable govulncheck

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git reference to check out'
        required: true
        type: string

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: ${{ inputs.ref }}
        
    - uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1.1.0
      with:
        repo-checkout: false
        output-format: sarif
        output-file: results_${{ steps.checkout.outputs.commit }}.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v3.29.5
      with:
        sarif_file: results_${{ steps.checkout.outputs.commit }}.sarif
        ref: refs/heads/${{ inputs.ref }}
        sha: ${{ steps.checkout.outputs.commit }}
        category: govulncheck
