name: Integration tests

on:
  workflow_call:
    inputs:
      cluster_version:
        description: "The Kubernetes cluster version to use for envtest"
        type: string
        required: true
      kong-image-repo:
        description: "Kong Gateway Docker image repository override. If not set,
          defaults are used."
        type: string
        required: false
      kong-image-tag:
        description: "Kong Gateway Docker image tag override."
        type: string
        required: false
      kong-effective-version:
        description: "Effective semantic version of Kong Gateway. If not given, parsed
          from the image tag."
        type: string
        required: false

permissions:
  contents: read

env:
  MISE_VERBOSE: 1
  MISE_DEBUG: 1

jobs:
  integration-tests:
    timeout-minutes: ${{ fromJSON(vars.GHA_EXTENDED_TIMEOUT_MINUTES || 60) }}
    runs-on: ubuntu-latest
    name: ${{ format('{0} {1} {2} - {3}', matrix.suite, matrix.kong-variant, matrix.router_flavor, inputs.cluster_version) }}
    strategy:
      matrix:
        include:
          - suite: ko
          - suite: konnect
          - suite: kic
            kong-variant: enterprise
          - suite: kic
            kong-variant: oss
          - suite: bluegreen
          - suite: validatingwebhook
            router_flavor: traditional_compatible
          - suite: validatingwebhook
            router_flavor: expressions
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod
        cache: false

    - uses: ./.github/actions/setup-mise
      with:
        install: false

    - uses: Kong/kong-license@ddccb487a0b319cef85f348b16a1ad2b6d9c1df7 # master @ 20260529
      id: license
      with:
        op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    - name: set kong oss version
      if: ${{ matrix.suite == 'kic' && matrix.kong-variant == 'oss' && inputs.kong-image-repo == '' }}
      run: |
        echo "TEST_KONG_IMAGE=kong" >> $GITHUB_ENV
        echo "TEST_KONG_TAG=$(yq -ojson -r '.integration.kong-oss' < test/test_dependencies.yaml )" >> $GITHUB_ENV

    - name: set kong ee version
      if: ${{ matrix.suite == 'kic' && matrix.kong-variant == 'enterprise' && inputs.kong-image-repo == '' }}
      run: |
        echo "TEST_KONG_IMAGE=kong/kong-gateway" >> $GITHUB_ENV
        echo "TEST_KONG_TAG=$(yq -ojson -r '.integration.kong-ee' < test/test_dependencies.yaml )" >> $GITHUB_ENV

    - name: set kong image override
      if: ${{ inputs.kong-image-repo != '' }}
      env:
        KONG_IMAGE_REPO: ${{ inputs.kong-image-repo }}
        KONG_IMAGE_TAG: ${{ inputs.kong-image-tag }}
      run: |
        echo "TEST_KONG_IMAGE=$KONG_IMAGE_REPO" >> $GITHUB_ENV
        echo "TEST_KONG_TAG=$KONG_IMAGE_TAG" >> $GITHUB_ENV

    - name: set kong effective version
      if: ${{ inputs.kong-effective-version != '' }}
      env:
        KONG_EFFECTIVE_VERSION: ${{ inputs.kong-effective-version }}
      run: |
        echo "TEST_KONG_EFFECTIVE_VERSION=$KONG_EFFECTIVE_VERSION" >> $GITHUB_ENV

    - run: echo "GO_MOD_CACHE=$(go env GOMODCACHE)" >> $GITHUB_ENV
    - run: echo "GO_BUILD_CACHE=$(go env GOCACHE)" >> $GITHUB_ENV

    # Create cache keys just for the suite. Different e.g. flavors do not warrant
    # a separate cache since they all use the same dependencies, so we can save some
    # cache storage and increase hit rate by not including the router flavor in the key.
    #
    # Separate cache keys only for kic and ko to minimize cache eviction.
    - name: Compute Go build cache key
      env:
        RUNNER_OS: ${{ runner.os }}
        RUNNER_ARCH: ${{ runner.arch }}
        GO_MOD_HASH: ${{ hashFiles('**/go.mod') }}
        CACHE_SUFFIX: ${{ matrix.suite == 'kic' && 'kic' || 'ko' }}
      run: |
        {
          echo "GO_CACHE_KEY=go-integrationtests-$CACHE_SUFFIX-$RUNNER_OS-$RUNNER_ARCH-go-$GO_MOD_HASH"
          echo "GO_CACHE_KEY_2=go-integrationtests-$CACHE_SUFFIX-$RUNNER_OS-$RUNNER_ARCH-go-"
          echo "GO_CACHE_KEY_3=go-integrationtests-"
        } >> $GITHUB_ENV

    - name: Go cache main branch
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
      with:
        path: |
          ${{ env.GO_MOD_CACHE }}
          ${{ env.GO_BUILD_CACHE }}
        key: ${{ env.GO_CACHE_KEY }}
        restore-keys: |
          ${{ env.GO_CACHE_KEY }}
          ${{ env.GO_CACHE_KEY_2 }}
          ${{ env.GO_CACHE_KEY_3 }}

    - name: Go cache (restore only for non-main branches)
      if: ${{ github.ref != 'refs/heads/main' }}
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
      with:
        path: |
          ${{ env.GO_MOD_CACHE }}
          ${{ env.GO_BUILD_CACHE }}
        key: ${{ env.GO_CACHE_KEY }}
        restore-keys: |
          ${{ env.GO_CACHE_KEY }}
          ${{ env.GO_CACHE_KEY_2 }}
          ${{ env.GO_CACHE_KEY_3 }}

    - name: start tcpdump capture
      env:
        SUITE: ${{ matrix.suite }}
        KONG_VARIANT: ${{ matrix.kong-variant }}
        ROUTER_FLAVOR: ${{ matrix.router_flavor }}
      run: |
        sudo tcpdump -i any 'dst port 443' -w "/tmp/capture-$SUITE-$KONG_VARIANT-$ROUTER_FLAVOR.pcap" &
        echo $! > /tmp/tcpdump.pid

    - uses: ./.github/actions/bump-inotify

    - name: run integration tests
      run: make "test.integration-$SUITE"
      env:
        SUITE: ${{ matrix.suite }}
        KONG_PLUGIN_IMAGE_REGISTRY_CREDENTIALS: ${{ secrets.KONG_PLUGIN_IMAGE_REGISTRY_CREDENTIALS }}
        KONG_CONTROLLER_OUT: stdout
        GOTESTSUM_JUNITFILE: "integration-tests-${{ matrix.suite }}-${{ matrix.kong-variant }}-${{ matrix.router_flavor }}.xml"
        KONG_TEST_KONNECT_ACCESS_TOKEN: ${{ secrets.KONG_TEST_KONNECT_ACCESS_TOKEN }}
        KONG_TEST_KONNECT_SERVER_URL: us.api.konghq.tech
        KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        KONG_CLUSTER_VERSION: ${{ inputs.cluster_version }}
        # This is needed for ktf to find latest releases of addons.
        # This could be changed so that ktf addons have their versions pinned
        # in the test Makefile instead.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: stop tcpdump capture
      if: always()
      run: |
        if [ -f /tmp/tcpdump.pid ]; then
          sudo kill "$(cat /tmp/tcpdump.pid)" || true
        fi

    - name: upload pcap capture
      if: failure()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: pcap-integration-${{ matrix.suite }}-${{ matrix.kong-variant }}-${{ matrix.router_flavor }}
        path: /tmp/capture-${{ matrix.suite }}-${{ matrix.kong-variant }}-${{ matrix.router_flavor }}.pcap
        if-no-files-found: ignore

    - name: upload diagnostics
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: diagnostics-integration-${{ matrix.suite }}-${{ matrix.kong-variant }}
        path: /tmp/ktf-diag*
        if-no-files-found: ignore

    - name: collect test coverage
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ matrix.suite }}-${{ matrix.kong-variant }}-coverage-integration
        path: coverage.integration.${{ matrix.suite }}-${{ matrix.kong-variant }}-${{ matrix.router_flavor }}.out

    - name: collect test report
      if: ${{ always() }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ matrix.suite }}-${{ matrix.kong-variant }}-tests-report-integration
        path: integration-tests-${{ matrix.suite }}-${{ matrix.kong-variant }}-${{ matrix.router_flavor }}.xml
