name: kong integration tests

on:
  workflow_call:
    inputs:
      kong-image-repo:
        description: "Kong Gateway Docker image repository override. If not set,
          defaults are used from test_dependencies.yaml."
        type: string
        required: false
      kong-image-tag:
        description: "Kong Gateway Docker image tag override."
        type: string
        required: false
      kong-effective-version:
        description: "Effective semantic version of Kong Gateway. If not given, parsed
          from the image tag."
        type: string
        required: false

permissions:
  contents: read

env:
  MISE_VERBOSE: 1
  MISE_DEBUG: 1

jobs:
  kongintegration-tests:
    timeout-minutes: ${{ fromJSON(vars.GHA_EXTENDED_TIMEOUT_MINUTES || 60) }}
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: enterprise
            enterprise: true
          - name: oss
            enterprise: false
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        id: setup-go
        with:
          go-version-file: go.mod
          cache: false
      - run: |
          echo "GO_MOD_CACHE=$(go env GOMODCACHE)" >> $GITHUB_ENV
          echo "GO_BUILD_CACHE=$(go env GOCACHE)" >> $GITHUB_ENV

      - uses: Kong/kong-license@62d5e200998d4b19ed6b78591332a092536c63f5 # master @ 20260330
        id: license
        with:
          op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: set kong oss version
        if: ${{ !matrix.enterprise && inputs.kong-image-repo == '' }}
        run: |
          echo "TEST_KONG_IMAGE=kong" >> $GITHUB_ENV
          echo "TEST_KONG_TAG=$(yq -ojson -r '.kongintegration.kong-oss' < test/test_dependencies.yaml )" >> $GITHUB_ENV

      - name: set kong ee version
        if: ${{ matrix.enterprise && inputs.kong-image-repo == '' }}
        run: |
          echo "TEST_KONG_IMAGE=kong/kong-gateway" >> $GITHUB_ENV
          echo "TEST_KONG_TAG=$(yq -ojson -r '.kongintegration.kong-ee' < test/test_dependencies.yaml )" >> $GITHUB_ENV

      - name: set kong image override
        if: ${{ inputs.kong-image-repo != '' }}
        run: |
          echo "TEST_KONG_IMAGE=${{ inputs.kong-image-repo }}" >> $GITHUB_ENV
          echo "TEST_KONG_TAG=${{ inputs.kong-image-tag }}" >> $GITHUB_ENV

      - name: set kong effective version
        if: ${{ inputs.kong-effective-version != '' }}
        run: |
          echo "TEST_KONG_EFFECTIVE_VERSION=${{ inputs.kong-effective-version }}" >> $GITHUB_ENV

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          install: false

      - run: echo "GOTESTSUM_JUNITFILE=kongintegration-${{ matrix.name }}-tests.xml" >>
          $GITHUB_ENV
      # Share the cache key across all kongintegration tests since they all use the same dependencies.
      - run: echo "GO_CACHE_KEY=go-kongintegration-${{ runner.os }}-${{ runner.arch
          }}-go-${{ hashFiles('**/go.mod') }}" >> $GITHUB_ENV
      - run: echo "GO_CACHE_KEY_2=go-kongintegration-${{ runner.os }}-${{ runner.arch
          }}-go-" >> $GITHUB_ENV

      - name: Go cache main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: |
            ${{ env.GO_MOD_CACHE }}
            ${{ env.GO_BUILD_CACHE }}
          key: ${{ env.GO_CACHE_KEY }}
          restore-keys: |
            ${{ env.GO_CACHE_KEY }}
            ${{ env.GO_CACHE_KEY_2 }}

      - name: Go cache (restore only for non-main branches)
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: |
            ${{ env.GO_MOD_CACHE }}
            ${{ env.GO_BUILD_CACHE }}
          key: ${{ env.GO_CACHE_KEY }}
          restore-keys: |
            ${{ env.GO_CACHE_KEY }}
            ${{ env.GO_CACHE_KEY_2 }}

      - name: run kong integration tests
        run: make test.kongintegration
        env:
          GOTESTSUM_JUNITFILE: ${{ env.GOTESTSUM_JUNITFILE }}
          KONG_CUSTOM_DOMAIN: konghq.tech
          KONG_TEST_KONNECT_ACCESS_TOKEN: ${{ secrets.KONG_TEST_KONNECT_ACCESS_TOKEN }}
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
          TEST_KONG_ENTERPRISE: ${{ matrix.enterprise }}

      - name: collect test coverage
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-kongintegration-${{ matrix.name }}
          path: coverage.*.out

      - name: collect test report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tests-report-kongintegration-${{ matrix.name }}
          path: ${{ env.GOTESTSUM_JUNITFILE }}
