name: cleanup

on:
  schedule:
    - cron: '8 */1 * * *' # Run once per hour
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  konnect:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: setup golang
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: cleanup orphaned test clusters
        run: go run ./hack/cleanup konnect
        env:
          KONG_TEST_KONNECT_ACCESS_TOKEN: ${{ secrets.KONG_TEST_KONNECT_ACCESS_TOKEN }}
          KONG_TEST_KONNECT_SERVER_URL: us.api.konghq.tech
          # Ref: https://github.com/Kong/sdk-konnect-go/issues/20
          KONG_CUSTOM_DOMAIN: konghq.tech
