name: falco-analyzed-e2e

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      konnect-pat:
        description: "Konnect PAT used by tests that hit Konnect"
        required: false
    
    inputs:
      test-image:
        description: "image used for e2e tests, if not set, the image built in the workflow will be used"
        required: false
        type: string
        default: ""

permissions:
  contents: read

env:
  MISE_VERBOSE: 1

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    outputs:
      falco_result: ${{ steps.falco_result.outcome }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0

    - name: start falco
      continue-on-error: true
      uses: falcosecurity/falco-actions/start@4a4ff48cca452b3b03f06073d1ae0ff564503fc9
      with:
        mode: analyze

    - name: setup golang
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod

    - name: build docker image
      if: ${{ inputs.test-image == '' }}
      env:
        IMG: kong-operator
        TAG: e2e-${{ github.sha }}
      run: make docker.build && echo "TEST_IMAGE=$IMG:$TAG" >> $GITHUB_ENV

    - name: set test image
      if: ${{ inputs.test-image != '' }}
      env:
         TEST_IMAGE: ${{ inputs.test-image }}
      run: |
        docker pull "$TEST_IMAGE"
        echo "TEST_IMAGE=$TEST_IMAGE" >> $GITHUB_ENV

    - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      with:
        install: false

    - name: run e2e tests
      run: make test.e2e
      env:
        KONG_TEST_KONG_OPERATOR_IMAGE_LOAD: ${{ env.TEST_IMAGE }}
        GOTESTSUM_JUNITFILE: "e2e-tests.xml"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KONG_TEST_KONNECT_ACCESS_TOKEN: ${{ secrets.konnect-pat }}
        KONG_TEST_KONNECT_SERVER_URL: us.api.konghq.tech

    - name: upload diagnostics
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: diagnostics-e2e
        path: /tmp/ktf-diag*
        if-no-files-found: ignore

    - name: stop falco and upload results
      id: falco_result
      continue-on-error: true
      uses: falcosecurity/falco-actions/stop@4a4ff48cca452b3b03f06073d1ae0ff564503fc9
      with:
        mode: analyze
  
  analyze_falco_results:
    name: Analyze Falco Results
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: run-e2e
    continue-on-error: true
    if: contains(needs.run-e2e.result, 'success') && needs.run-e2e.outputs.falco_result == 'success'
    permissions:
      contents: read
      actions: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout Source Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Analyze Falco Results
        uses: falcosecurity/falco-actions/analyze@4a4ff48cca452b3b03f06073d1ae0ff564503fc9
        continue-on-error: true
        with:
          custom-rule-file: ${{ github.workspace }}/.github/securityrules/custom_rules.yml

      - name: Upload Falco analysis report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: falco-analysis-report
          path: |
            /tmp/report_output.md
            /tmp/falco_events.json
            /tmp/proc.txt
            /tmp/files_written.txt
            /tmp/outbound.txt
            /tmp/dns_extract.txt
            /tmp/containers.txt
            /tmp/hashes.txt
          if-no-files-found: ignore
          retention-days: 14
