name: "Pull Request Labeler"
run-name: Pull Request Labeler, branch:${{ github.ref_name }}, triggered by @${{ github.actor }}

on:
- pull_request

permissions:
  contents: read

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13
